/**
 * Beat Pads Lane Placements — Boom Bap pack.
 * 30 each: kick · snare · clap · hihat · openHat · rim (one-lane 16th patterns).
 * Golden-era / sample-flip pocket — swung kicks, hard 2&4, dusty ghosts.
 */
import type {
  BeatPadsDrumRole,
  BeatPadsLanePlacementTemplate,
  BeatPadsPlacementGenre,
} from '@/app/lib/creationStation/beatPadsLanePlacementTemplates';

function bar(...steps: number[]): readonly number[] {
  return steps;
}

function tpl(
  id: string,
  name: string,
  role: BeatPadsDrumRole,
  genre: BeatPadsPlacementGenre,
  desc: string,
  steps: readonly number[],
): BeatPadsLanePlacementTemplate {
  return { id, name, role, genre, desc, steps };
}

/** @internal Merged into ALL_TEMPLATES. */
export const BEAT_PADS_BOOMBAP_LANE_TEMPLATES: readonly BeatPadsLanePlacementTemplate[] = [
  // ── BOOM BAP KICK (30) ──
  tpl('boombap-kick-classic', 'Classic Boom', 'kick', 'boombap', '1 and & of 3 — golden-era pocket', bar(0, 10)),
  tpl('boombap-kick-simple-13', 'Simple 1 & 3', 'kick', 'boombap', 'Plain downbeat and beat 3', bar(0, 8)),
  tpl('boombap-kick-swing-lean', 'Swing Lean', 'kick', 'boombap', '1 · & of 2 · & of 3 swing lean', bar(0, 6, 10)),
  tpl('boombap-kick-off-lean', 'Off-Kick Lean', 'kick', 'boombap', '1 · push before 2 · beat 3', bar(0, 3, 8)),
  tpl('boombap-kick-golden', 'Golden Era', 'kick', 'boombap', '1 · late push · beat 3 pocket', bar(0, 7, 8)),
  tpl('boombap-kick-push-double', 'Push Double', 'kick', 'boombap', '1 · & of 3 doubled into beat 3', bar(0, 10, 11)),
  tpl('boombap-kick-half-swing', 'Half Swing', 'kick', 'boombap', '1 · & of 2 · beat 3', bar(0, 6, 8)),
  tpl('boombap-kick-early-push', 'Early Push', 'kick', 'boombap', '1 · early push · beat 3', bar(0, 2, 8)),
  tpl('boombap-kick-behind', 'Behind Grid', 'kick', 'boombap', '1 · laid-back push into beat 3', bar(0, 9, 10)),
  tpl('boombap-kick-classic-plus', 'Classic Plus', 'kick', 'boombap', '1 · beat 3 · late push after 3', bar(0, 8, 11)),
  tpl('boombap-kick-off2', 'Off 2 Pocket', 'kick', 'boombap', '1 · beat 2 · & of 3 pocket', bar(0, 4, 10)),
  tpl('boombap-kick-minimal', 'Minimal One', 'kick', 'boombap', 'Downbeat only — stripped pocket', bar(0)),
  tpl('boombap-kick-pickup', 'Pickup Tail', 'kick', 'boombap', '1 · beat 3 · bar-end pickup', bar(0, 8, 14)),
  tpl('boombap-kick-boom-pickup', 'Boom + Pickup', 'kick', 'boombap', '1 · & of 3 · bar-end pickup', bar(0, 10, 14)),
  tpl('boombap-kick-rolling', 'Rolling Pocket', 'kick', 'boombap', '1 · early push · mid · & of 3', bar(0, 3, 6, 10)),
  tpl('boombap-kick-behind-3', 'Behind 3', 'kick', 'boombap', '1 · late push · & of 3', bar(0, 7, 10)),
  tpl('boombap-kick-skip', 'Groove Skip', 'kick', 'boombap', '1 · early push · mid · & of 3', bar(0, 2, 6, 10)),
  tpl('boombap-kick-late-bar', 'Late Bar Push', 'kick', 'boombap', '1 · & of 3 · late bar push', bar(0, 10, 13)),
  tpl('boombap-kick-triplet', 'Triplet Lean', 'kick', 'boombap', '1 · swung mid · & of 3 pair', bar(0, 6, 9, 10)),
  tpl('boombap-kick-double-pocket', 'Double Pocket', 'kick', 'boombap', '1 · beat 3 · & of 3 double', bar(0, 8, 10)),
  tpl('boombap-kick-sample-flip', 'Sample Flip', 'kick', 'boombap', '1 · syncopated mid · & of 3', bar(0, 5, 10)),
  tpl('boombap-kick-chop-pocket', 'Chop Pocket', 'kick', 'boombap', '1 · chop push · beat 3 · late', bar(0, 3, 8, 12)),
  tpl('boombap-kick-head-nod', 'Head Nod', 'kick', 'boombap', '1 · & of 2 · beat 3 · & of 4', bar(0, 6, 8, 14)),
  tpl('boombap-kick-crate', 'Crate Dig', 'kick', 'boombap', 'Sparse crate-digger knock', bar(0, 8, 15)),
  tpl('boombap-kick-vinyl', 'Vinyl Knock', 'kick', 'boombap', '1 · late 3 · soft ghost', bar(0, 9, 11)),
  tpl('boombap-kick-sp1200', 'SP Pocket', 'kick', 'boombap', 'Classic SP-style 1 · &3', bar(0, 10, 14)),
  tpl('boombap-kick-mpc', 'MPC Lean', 'kick', 'boombap', 'MPC swing lean 1 · mid · &3', bar(0, 5, 10, 11)),
  tpl('boombap-kick-dusty-trunk', 'Dusty Trunk', 'kick', 'boombap', 'Heavy trunk 1 · &3 · soft 4', bar(0, 10, 12)),
  tpl('boombap-kick-breakbeat', 'Breakbeat Lean', 'kick', 'boombap', 'Breakbeat lean 1 · push · 3 · &4', bar(0, 3, 8, 14)),
  tpl('boombap-kick-two-bar-feel', 'Two-Bar Feel', 'kick', 'boombap', '1 · early · &3 · pickup for two-bar loops', bar(0, 2, 10, 15)),

  // ── BOOM BAP SNARE (30) ──
  tpl('boombap-snare-24', 'Hard 2 & 4', 'snare', 'boombap', 'Hard boom-bap backbeat', bar(4, 12)),
  tpl('boombap-snare-ghost-tail', 'Ghost Tail', 'snare', 'boombap', '2 & 4 + soft ghost after 4', bar(4, 12, 14)),
  tpl('boombap-snare-laid', 'Laid-Back', 'snare', 'boombap', 'Backbeat sitting slightly behind', bar(5, 13)),
  tpl('boombap-snare-push-ghost', 'Push Ghost', 'snare', 'boombap', '2 & 4 + ghost before the bar line', bar(4, 12, 15)),
  tpl('boombap-snare-pickup', 'Pickup Ghost', 'snare', 'boombap', '2 & 4 + ghost pickup before 4', bar(4, 11, 12)),
  tpl('boombap-snare-ghost-mid', 'Ghost Mid', 'snare', 'boombap', '2 & 4 + ghost after beat 2', bar(4, 7, 12)),
  tpl('boombap-snare-half', 'Half-Time', 'snare', 'boombap', 'Single snare on beat 3', bar(8)),
  tpl('boombap-snare-off-ghost', 'Off Ghost', 'snare', 'boombap', '2 & 4 + ghost on & of 2', bar(4, 6, 12)),
  tpl('boombap-snare-sync', 'Sync Ghost', 'snare', 'boombap', '2 & 4 + syncopated ghost before 3', bar(4, 9, 12)),
  tpl('boombap-snare-double', 'Double Tap', 'snare', 'boombap', '2 & 4 with doubled hit on 4', bar(4, 12, 13)),
  tpl('boombap-snare-pickup-lead', 'Pickup Lead', 'snare', 'boombap', 'Ghost before 2, then 2 & 4', bar(3, 4, 12)),
  tpl('boombap-snare-tri', 'Triangulated', 'snare', 'boombap', '2 & 4 with mid-bar ghost', bar(4, 10, 12)),
  tpl('boombap-snare-early', 'Early Ghost', 'snare', 'boombap', 'Ghost after downbeat, then 2 & 4', bar(1, 4, 12)),
  tpl('boombap-snare-fill', 'Bar Fill', 'snare', 'boombap', '2 & 4 plus short bar-end fill', bar(4, 12, 14, 15)),
  tpl('boombap-snare-offbeat', 'Offbeat', 'snare', 'boombap', 'Snare on & of 2 and & of 4', bar(6, 14)),
  tpl('boombap-snare-beat2', 'Beat 2 Only', 'snare', 'boombap', 'Single snare on beat 2', bar(4)),
  tpl('boombap-snare-beat4', 'Beat 4 Only', 'snare', 'boombap', 'Single snare on beat 4', bar(12)),
  tpl('boombap-snare-wide', 'Wide Stack', 'snare', 'boombap', 'Layered snare width on backbeat', bar(4, 5, 12, 13)),
  tpl('boombap-snare-triplet', 'Triplet Ghost', 'snare', 'boombap', '2 & 4 with triplet ghost before 3', bar(4, 9, 10, 12)),
  tpl('boombap-snare-off13', 'Off 1 & 3', 'snare', 'boombap', 'Ghost variant on & of 1 and & of 3', bar(2, 10)),
  tpl('boombap-snare-crack', 'Crack 2', 'snare', 'boombap', 'Hard crack on beat 2 + soft 4', bar(4, 12, 14)),
  tpl('boombap-snare-rim-feel', 'Rim-Feel', 'snare', 'boombap', 'Rim-feel ghost then hard 2 & 4', bar(3, 4, 11, 12)),
  tpl('boombap-snare-flam', 'Flam Backbeat', 'snare', 'boombap', 'Flam texture around 2 & 4', bar(3, 4, 11, 12, 13)),
  tpl('boombap-snare-late-fill', 'Late Fill', 'snare', 'boombap', '2 & 4 + busy late fill', bar(4, 12, 13, 14, 15)),
  tpl('boombap-snare-ghost-dense', 'Dense Ghost', 'snare', 'boombap', '2 & 4 with dense ghost layer', bar(4, 6, 7, 12, 14)),
  tpl('boombap-snare-chop', 'Chop Snare', 'snare', 'boombap', 'Sample-chop snare accents', bar(4, 8, 12)),
  tpl('boombap-snare-swing-back', 'Swing Back', 'snare', 'boombap', 'Swung late 2 & 4 pocket', bar(5, 6, 13, 14)),
  tpl('boombap-snare-press', 'Press Roll', 'snare', 'boombap', 'Press-roll feel into beat 4', bar(4, 10, 11, 12)),
  tpl('boombap-snare-minimal-ghost', 'Minimal Ghost', 'snare', 'boombap', 'Hard 2 & 4 + one quiet ghost', bar(4, 12, 15)),
  tpl('boombap-snare-break-end', 'Break End', 'snare', 'boombap', 'Breakbeat-style bar-end snare run', bar(4, 12, 13, 15)),

  // ── BOOM BAP CLAP (30) ──
  tpl('boombap-clap-dusty-24', 'Dusty 2 & 4', 'clap', 'boombap', 'Dusty vinyl clap on 2 & 4', bar(4, 12)),
  tpl('boombap-clap-late', 'Late Dusty', 'clap', 'boombap', 'Dusty clap behind 2 & 4', bar(5, 13)),
  tpl('boombap-clap-vinyl-tail', 'Vinyl Tail', 'clap', 'boombap', '2 & 4 + dusty ghost after 4', bar(4, 12, 14)),
  tpl('boombap-clap-single', 'Single Dusty', 'clap', 'boombap', 'Single dusty clap on beat 2', bar(4)),
  tpl('boombap-clap-beat4', 'Beat 4 Dusty', 'clap', 'boombap', 'Single dusty clap on beat 4', bar(12)),
  tpl('boombap-clap-off', 'Off Dusty', 'clap', 'boombap', 'Dusty clap on & of 2 and & of 4', bar(6, 14)),
  tpl('boombap-clap-wide', 'Wide Dusty', 'clap', 'boombap', 'Layered dusty clap width', bar(4, 5, 12, 13)),
  tpl('boombap-clap-push', 'Push Dusty', 'clap', 'boombap', '2 & 4 + dusty ghost before bar line', bar(4, 12, 15)),
  tpl('boombap-clap-pickup', 'Pickup Dusty', 'clap', 'boombap', '2 & 4 + dusty pickup before 4', bar(4, 11, 12)),
  tpl('boombap-clap-mid', 'Mid Dusty', 'clap', 'boombap', '2 & 4 + dusty ghost after 2', bar(4, 7, 12)),
  tpl('boombap-clap-off13', 'Off 1 & 3', 'clap', 'boombap', 'Dusty clap on & of 1 and & of 3', bar(2, 10)),
  tpl('boombap-clap-half', 'Half Dusty', 'clap', 'boombap', 'Single dusty clap on beat 3', bar(8)),
  tpl('boombap-clap-sync', 'Sync Dusty', 'clap', 'boombap', '2 & 4 + syncopated dusty ghost', bar(4, 9, 12)),
  tpl('boombap-clap-double', 'Double Dusty', 'clap', 'boombap', '2 & 4 with dusty double on 4', bar(4, 12, 13)),
  tpl('boombap-clap-tri', 'Triangulated', 'clap', 'boombap', '2 & 4 with dusty mid ghost', bar(4, 10, 12)),
  tpl('boombap-clap-tail', 'Tail Dusty', 'clap', 'boombap', 'Single dusty ghost at bar tail', bar(14)),
  tpl('boombap-clap-early', 'Early Dusty', 'clap', 'boombap', 'Dusty ghost after 1, then 2 & 4', bar(1, 4, 12)),
  tpl('boombap-clap-off-ghost', 'Off Ghost Dusty', 'clap', 'boombap', '2 & 4 + dusty ghost on & of 2', bar(4, 6, 12)),
  tpl('boombap-clap-downbeat', 'Downbeat Dusty', 'clap', 'boombap', 'Rare dusty clap with the kick', bar(0, 8)),
  tpl('boombap-clap-bar-end', 'Bar-End Dusty', 'clap', 'boombap', 'Two dusty ghosts closing the bar', bar(13, 15)),
  tpl('boombap-clap-layer-snare', 'Layer Snare', 'clap', 'boombap', 'Clap layered tight on hard 2 & 4', bar(4, 12)),
  tpl('boombap-clap-room', 'Room Clap', 'clap', 'boombap', 'Wide room clap on 2 & 4', bar(4, 5, 12)),
  tpl('boombap-clap-tape', 'Tape Clap', 'clap', 'boombap', 'Tape-saturated 2 & 4 + ghost', bar(4, 12, 14)),
  tpl('boombap-clap-crack', 'Crack Layer', 'clap', 'boombap', 'Crack clap stack on beat 2', bar(4, 5)),
  tpl('boombap-clap-soft-4', 'Soft 4', 'clap', 'boombap', 'Hard 2 · soft dusty 4', bar(4, 13)),
  tpl('boombap-clap-fill', 'Fill Clap', 'clap', 'boombap', '2 & 4 + dusty fill tail', bar(4, 12, 14, 15)),
  tpl('boombap-clap-swing', 'Swing Clap', 'clap', 'boombap', 'Swung dusty clap pocket', bar(5, 6, 13, 14)),
  tpl('boombap-clap-minimal', 'One Soft', 'clap', 'boombap', 'Single soft clap on 4', bar(12)),
  tpl('boombap-clap-ghost-pair', 'Ghost Pair', 'clap', 'boombap', 'Two dusty ghosts around beat 4', bar(11, 14)),
  tpl('boombap-clap-crate', 'Crate Clap', 'clap', 'boombap', 'Crate-digger clap on 2 & soft 4', bar(4, 12, 15)),

  // ── BOOM BAP HI-HAT (30) ──
  tpl('boombap-hat-8ths', 'Straight 8ths', 'hihat', 'boombap', 'Steady closed eighth-note hats', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('boombap-hat-swing-off', 'Swing Off', 'hihat', 'boombap', 'Hats on every off-eighth — swing lean', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('boombap-hat-dense', 'Dense 16ths', 'hihat', 'boombap', 'Full dense sixteenth-note hats', bar(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)),
  tpl('boombap-hat-swung-skip', 'Swung Skip', 'hihat', 'boombap', 'Classic swung skip hat pattern', bar(0, 3, 4, 7, 8, 11, 12, 15)),
  tpl('boombap-hat-swing-pocket', 'Swing Pocket', 'hihat', 'boombap', 'Swung eighth pocket hats', bar(0, 2, 4, 7, 8, 10, 12, 15)),
  tpl('boombap-hat-offbeat', 'Offbeat Only', 'hihat', 'boombap', 'Hats only on the & of every beat', bar(2, 6, 10, 14)),
  tpl('boombap-hat-quarters', 'Quarter Pulse', 'hihat', 'boombap', 'Simple quarter-note hat pulse', bar(0, 4, 8, 12)),
  tpl('boombap-hat-dense-swing', 'Dense Swing', 'hihat', 'boombap', 'Dense swung hats with extra pushes', bar(0, 2, 4, 6, 8, 9, 10, 12, 14)),
  tpl('boombap-hat-loose', 'Loose Swing', 'hihat', 'boombap', 'Loosely swung hat pattern', bar(0, 3, 6, 8, 11, 14)),
  tpl('boombap-hat-behind', 'Behind Grid', 'hihat', 'boombap', 'Hats sitting behind the grid', bar(1, 4, 7, 9, 12, 15)),
  tpl('boombap-hat-laid', 'Laid Swing', 'hihat', 'boombap', 'Laid-back swing pattern', bar(0, 2, 5, 6, 8, 10, 13, 14)),
  tpl('boombap-hat-off16', 'Off-16th Ticks', 'hihat', 'boombap', 'Sparse hats on last 16th of each beat', bar(3, 7, 11, 15)),
  tpl('boombap-hat-triplet', 'Triplet Feel', 'hihat', 'boombap', 'Approximated triplet-feel hats', bar(0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14)),
  tpl('boombap-hat-minimal-two', 'Minimal Two', 'hihat', 'boombap', 'Two sparse hat hits per bar', bar(2, 10)),
  tpl('boombap-hat-minimal-off', 'Minimal Off', 'hihat', 'boombap', 'Two sparse offbeat hits', bar(6, 14)),
  tpl('boombap-hat-push-roll', 'Push Roll', 'hihat', 'boombap', 'Steady hats with bar-end push roll', bar(0, 2, 4, 6, 7, 8, 10, 12, 14, 15)),
  tpl('boombap-hat-skip-swing', 'Skip Swing', 'hihat', 'boombap', 'Skipping swung hat pattern', bar(0, 2, 3, 6, 8, 10, 11, 14)),
  tpl('boombap-hat-bar-roll', 'Bar-End Roll', 'hihat', 'boombap', 'Dense roll closing out the bar', bar(9, 10, 11, 13, 14, 15)),
  tpl('boombap-hat-loose-groove', 'Loose Groove', 'hihat', 'boombap', 'Loose groove hat pattern', bar(0, 4, 6, 8, 12, 14)),
  tpl('boombap-hat-dusty', 'Dusty Swing', 'hihat', 'boombap', 'Dusty swung hats with texture', bar(1, 3, 4, 7, 9, 11, 12, 15)),
  tpl('boombap-hat-sp-swing', 'SP Swing', 'hihat', 'boombap', 'SP-1200 style swung 8ths', bar(0, 2, 4, 7, 8, 10, 12, 15)),
  tpl('boombap-hat-mpc-swing', 'MPC Swing', 'hihat', 'boombap', 'MPC swing lean hats', bar(0, 3, 4, 6, 8, 11, 12, 14)),
  tpl('boombap-hat-verse', 'Verse Light', 'hihat', 'boombap', 'Light verse hat pulse', bar(0, 4, 8, 12)),
  tpl('boombap-hat-chorus', 'Chorus Push', 'hihat', 'boombap', 'Denser chorus hat push', bar(0, 2, 4, 6, 8, 10, 11, 12, 14, 15)),
  tpl('boombap-hat-ghost-tick', 'Ghost Tick', 'hihat', 'boombap', 'Soft ghost ticks between beats', bar(1, 5, 9, 13)),
  tpl('boombap-hat-skip-snare', 'Skip Snare', 'hihat', 'boombap', 'Skip steps near the snare', bar(0, 2, 6, 8, 10, 14)),
  tpl('boombap-hat-build', 'Second-Half Build', 'hihat', 'boombap', 'Second half denser hats', bar(0, 4, 8, 9, 10, 11, 12, 13, 14, 15)),
  tpl('boombap-hat-crate', 'Crate Tick', 'hihat', 'boombap', 'Irregular crate-digger ticks', bar(1, 4, 7, 10, 13)),
  tpl('boombap-hat-half-swing', 'Half + Swing', 'hihat', 'boombap', 'Half-time pulse with swing accents', bar(0, 4, 7, 8, 12, 15)),
  tpl('boombap-hat-break', 'Break Hats', 'hihat', 'boombap', 'Breakbeat hat chatter', bar(0, 2, 3, 6, 8, 10, 11, 14, 15)),

  // ── BOOM BAP OPEN HAT (30) ──
  tpl('boombap-oh-tail', 'Tail Lift', 'openHat', 'boombap', 'Single open hat at bar tail', bar(14)),
  tpl('boombap-oh-24', 'OH 2 & 4', 'openHat', 'boombap', 'Open on & of 2 and & of 4', bar(6, 14)),
  tpl('boombap-oh-single', 'Single Lift', 'openHat', 'boombap', 'One open on & of 2', bar(6)),
  tpl('boombap-oh-late3', 'Late 3 Lift', 'openHat', 'boombap', 'One open on & of 3', bar(10)),
  tpl('boombap-oh-off13', 'Off 1 & 3', 'openHat', 'boombap', 'Open on & of 1 and & of 3', bar(2, 10)),
  tpl('boombap-oh-pickup', 'Pickup Lift', 'openHat', 'boombap', 'Open at bar-end pickup', bar(15)),
  tpl('boombap-oh-late-duo', 'Late Duo', 'openHat', 'boombap', 'Two late open lifts', bar(7, 15)),
  tpl('boombap-oh-bar-end', 'Bar-End Duo', 'openHat', 'boombap', 'Two opens closing the bar', bar(13, 15)),
  tpl('boombap-oh-early', 'Early Lift', 'openHat', 'boombap', 'One open on & of 1', bar(2)),
  tpl('boombap-oh-double-mid', 'Double Mid', 'openHat', 'boombap', 'Opens on & of 2 and & of 3', bar(6, 10)),
  tpl('boombap-oh-beat', 'Beat Lift', 'openHat', 'boombap', 'Open locked to beats 2 and 4', bar(4, 12)),
  tpl('boombap-oh-off-late', 'Off Late', 'openHat', 'boombap', 'Open right before beat 4', bar(11)),
  tpl('boombap-oh-loose', 'Loose Duo', 'openHat', 'boombap', 'Loosely placed open pair', bar(6, 13)),
  tpl('boombap-oh-full', 'Full Groove', 'openHat', 'boombap', 'Open on every & of the bar', bar(2, 6, 10, 14)),
  tpl('boombap-oh-sync', 'Sync Lift', 'openHat', 'boombap', 'Syncopated open before beat 3', bar(9)),
  tpl('boombap-oh-off-pair', 'Off Pair', 'openHat', 'boombap', 'Open pair slightly behind grid', bar(5, 13)),
  tpl('boombap-oh-close', 'Bar Close', 'openHat', 'boombap', 'Opens closing end of bar', bar(14, 15)),
  tpl('boombap-oh-skip', 'Skip Lift', 'openHat', 'boombap', 'Skipping open lift pattern', bar(3, 11)),
  tpl('boombap-oh-downbeat', 'Downbeat Lift', 'openHat', 'boombap', 'Rare open on downbeats', bar(0, 8)),
  tpl('boombap-oh-half-tail', 'Half + Tail', 'openHat', 'boombap', 'Open on beat 3 plus bar tail', bar(8, 14)),
  tpl('boombap-oh-sizzle-4', 'Sizzle 4', 'openHat', 'boombap', 'Open sizzle around beat 4', bar(12, 14)),
  tpl('boombap-oh-breath', 'Breath Lift', 'openHat', 'boombap', 'Soft breath open on & of 4', bar(14)),
  tpl('boombap-oh-push', 'Push Open', 'openHat', 'boombap', 'Open push into bar line', bar(14, 15)),
  tpl('boombap-oh-verse', 'Verse Breath', 'openHat', 'boombap', 'Sparse verse open lift', bar(6)),
  tpl('boombap-oh-chorus', 'Chorus Lift', 'openHat', 'boombap', 'Chorus open on 2 & 4 offs', bar(6, 14)),
  tpl('boombap-oh-ghost', 'Ghost Open', 'openHat', 'boombap', 'Soft ghost open mid-bar', bar(7)),
  tpl('boombap-oh-swing', 'Swing Open', 'openHat', 'boombap', 'Swung open pair', bar(7, 15)),
  tpl('boombap-oh-crate', 'Crate Open', 'openHat', 'boombap', 'Crate-digger open accents', bar(5, 14)),
  tpl('boombap-oh-room', 'Room Wash', 'openHat', 'boombap', 'Wide room open wash', bar(6, 13, 14)),
  tpl('boombap-oh-minimal', 'One Open', 'openHat', 'boombap', 'Single open per bar', bar(14)),

  // ── BOOM BAP RIM / PERC (30) ──
  tpl('boombap-rim-tail', 'Rim Tail', 'rim', 'boombap', 'Rim at the bar tail', bar(7, 15)),
  tpl('boombap-rim-duo', 'Rim Duo', 'rim', 'boombap', 'Two rims late in each half', bar(3, 11)),
  tpl('boombap-rim-sync', 'Sync Rim', 'rim', 'boombap', 'Syncopated rim pair', bar(1, 9)),
  tpl('boombap-rim-off', 'Off Rim', 'rim', 'boombap', 'Offbeat rim pair late', bar(5, 13)),
  tpl('boombap-rim-13', 'Rim 1 & 3', 'rim', 'boombap', 'Rim on & of 1 and & of 3', bar(2, 10)),
  tpl('boombap-rim-24', 'Rim 2 & 4', 'rim', 'boombap', 'Rim on & of 2 and & of 4', bar(6, 14)),
  tpl('boombap-rim-beat', 'Rim Beat', 'rim', 'boombap', 'Rim locked to beats 2 and 4', bar(4, 12)),
  tpl('boombap-rim-downbeat', 'Rim Downbeat', 'rim', 'boombap', 'Rim with kick downbeats', bar(0, 8)),
  tpl('boombap-rim-ghost', 'Ghost Rim', 'rim', 'boombap', 'Two ghost rims late in bar', bar(9, 13)),
  tpl('boombap-rim-off16', 'Off-16th Rim', 'rim', 'boombap', 'Rim on last 16th of each beat', bar(3, 7, 11, 15)),
  tpl('boombap-rim-off-q', 'Off-Quarter', 'rim', 'boombap', 'Rim ticks between the beats', bar(1, 5, 9, 13)),
  tpl('boombap-rim-steady', 'Steady Rim', 'rim', 'boombap', 'Steady rim on every offbeat', bar(2, 6, 10, 14)),
  tpl('boombap-rim-single', 'Single Rim', 'rim', 'boombap', 'One rim after the downbeat', bar(7)),
  tpl('boombap-rim-late', 'Late Rim', 'rim', 'boombap', 'One rim before beat 4', bar(11)),
  tpl('boombap-rim-flam', 'Flam Rim', 'rim', 'boombap', 'Flam rim around beat 3', bar(2, 3, 10, 11)),
  tpl('boombap-rim-flam-tail', 'Flam Tail', 'rim', 'boombap', 'Flam rim around beat 4', bar(6, 7, 14, 15)),
  tpl('boombap-rim-triplet', 'Triplet Rim', 'rim', 'boombap', 'Triplet-feel rim across bar', bar(0, 3, 6, 9, 12, 15)),
  tpl('boombap-rim-skip', 'Skip Rim', 'rim', 'boombap', 'Skipping rim in front half', bar(1, 3, 9, 11)),
  tpl('boombap-rim-skip-tail', 'Skip Tail', 'rim', 'boombap', 'Skipping rim in back half', bar(5, 7, 13, 15)),
  tpl('boombap-rim-tick', 'Single Tick', 'rim', 'boombap', 'One rim tick at bar tail', bar(14)),
  tpl('boombap-rim-shaker', 'Shaker 8ths', 'rim', 'boombap', 'Soft shaker-feel 8ths', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('boombap-rim-perc-fill', 'Perc Fill', 'rim', 'boombap', 'Perc fill closing the bar', bar(12, 13, 14, 15)),
  tpl('boombap-rim-ghost-dense', 'Dense Ghost', 'rim', 'boombap', 'Dense ghost rim layer', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('boombap-rim-crate', 'Crate Perc', 'rim', 'boombap', 'Irregular crate perc ticks', bar(1, 5, 8, 13)),
  tpl('boombap-rim-side', 'Side Stick', 'rim', 'boombap', 'Side-stick on 2 & 4', bar(4, 12)),
  tpl('boombap-rim-click', 'Click Quarters', 'rim', 'boombap', 'Soft quarter clicks', bar(0, 4, 8, 12)),
  tpl('boombap-rim-swing', 'Swing Perc', 'rim', 'boombap', 'Swung perc ticks', bar(1, 4, 7, 10, 13)),
  tpl('boombap-rim-minimal', 'Two Ticks', 'rim', 'boombap', 'Two sparse rim ticks', bar(6, 14)),
  tpl('boombap-rim-break', 'Break Perc', 'rim', 'boombap', 'Breakbeat perc chatter', bar(1, 3, 6, 9, 11, 14)),
  tpl('boombap-rim-woodblock', 'Woodblock Feel', 'rim', 'boombap', 'Woodblock-feel accents', bar(2, 6, 11, 15)),
];
