/**
 * Beat Pads Lane Placements — Hip Hop pack.
 * 20 each: kick · snare · clap · hihat · openHat · rim (one-lane 16th patterns).
 */
import type {
  BeatPadsDrumRole,
  BeatPadsLanePlacementTemplate,
  BeatPadsPlacementGenre,
} from '@/app/lib/creationStation/beatPadsLanePlacementTemplates';

function bar(...steps: number[]): readonly number[] {
  return steps;
}

function tpl(
  id: string,
  name: string,
  role: BeatPadsDrumRole,
  genre: BeatPadsPlacementGenre,
  desc: string,
  steps: readonly number[],
): BeatPadsLanePlacementTemplate {
  return { id, name, role, genre, desc, steps };
}

/** @internal Merged into ALL_TEMPLATES. */
export const BEAT_PADS_HIPHOP_LANE_TEMPLATES: readonly BeatPadsLanePlacementTemplate[] = [
  // ── HIP HOP KICK (20) ──
  tpl('hiphop-kick-boom-bap', 'Boom Bap Classic', 'kick', 'hiphop', '1 and & of 3 — golden-era pocket', bar(0, 10)),
  tpl('hiphop-kick-pocket-swing', 'Pocket Swing', 'kick', 'hiphop', '1 · & of 2 · & of 3 swing lean', bar(0, 6, 10)),
  tpl('hiphop-kick-simple-13', 'Simple 1 & 3', 'kick', 'hiphop', 'Plain downbeat and beat 3', bar(0, 8)),
  tpl('hiphop-kick-off-lean', 'Off-Kick Lean', 'kick', 'hiphop', '1 · push before 2 · beat 3', bar(0, 3, 8)),
  tpl('hiphop-kick-golden-era', 'Golden Era', 'kick', 'hiphop', '1 · late push · beat 3 pocket', bar(0, 7, 8)),
  tpl('hiphop-kick-push-double', 'Push Double', 'kick', 'hiphop', '1 · & of 3 doubled into beat 3', bar(0, 10, 11)),
  tpl('hiphop-kick-half-swing', 'Half Swing', 'kick', 'hiphop', '1 · & of 2 · beat 3', bar(0, 6, 8)),
  tpl('hiphop-kick-boom-lean', 'Boom Lean', 'kick', 'hiphop', '1 · early push · beat 3', bar(0, 2, 8)),
  tpl('hiphop-kick-behind-grid', 'Behind Grid', 'kick', 'hiphop', '1 · laid-back push into beat 3', bar(0, 9, 10)),
  tpl('hiphop-kick-classic-plus', 'Classic Plus', 'kick', 'hiphop', '1 · beat 3 · late push after 3', bar(0, 8, 11)),
  tpl('hiphop-kick-off2-pocket', 'Off 2 Pocket', 'kick', 'hiphop', '1 · beat 2 · & of 3 pocket', bar(0, 4, 10)),
  tpl('hiphop-kick-minimal-one', 'Minimal One', 'kick', 'hiphop', 'Downbeat only — stripped pocket', bar(0)),
  tpl('hiphop-kick-pickup-tail', 'Pickup Tail', 'kick', 'hiphop', '1 · beat 3 · bar-end pickup', bar(0, 8, 14)),
  tpl('hiphop-kick-boom-pickup', 'Boom + Pickup', 'kick', 'hiphop', '1 · & of 3 · bar-end pickup', bar(0, 10, 14)),
  tpl('hiphop-kick-rolling-pocket', 'Rolling Pocket', 'kick', 'hiphop', '1 · early push · mid roll · & of 3', bar(0, 3, 6, 10)),
  tpl('hiphop-kick-behind-3', 'Behind 3', 'kick', 'hiphop', '1 · late push · & of 3', bar(0, 7, 10)),
  tpl('hiphop-kick-groove-skip', 'Groove Skip', 'kick', 'hiphop', '1 · early push · mid · & of 3', bar(0, 2, 6, 10)),
  tpl('hiphop-kick-late-push', 'Late Push', 'kick', 'hiphop', '1 · & of 3 · late bar push', bar(0, 10, 13)),
  tpl('hiphop-kick-triplet-lean', 'Triplet Lean', 'kick', 'hiphop', '1 · swung mid · & of 3 pair', bar(0, 6, 9, 10)),
  tpl('hiphop-kick-double-pocket', 'Double Pocket', 'kick', 'hiphop', '1 · beat 3 · & of 3 double', bar(0, 8, 10)),

  // ── HIP HOP SNARE (20) ──
  tpl('hiphop-snare-24-classic', 'Classic 2 & 4', 'snare', 'hiphop', 'Standard boom-bap backbeat', bar(4, 12)),
  tpl('hiphop-snare-ghost-tail', 'Ghost Tail', 'snare', 'hiphop', '2 & 4 + soft ghost after 4', bar(4, 12, 14)),
  tpl('hiphop-snare-laid-back', 'Laid-Back 2 & 4', 'snare', 'hiphop', 'Backbeat sitting slightly behind the grid', bar(5, 13)),
  tpl('hiphop-snare-push-ghost', 'Push Ghost', 'snare', 'hiphop', '2 & 4 + ghost right before the bar line', bar(4, 12, 15)),
  tpl('hiphop-snare-pickup-ghost', 'Pickup Ghost', 'snare', 'hiphop', '2 & 4 + ghost pickup before beat 4', bar(4, 11, 12)),
  tpl('hiphop-snare-ghost-mid', 'Ghost Mid', 'snare', 'hiphop', '2 & 4 + ghost right after beat 2', bar(4, 7, 12)),
  tpl('hiphop-snare-half-time', 'Half-Time Snare', 'snare', 'hiphop', 'Single snare on beat 3 only', bar(8)),
  tpl('hiphop-snare-off-ghost', 'Off Ghost', 'snare', 'hiphop', '2 & 4 + ghost on & of 2', bar(4, 6, 12)),
  tpl('hiphop-snare-sync-ghost', 'Syncopated Ghost', 'snare', 'hiphop', '2 & 4 + syncopated ghost before beat 3', bar(4, 9, 12)),
  tpl('hiphop-snare-double-tap', 'Double Tap', 'snare', 'hiphop', '2 & 4 with a doubled hit on 4', bar(4, 12, 13)),
  tpl('hiphop-snare-pickup-lead', 'Pickup Lead', 'snare', 'hiphop', 'Ghost pickup before beat 2, then 2 & 4', bar(3, 4, 12)),
  tpl('hiphop-snare-triangulated', 'Triangulated', 'snare', 'hiphop', '2 & 4 with a mid-bar ghost between them', bar(4, 10, 12)),
  tpl('hiphop-snare-early-ghost', 'Early Ghost', 'snare', 'hiphop', 'Ghost right after the downbeat, then 2 & 4', bar(1, 4, 12)),
  tpl('hiphop-snare-bar-fill', 'Bar Fill', 'snare', 'hiphop', '2 & 4 plus a short bar-end fill', bar(4, 12, 14, 15)),
  tpl('hiphop-snare-offbeat', 'Offbeat Snare', 'snare', 'hiphop', 'Snare shifted to & of 2 and & of 4', bar(6, 14)),
  tpl('hiphop-snare-beat2-only', 'Beat 2 Only', 'snare', 'hiphop', 'Single snare accent on beat 2', bar(4)),
  tpl('hiphop-snare-beat4-only', 'Beat 4 Only', 'snare', 'hiphop', 'Single snare accent on beat 4', bar(12)),
  tpl('hiphop-snare-wide-stack', 'Wide Stack', 'snare', 'hiphop', 'Layered snare width on the backbeat', bar(4, 5, 12, 13)),
  tpl('hiphop-snare-triplet-ghost', 'Triplet Ghost', 'snare', 'hiphop', '2 & 4 with a triplet-feel ghost pair before beat 3', bar(4, 9, 10, 12)),
  tpl('hiphop-snare-off13-ghost', 'Off 1 & 3 Ghost', 'snare', 'hiphop', 'Unusual ghost variant on & of 1 and & of 3', bar(2, 10)),

  // ── HIP HOP CLAP (20) ──
  tpl('hiphop-clap-dusty-24', 'Dusty Clap', 'clap', 'hiphop', 'Dusty vinyl clap on 2 & 4', bar(4, 12)),
  tpl('hiphop-clap-late-dusty', 'Late Dusty', 'clap', 'hiphop', 'Dusty clap sitting behind 2 & 4', bar(5, 13)),
  tpl('hiphop-clap-vinyl-tail', 'Vinyl Tail', 'clap', 'hiphop', '2 & 4 + soft dusty ghost after 4', bar(4, 12, 14)),
  tpl('hiphop-clap-single-dusty', 'Single Dusty', 'clap', 'hiphop', 'Single dusty clap on beat 2', bar(4)),
  tpl('hiphop-clap-beat4-dusty', 'Beat 4 Dusty', 'clap', 'hiphop', 'Single dusty clap on beat 4', bar(12)),
  tpl('hiphop-clap-off-dusty', 'Off Dusty', 'clap', 'hiphop', 'Dusty clap shifted to & of 2 and & of 4', bar(6, 14)),
  tpl('hiphop-clap-wide-dusty', 'Wide Dusty', 'clap', 'hiphop', 'Layered dusty clap width on the backbeat', bar(4, 5, 12, 13)),
  tpl('hiphop-clap-push-dusty', 'Push Dusty', 'clap', 'hiphop', '2 & 4 + dusty ghost before the bar line', bar(4, 12, 15)),
  tpl('hiphop-clap-pickup-dusty', 'Pickup Dusty', 'clap', 'hiphop', '2 & 4 + dusty pickup ghost before beat 4', bar(4, 11, 12)),
  tpl('hiphop-clap-mid-dusty', 'Mid Dusty', 'clap', 'hiphop', '2 & 4 + dusty ghost right after beat 2', bar(4, 7, 12)),
  tpl('hiphop-clap-off13-dusty', 'Off 1 & 3 Dusty', 'clap', 'hiphop', 'Dusty clap on the & of 1 and & of 3', bar(2, 10)),
  tpl('hiphop-clap-half-dusty', 'Half Dusty', 'clap', 'hiphop', 'Single dusty clap on beat 3', bar(8)),
  tpl('hiphop-clap-sync-dusty', 'Sync Dusty', 'clap', 'hiphop', '2 & 4 + dusty syncopated ghost before beat 3', bar(4, 9, 12)),
  tpl('hiphop-clap-double-dusty', 'Double Dusty', 'clap', 'hiphop', '2 & 4 with a dusty doubled hit on 4', bar(4, 12, 13)),
  tpl('hiphop-clap-triangulated-dusty', 'Triangulated Dusty', 'clap', 'hiphop', '2 & 4 with a dusty mid-bar ghost between them', bar(4, 10, 12)),
  tpl('hiphop-clap-tail-dusty', 'Tail Dusty', 'clap', 'hiphop', 'Single dusty ghost clap right at the bar tail', bar(14)),
  tpl('hiphop-clap-early-dusty', 'Early Dusty', 'clap', 'hiphop', 'Dusty ghost right after the downbeat, then 2 & 4', bar(1, 4, 12)),
  tpl('hiphop-clap-off-ghost-dusty', 'Off Ghost Dusty', 'clap', 'hiphop', '2 & 4 + dusty ghost on & of 2', bar(4, 6, 12)),
  tpl('hiphop-clap-downbeat-dusty', 'Downbeat Dusty', 'clap', 'hiphop', 'Rare dusty clap variant locked to the kick', bar(0, 8)),
  tpl('hiphop-clap-bar-end-dusty', 'Bar-End Dusty', 'clap', 'hiphop', 'Two dusty ghost claps closing out the bar', bar(13, 15)),

  // ── HIP HOP HI-HAT (20) ──
  tpl('hiphop-hat-straight-8ths', 'Straight 8ths', 'hihat', 'hiphop', 'Steady closed eighth-note hats', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('hiphop-hat-swing-lean', 'Swing Lean', 'hihat', 'hiphop', 'Hats on every off-eighth — swing lean', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('hiphop-hat-dense-boom', 'Dense Boom', 'hihat', 'hiphop', 'Full dense sixteenth-note hat pattern', bar(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)),
  tpl('hiphop-hat-swung-skip', 'Swung Skip', 'hihat', 'hiphop', 'Classic swung skip hat pattern', bar(0, 3, 4, 7, 8, 11, 12, 15)),
  tpl('hiphop-hat-swing-pocket', 'Swing Pocket', 'hihat', 'hiphop', 'Swung eighth pocket hats', bar(0, 2, 4, 7, 8, 10, 12, 15)),
  tpl('hiphop-hat-offbeat-only', 'Offbeat Only', 'hihat', 'hiphop', 'Hats only on the & of every beat', bar(2, 6, 10, 14)),
  tpl('hiphop-hat-quarter-pulse', 'Quarter Pulse', 'hihat', 'hiphop', 'Simple quarter-note hat pulse', bar(0, 4, 8, 12)),
  tpl('hiphop-hat-dense-swing', 'Dense Swing', 'hihat', 'hiphop', 'Dense swung hat pattern with extra pushes', bar(0, 2, 4, 6, 8, 9, 10, 12, 14)),
  tpl('hiphop-hat-loose-swing', 'Loose Swing', 'hihat', 'hiphop', 'Loosely swung hat pattern', bar(0, 3, 6, 8, 11, 14)),
  tpl('hiphop-hat-behind-grid', 'Behind-Grid Swing', 'hihat', 'hiphop', 'Hats sitting behind the grid throughout', bar(1, 4, 7, 9, 12, 15)),
  tpl('hiphop-hat-laid-swing', 'Laid Swing', 'hihat', 'hiphop', 'Laid-back swing pattern', bar(0, 2, 5, 6, 8, 10, 13, 14)),
  tpl('hiphop-hat-off16-ticks', 'Off-16th Ticks', 'hihat', 'hiphop', 'Sparse hats on the final sixteenth of each beat', bar(3, 7, 11, 15)),
  tpl('hiphop-hat-triplet-feel', 'Triplet Feel', 'hihat', 'hiphop', 'Approximated triplet-feel hat pattern', bar(0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14)),
  tpl('hiphop-hat-minimal-two', 'Minimal Two', 'hihat', 'hiphop', 'Two sparse hat hits per bar', bar(2, 10)),
  tpl('hiphop-hat-minimal-off', 'Minimal Off', 'hihat', 'hiphop', 'Two sparse offbeat hits', bar(6, 14)),
  tpl('hiphop-hat-push-roll', 'Push Roll', 'hihat', 'hiphop', 'Steady hats with a bar-end push roll', bar(0, 2, 4, 6, 7, 8, 10, 12, 14, 15)),
  tpl('hiphop-hat-skip-swing', 'Skip Swing', 'hihat', 'hiphop', 'Skipping swung hat pattern', bar(0, 2, 3, 6, 8, 10, 11, 14)),
  tpl('hiphop-hat-bar-end-roll', 'Bar-End Roll', 'hihat', 'hiphop', 'Dense roll closing out the bar', bar(9, 10, 11, 13, 14, 15)),
  tpl('hiphop-hat-loose-groove', 'Loose Groove', 'hihat', 'hiphop', 'Loose groove hat pattern', bar(0, 4, 6, 8, 12, 14)),
  tpl('hiphop-hat-dusty-swing', 'Dusty Swing', 'hihat', 'hiphop', 'Dusty swung hat pattern with extra texture', bar(1, 3, 4, 7, 9, 11, 12, 15)),

  // ── HIP HOP OPEN HAT (20) ──
  tpl('hiphop-oh-tail-lift', 'Tail Lift', 'openHat', 'hiphop', 'Single open hat lift at the bar tail', bar(14)),
  tpl('hiphop-oh-24-lift', 'OH 2 & 4 Lift', 'openHat', 'hiphop', 'Open hat lift on & of 2 and & of 4', bar(6, 14)),
  tpl('hiphop-oh-single-lift', 'Single Lift', 'openHat', 'hiphop', 'One open hat lift on & of 2', bar(6)),
  tpl('hiphop-oh-late3-lift', 'Late 3 Lift', 'openHat', 'hiphop', 'One open hat lift on & of 3', bar(10)),
  tpl('hiphop-oh-off13', 'Off 1 & 3', 'openHat', 'hiphop', 'Open hat lift on & of 1 and & of 3', bar(2, 10)),
  tpl('hiphop-oh-pickup-lift', 'Pickup Lift', 'openHat', 'hiphop', 'Single open lift right at the bar-end pickup', bar(15)),
  tpl('hiphop-oh-late-duo', 'Late Duo', 'openHat', 'hiphop', 'Two late open hat lifts per bar', bar(7, 15)),
  tpl('hiphop-oh-bar-end-duo', 'Bar-End Duo', 'openHat', 'hiphop', 'Two open lifts closing out the bar', bar(13, 15)),
  tpl('hiphop-oh-early-lift', 'Early Lift', 'openHat', 'hiphop', 'One open hat lift on & of 1', bar(2)),
  tpl('hiphop-oh-double-mid', 'Double Mid', 'openHat', 'hiphop', 'Open lifts on & of 2 and & of 3', bar(6, 10)),
  tpl('hiphop-oh-beat-lift', 'Beat Lift', 'openHat', 'hiphop', 'Open hat lift locked to beats 2 and 4', bar(4, 12)),
  tpl('hiphop-oh-off-late', 'Off Late', 'openHat', 'hiphop', 'Single open lift right before beat 4', bar(11)),
  tpl('hiphop-oh-loose-duo', 'Loose Duo', 'openHat', 'hiphop', 'Loosely placed open hat pair', bar(6, 13)),
  tpl('hiphop-oh-full-groove', 'Full Groove', 'openHat', 'hiphop', 'Open hat lift on every & of the bar', bar(2, 6, 10, 14)),
  tpl('hiphop-oh-sync-lift', 'Sync Lift', 'openHat', 'hiphop', 'Single syncopated open lift before beat 3', bar(9)),
  tpl('hiphop-oh-off-pair', 'Off Pair', 'openHat', 'hiphop', 'Open hat pair sitting slightly behind the grid', bar(5, 13)),
  tpl('hiphop-oh-bar-close', 'Bar Close', 'openHat', 'hiphop', 'Open hats closing the very end of the bar', bar(14, 15)),
  tpl('hiphop-oh-skip-lift', 'Skip Lift', 'openHat', 'hiphop', 'Skipping open hat lift pattern', bar(3, 11)),
  tpl('hiphop-oh-downbeat-lift', 'Downbeat Lift', 'openHat', 'hiphop', 'Rare open hat lift on the downbeats', bar(0, 8)),
  tpl('hiphop-oh-half-tail', 'Half + Tail', 'openHat', 'hiphop', 'Open lift on beat 3 plus a bar-tail lift', bar(8, 14)),

  // ── HIP HOP RIM / PERC (20) ──
  tpl('hiphop-rim-tail', 'Rim Tail', 'rim', 'hiphop', 'Rim shot at the bar tail', bar(7, 15)),
  tpl('hiphop-rim-duo', 'Rim Duo', 'rim', 'hiphop', 'Two rim hits sitting late in each half', bar(3, 11)),
  tpl('hiphop-rim-sync', 'Sync Rim', 'rim', 'hiphop', 'Syncopated rim shot pair', bar(1, 9)),
  tpl('hiphop-rim-off-pair', 'Off Rim', 'rim', 'hiphop', 'Offbeat rim pair sitting late', bar(5, 13)),
  tpl('hiphop-rim-13', 'Rim 1 & 3', 'rim', 'hiphop', 'Rim shots on the & of 1 and & of 3', bar(2, 10)),
  tpl('hiphop-rim-24', 'Rim 2 & 4', 'rim', 'hiphop', 'Rim shots on the & of 2 and & of 4', bar(6, 14)),
  tpl('hiphop-rim-beat', 'Rim Beat', 'rim', 'hiphop', 'Rim shots locked to beats 2 and 4', bar(4, 12)),
  tpl('hiphop-rim-downbeat', 'Rim Downbeat', 'rim', 'hiphop', 'Rim shots locked to the kick downbeats', bar(0, 8)),
  tpl('hiphop-rim-ghost', 'Ghost Rim', 'rim', 'hiphop', 'Two syncopated ghost rim hits late in the bar', bar(9, 13)),
  tpl('hiphop-rim-off16', 'Off-16th Rim', 'rim', 'hiphop', 'Rim texture on the final sixteenth of each beat', bar(3, 7, 11, 15)),
  tpl('hiphop-rim-off-quarter', 'Off-Quarter Rim', 'rim', 'hiphop', 'Rim ticks between the beats', bar(1, 5, 9, 13)),
  tpl('hiphop-rim-steady', 'Steady Rim', 'rim', 'hiphop', 'Steady rim texture on every offbeat', bar(2, 6, 10, 14)),
  tpl('hiphop-rim-single', 'Single Rim', 'rim', 'hiphop', 'One rim shot right after the downbeat', bar(7)),
  tpl('hiphop-rim-late', 'Late Rim', 'rim', 'hiphop', 'One rim shot right before beat 4', bar(11)),
  tpl('hiphop-rim-flam', 'Flam Rim', 'rim', 'hiphop', 'Flammed rim texture around beat 3', bar(2, 3, 10, 11)),
  tpl('hiphop-rim-flam-tail', 'Flam Tail Rim', 'rim', 'hiphop', 'Flammed rim texture around beat 4', bar(6, 7, 14, 15)),
  tpl('hiphop-rim-triplet', 'Triplet Rim', 'rim', 'hiphop', 'Triplet-feel rim texture across the bar', bar(0, 3, 6, 9, 12, 15)),
  tpl('hiphop-rim-skip', 'Skip Rim', 'rim', 'hiphop', 'Skipping rim pattern in the front half', bar(1, 3, 9, 11)),
  tpl('hiphop-rim-skip-tail', 'Skip Tail Rim', 'rim', 'hiphop', 'Skipping rim pattern in the back half', bar(5, 7, 13, 15)),
  tpl('hiphop-rim-single-tick', 'Single Tick', 'rim', 'hiphop', 'One rim tick at the bar tail', bar(14)),
];
