/**
 * SE2 Beat Pads Pattern Bank — extra Trap / R&B / Up Tempo drum grids.
 * Rows: 0=Kick  1=Snare  2=Clap  3=Hi-Hat  4=Open Hat  5=TomHi  6=TomLo  7=Rim
 */
import type { PatternPreset } from '@/app/lib/patternPresets';
import {
  trap808Down,
  trap808FollowKick,
  trap808OneThree,
  trapHatsEightThenRoll,
  trapHatsRollEnd,
  trapHatsSteadyThenRoll,
  trapHatsTripletFill,
  trapHatsTwoStep,
  trapKickBarRush,
  trapKickLean,
  trapKickMetro,
  trapKickSlide,
  trapKickSouth,
  trapKickSparse,
  trapKickSyncopated,
  trapOh24,
  trapOhGroove,
  trapRimOff,
  trapSnare24,
  trapSnareBarPush,
} from '@/app/lib/creationStation/beatLabTrapPatternGrid';

const S = 16;

function grid(hits: ReadonlyArray<[number, number]>): boolean[][] {
  const g: boolean[][] = Array.from({ length: 8 }, () => new Array<boolean>(S).fill(false));
  for (const [row, step] of hits) {
    if (row >= 0 && row < 8 && step >= 0 && step < S) g[row]![step] = true;
  }
  return g;
}

function hats8(): ReadonlyArray<[number, number]> {
  return [0, 2, 4, 6, 8, 10, 12, 14].map((s) => [3, s] as [number, number]);
}

function miamiSnare(): ReadonlyArray<[number, number]> {
  return [
    [1, 4],
    [1, 12],
  ];
}

function miamiHatsLite(): ReadonlyArray<[number, number]> {
  return [0, 2, 8, 10].map((s) => [3, s] as [number, number]);
}

function miamiHats8(): ReadonlyArray<[number, number]> {
  return [0, 2, 6, 8, 10, 14].map((s) => [3, s] as [number, number]);
}

/** Trap + R&B + Up Tempo extras — Beat Pads SE2 Pattern Bank. */
export const BEAT_LAB_SE2_BEAT_PADS_BANK_PACK: readonly PatternPreset[] = [
  // ── Trap ──────────────────────────────────────────────────────────────────
  {
    id: 'trap-33',
    name: 'Trap Solid Trunk',
    genre: 'Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Clean 1·3·&4 kick, snap 2 & 4, two-step hats → roll',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-34',
    name: 'Trap Double Tap',
    genre: 'Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Open doubles into 3, snap 2 & 4, steady→roll hats',
    pattern: grid([
      [0, 0],
      [0, 2],
      [0, 8],
      [0, 10],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      [4, 14],
      ...trap808FollowKick([
        [0, 0],
        [0, 2],
        [0, 8],
        [0, 10],
      ]),
    ]),
  },
  {
    id: 'trap-35',
    name: 'Trap Offbeat Bounce',
    genre: 'Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Sync kicks around snares, two-step hats, OH groove',
    pattern: grid([
      [0, 0],
      [0, 5],
      [0, 8],
      [0, 13],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapOhGroove(),
      ...trap808FollowKick([
        [0, 0],
        [0, 5],
        [0, 8],
        [0, 13],
      ]),
    ]),
  },
  {
    id: 'trap-36',
    name: 'Trap Heavy Drop',
    genre: 'Trap',
    role: 'drums',
    bpm: 138,
    desc: 'Aggressive late-3 kick stack, snap 2 & 4, 8ths→roll',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 10],
      [0, 11],
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-37',
    name: 'Trap Rolling Tail',
    genre: 'Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Bar-end kick rush, snap 2 & 4, hat finisher',
    pattern: grid([
      [0, 0],
      [0, 8],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      [4, 14],
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-38',
    name: 'Trap Minimalist',
    genre: 'Trap',
    role: 'drums',
    bpm: 136,
    desc: 'Wide space — 1 · &3 kick, snap 2 & 4, light hats',
    pattern: grid([
      [0, 0],
      [0, 10],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      [4, 14],
      ...trap808FollowKick([
        [0, 0],
        [0, 10],
      ]),
    ]),
  },
  {
    id: 'trap-39',
    name: 'Trap Sync Middle',
    genre: 'Trap',
    role: 'drums',
    bpm: 141,
    desc: 'Mid-bar kick pocket, snap 2 & 4, two-step + rim',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 9],
      [0, 10],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapRimOff(),
      ...trap808FollowKick([
        [0, 0],
        [0, 6],
        [0, 9],
        [0, 10],
      ]),
    ]),
  },
  {
    id: 'trap-40',
    name: 'Trap Continuous Drive',
    genre: 'Trap',
    role: 'drums',
    bpm: 148,
    desc: 'Busy high-energy kick, snap 2 & 4, steady→roll',
    pattern: grid([
      [0, 0],
      [0, 2],
      [0, 6],
      [0, 8],
      [0, 10],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-41',
    name: 'Trap Ghost Lead',
    genre: 'Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Pickup into beat 3, snap 2 & 4, 8ths→roll',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 8],
      [0, 10],
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      [4, 14],
      ...trap808FollowKick([
        [0, 0],
        [0, 7],
        [0, 8],
        [0, 10],
      ]),
    ]),
  },
  {
    id: 'trap-42',
    name: 'Trap Delayed',
    genre: 'Trap',
    role: 'drums',
    bpm: 139,
    desc: 'Skips classic 3 — halting pocket, snap 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 9],
      [0, 11],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
      ...trap808FollowKick([
        [0, 0],
        [0, 9],
        [0, 11],
        [0, 14],
      ]),
    ]),
  },
  {
    id: 'trap-43',
    name: 'Trap Machine Gun',
    genre: 'Trap',
    role: 'drums',
    bpm: 150,
    desc: 'Kick clusters on 1 and 3, snap 2 & 4, hat burst',
    pattern: grid([
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 8],
      [0, 9],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      [4, 14],
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-44',
    name: 'Trap Anticipation',
    genre: 'Trap',
    role: 'drums',
    bpm: 143,
    desc: 'Shifted kicks off the grid, snap 2 & 4, OH swing',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 11],
      [0, 13],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapOhGroove(),
      ...trap808FollowKick([
        [0, 0],
        [0, 7],
        [0, 11],
        [0, 13],
      ]),
    ]),
  },
  {
    id: 'trap-45',
    name: 'Trap Counter Punch',
    genre: 'Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Kick stacks with snare on 4, two-step hats, rim accent',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 5],
      [0, 10],
      [0, 12],
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      [7, 6],
      [7, 14],
      ...trap808FollowKick([
        [0, 0],
        [0, 3],
        [0, 5],
        [0, 10],
        [0, 12],
      ]),
    ]),
  },
  {
    id: 'trap-46',
    name: 'Trap Peak Energy',
    genre: 'Trap',
    role: 'drums',
    bpm: 152,
    desc: 'Relentless kick grid, snap 2 & 4 + bar push, rolling hats',
    pattern: grid([
      [0, 0],
      [0, 2],
      [0, 5],
      [0, 8],
      [0, 11],
      [0, 13],
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-47',
    name: 'Trap Poly Bounce',
    genre: 'Trap',
    role: 'drums',
    bpm: 138,
    desc: 'Four-feel kick trunk with trap hats and snap 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 12],
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
      ...trap808FollowKick([
        [0, 0],
        [0, 4],
        [0, 8],
        [0, 12],
      ]),
    ]),
  },
  {
    id: 'trap-48',
    name: 'Trap Metro Pocket',
    genre: 'Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Metro bounce kick, snap 2 & 4 + bar push, steady→roll',
    pattern: grid([
      ...trapKickMetro(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickMetro()),
    ]),
  },
  {
    id: 'trap-49',
    name: 'Trap South Bounce',
    genre: 'Trap',
    role: 'drums',
    bpm: 138,
    desc: 'Southern behind-the-grid kicks, two-step hats, OH groove',
    pattern: grid([
      ...trapKickSouth(),
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOhGroove(),
      ...trap808FollowKick(trapKickSouth()),
    ]),
  },
  {
    id: 'trap-50',
    name: 'Trap Lean Late',
    genre: 'Trap',
    role: 'drums',
    bpm: 136,
    desc: 'Late lean pocket, sparse snap, light hats + OH breath',
    pattern: grid([
      ...trapKickLean(),
      ...trapSnare24(),
      ...trapHatsTwoStep(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickLean()),
    ]),
  },
  {
    id: 'trap-51',
    name: 'Trap Slide Roll',
    genre: 'Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Bar-end kick slide into next downbeat, 8ths→roll hats',
    pattern: grid([
      ...trapKickSlide(),
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-52',
    name: 'Trap Sparse Trunk',
    genre: 'Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Wide sparse kick, snap 2 & 4, classic 8ths→roll + 808 1·3',
    pattern: grid([
      ...trapKickSparse(),
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOhGroove(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-53',
    name: 'Trap Sync Pocket',
    genre: 'Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Syncopated kick grid, triplet hat fill, rim ghosts',
    pattern: grid([
      ...trapKickSyncopated(),
      ...trapSnare24(),
      ...trapHatsTripletFill(),
      ...trapRimOff(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickSyncopated()),
    ]),
  },
  {
    id: 'trap-54',
    name: 'Trap Downbeat 808',
    genre: 'Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Kick on 1·3, 808 on all downbeats, steady→roll hats',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
      ...trap808Down(),
    ]),
  },
  {
    id: 'trap-55',
    name: 'Trap Clap Stack',
    genre: 'Trap',
    role: 'drums',
    bpm: 148,
    desc: 'Snare+clap stack 2 & 4, metro kick, two-step→roll',
    pattern: grid([
      ...trapKickMetro(),
      ...trapSnare24(),
      [2, 4],
      [2, 12],
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickMetro()),
    ]),
  },
  {
    id: 'trap-56',
    name: 'Trap Ghost Rim',
    genre: 'Trap',
    role: 'drums',
    bpm: 139,
    desc: 'Lean kick, snap 2 & 4, rim offbeats, airy two-step hats',
    pattern: grid([
      ...trapKickLean(),
      ...trapSnare24(),
      ...trapRimOff(),
      ...trapHatsTwoStep(),
      [4, 14],
      ...trap808FollowKick(trapKickLean()),
    ]),
  },
  {
    id: 'trap-57',
    name: 'Trap Rush Finish',
    genre: 'Trap',
    role: 'drums',
    bpm: 150,
    desc: 'Sparse open + bar-end kick rush, rolling hats into 1',
    pattern: grid([
      [0, 0],
      [0, 8],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      ...trapOhGroove(),
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-58',
    name: 'Trap Night Drill',
    genre: 'Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Drill stomp kick, snap 2 & 4, 8ths → roll, open &s',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 8],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
      ...trap808FollowKick([
        [0, 0],
        [0, 7],
        [0, 8],
        [0, 14],
      ]),
    ]),
  },
  {
    id: 'trap-59',
    name: 'Trap Plugg Soft',
    genre: 'Trap',
    role: 'drums',
    bpm: 136,
    desc: 'Soft plugg pocket — sparse kick, late snare ghosts, airy hats',
    pattern: grid([
      [0, 0],
      [0, 9],
      [0, 14],
      [1, 4],
      [1, 12],
      [1, 14],
      ...hats8(),
      [4, 14],
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-60',
    name: 'Trap Rage Chop',
    genre: 'Trap',
    role: 'drums',
    bpm: 148,
    desc: 'Rage doubles into 3, snare stack, busy two-step hats',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 8],
      [0, 10],
      [0, 11],
      ...trapSnare24(),
      [2, 4],
      [2, 12],
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOhGroove(),
      ...trap808FollowKick(trapKickSyncopated()),
    ]),
  },
  {
    id: 'trap-61',
    name: 'Trap Phonk Pulse',
    genre: 'Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Phonk four-lite kick, snare 2 & 4, rim ticks, steady hats',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 12],
      [0, 14],
      ...trapSnare24(),
      ...trapRimOff(),
      ...hats8(),
      [4, 6],
      ...trap808Down(),
    ]),
  },
  {
    id: 'trap-62',
    name: 'Trap Jersey Bounce',
    genre: 'Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Jersey kick chatter, snare lock, skitter 8ths into roll',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 6],
      [0, 8],
      [0, 11],
      [0, 14],
      ...trapSnare24(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickSouth()),
    ]),
  },
  {
    id: 'trap-63',
    name: 'Trap Velvet Half',
    genre: 'Trap',
    role: 'drums',
    bpm: 74,
    desc: 'Half-time velvet — kick 1·3, snare on 3, soft 8ths',
    pattern: grid([
      [0, 0],
      [0, 8],
      [1, 8],
      ...hats8(),
      [4, 14],
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-64',
    name: 'Trap Sync Clap',
    genre: 'Trap',
    role: 'drums',
    bpm: 141,
    desc: 'Sync kick pocket, snare+clap stack, triplet hat fill',
    pattern: grid([
      ...trapKickSyncopated(),
      ...trapSnare24(),
      [2, 4],
      [2, 12],
      ...trapHatsTripletFill(),
      ...trapOh24(),
      ...trap808FollowKick(trapKickSyncopated()),
    ]),
  },
  {
    id: 'trap-65',
    name: 'Trap Dark Wave',
    genre: 'Trap',
    role: 'drums',
    bpm: 138,
    desc: 'Sparse darkwave kick, late snare, minimal hats',
    pattern: grid([
      [0, 0],
      [0, 11],
      [1, 4],
      [1, 12],
      [3, 2],
      [3, 10],
      [4, 14],
      ...trap808OneThree(),
    ]),
  },
  {
    id: 'trap-66',
    name: 'Trap Slide Trunk',
    genre: 'Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Slide-in kick phrase, snap 2 & 4, steady→roll hats',
    pattern: grid([
      ...trapKickSlide(),
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      ...trapOhGroove(),
      ...trap808FollowKick(trapKickSlide()),
    ]),
  },
  {
    id: 'trap-67',
    name: 'Trap Club Metro',
    genre: 'Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Metro bounce kick, snare push, two-step + OH groove',
    pattern: grid([
      ...trapKickMetro(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsTwoStep(),
      ...trapOhGroove(),
      ...trap808FollowKick(trapKickMetro()),
    ]),
  },

  // ── R&B ───────────────────────────────────────────────────────────────────
  {
    id: 'rnb-31',
    name: 'R&B Quiet Storm',
    genre: 'R&B',
    role: 'drums',
    bpm: 86,
    desc: 'Soft storm pocket — sparse kick, snare 2 & 4, silk 8ths',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 10],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 14],
    ]),
  },
  {
    id: 'rnb-32',
    name: 'R&B New Jack',
    genre: 'R&B',
    role: 'drums',
    bpm: 100,
    desc: '90s new-jack lean — sync kick, snare 2 & 4, clap layer',
    pattern: grid([
      [0, 0],
      [0, 5],
      [0, 8],
      [0, 13],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      ...hats8(),
      [4, 6],
    ]),
  },
  {
    id: 'rnb-33',
    name: 'R&B Bedroom',
    genre: 'R&B',
    role: 'drums',
    bpm: 78,
    desc: 'Sparse bedroom pocket — kick 1 · late 3, snare 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 9],
      [1, 4],
      [1, 12],
      [3, 2],
      [3, 6],
      [3, 10],
      [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-34',
    name: 'R&B Silk Trunk',
    genre: 'R&B',
    role: 'drums',
    bpm: 90,
    desc: 'Silk trunk — kick 1 · late 3, rim ghosts, open lift',
    pattern: grid([
      [0, 0],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 10],
      [7, 3],
      [7, 11],
    ]),
  },
  {
    id: 'rnb-35',
    name: 'R&B Trap Soul',
    genre: 'R&B',
    role: 'drums',
    bpm: 94,
    desc: 'Trap-soul hybrid — 1·3·&4 kick feel, snare 2 & 4, rolling hats',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 10],
      [0, 14],
      [1, 4],
      [1, 12],
      [3, 0],
      [3, 2],
      [3, 4],
      [3, 6],
      [3, 8],
      [3, 9],
      [3, 10],
      [3, 11],
      [3, 12],
      [3, 13],
      [3, 14],
      [3, 15],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-36',
    name: 'R&B Church Push',
    genre: 'R&B',
    role: 'drums',
    bpm: 92,
    desc: 'Gospel-tinged push — kick 1·2·3, snare 2 & 4, open air',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 6],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-37',
    name: 'R&B Late Bounce',
    genre: 'R&B',
    role: 'drums',
    bpm: 88,
    desc: 'Late bounce pocket — kick behind the grid, snare 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 12],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [7, 6],
      [7, 14],
    ]),
  },
  {
    id: 'rnb-38',
    name: 'R&B Double 3',
    genre: 'R&B',
    role: 'drums',
    bpm: 91,
    desc: 'Doubles around beat 3, snare 2 & 4, soft hats',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 9],
      [0, 11],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 14],
    ]),
  },
  {
    id: 'rnb-39',
    name: 'R&B Verse Air',
    genre: 'R&B',
    role: 'drums',
    bpm: 84,
    desc: 'Airy verse — kick 1·3, snare 2 & 4, sparse hats',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 15],
      [1, 4],
      [1, 12],
      [3, 2],
      [3, 6],
      [3, 10],
      [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-40',
    name: 'R&B Chorus Lift',
    genre: 'R&B',
    role: 'drums',
    bpm: 96,
    desc: 'Chorus energy — denser kick, snare+clap 2 & 4, rolling hats',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      [3, 0],
      [3, 2],
      [3, 4],
      [3, 6],
      [3, 8],
      [3, 10],
      [3, 12],
      [3, 13],
      [3, 14],
      [3, 15],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-41',
    name: 'R&B Midnight Cruise',
    genre: 'R&B',
    role: 'drums',
    bpm: 82,
    desc: 'Late-night cruise — kick 1·&3·4, snare 2 & 4, soft 8ths',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 8],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 14],
    ]),
  },
  {
    id: 'rnb-42',
    name: 'R&B Honey Drip',
    genre: 'R&B',
    role: 'drums',
    bpm: 88,
    desc: 'Sticky pocket — sync kick, snare 2 & 4, open-hat breath',
    pattern: grid([
      [0, 0],
      [0, 5],
      [0, 10],
      [0, 13],
      [1, 4],
      [1, 12],
      [3, 0],
      [3, 4],
      [3, 8],
      [3, 12],
      [4, 6],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-43',
    name: 'R&B Gold Link',
    genre: 'R&B',
    role: 'drums',
    bpm: 93,
    desc: 'Modern gold-link bounce — kick doubles, clap on 3, rolling hats',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 8],
      [0, 11],
      [1, 4],
      [1, 12],
      [2, 8],
      [3, 0],
      [3, 2],
      [3, 4],
      [3, 6],
      [3, 8],
      [3, 10],
      [3, 12],
      [3, 13],
      [3, 14],
      [3, 15],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-44',
    name: 'R&B Slow Motion',
    genre: 'R&B',
    role: 'drums',
    bpm: 72,
    desc: 'Half-time crawl — kick on 1, snare on 3, sparse hats',
    pattern: grid([
      [0, 0],
      [0, 10],
      [1, 8],
      [3, 4],
      [3, 12],
      [4, 14],
      [7, 6],
    ]),
  },
  {
    id: 'rnb-45',
    name: 'R&B Velvet Kick',
    genre: 'R&B',
    role: 'drums',
    bpm: 90,
    desc: 'Velvet four-feel kick, snare 2 & 4, silk 8ths + rim',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 12],
      [1, 4],
      [1, 12],
      ...hats8(),
      [7, 2],
      [7, 10],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-46',
    name: 'R&B Skip Step',
    genre: 'R&B',
    role: 'drums',
    bpm: 98,
    desc: 'Skippy kick into 3, snare+clap 2 & 4, busy hats',
    pattern: grid([
      [0, 0],
      [0, 2],
      [0, 7],
      [0, 8],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      [3, 0],
      [3, 2],
      [3, 4],
      [3, 6],
      [3, 8],
      [3, 10],
      [3, 12],
      [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-47',
    name: 'R&B Soft Focus',
    genre: 'R&B',
    role: 'drums',
    bpm: 80,
    desc: 'Soft-focus ballad — kick 1·4, snare 2 & 4, airy quarters',
    pattern: grid([
      [0, 0],
      [0, 14],
      [1, 4],
      [1, 12],
      [3, 0],
      [3, 8],
      [4, 6],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-48',
    name: 'R&B Plaza Night',
    genre: 'R&B',
    role: 'drums',
    bpm: 95,
    desc: 'City plaza night — sync kick, snare 2 & 4, tom fill end',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 10],
      [0, 13],
      [1, 4],
      [1, 12],
      ...hats8(),
      [5, 14],
      [6, 15],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-49',
    name: 'R&B Smoke Room',
    genre: 'R&B',
    role: 'drums',
    bpm: 85,
    desc: 'Smoke-room pocket — behind-grid kick, snare 2 & 4, rim ghosts',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      [3, 2],
      [3, 6],
      [3, 10],
      [3, 14],
      [7, 3],
      [7, 11],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-50',
    name: 'R&B Lift Off',
    genre: 'R&B',
    role: 'drums',
    bpm: 102,
    desc: 'Uptempo lift — denser kick, snare+clap, open hats on &s',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 5],
      [0, 8],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      [3, 0],
      [3, 2],
      [3, 4],
      [3, 6],
      [3, 8],
      [3, 10],
      [3, 12],
      [3, 14],
      [4, 2],
      [4, 6],
      [4, 10],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-51',
    name: 'R&B Silk Walk',
    genre: 'R&B',
    role: 'drums',
    bpm: 88,
    desc: 'Silk walk — kick 1 · late 3, snare 2 & 4, soft shuffle hats',
    pattern: grid([
      [0, 0],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      [3, 1],
      [3, 3],
      [3, 5],
      [3, 7],
      [3, 9],
      [3, 11],
      [3, 13],
      [3, 15],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-52',
    name: 'R&B Trap Soul',
    genre: 'R&B',
    role: 'drums',
    bpm: 92,
    desc: 'Trap-soul hybrid — sync kick, snare 2 & 4, clap stack, 8ths',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 10],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      ...hats8(),
      [4, 6],
    ]),
  },
  {
    id: 'rnb-53',
    name: 'R&B Church Push',
    genre: 'R&B',
    role: 'drums',
    bpm: 96,
    desc: 'Gospel-tinged push — kick 1·2·3·&4, snare 2 & 4, open lifts',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 14],
      [1, 4],
      [1, 12],
      ...hats8(),
      [4, 2],
      [4, 10],
    ]),
  },
  {
    id: 'rnb-54',
    name: 'R&B Brush Pocket',
    genre: 'R&B',
    role: 'drums',
    bpm: 80,
    desc: 'Brush feel — soft kick, late snare, sparse offbeat hats',
    pattern: grid([
      [0, 0],
      [0, 10],
      [1, 5],
      [1, 13],
      [3, 2],
      [3, 6],
      [3, 10],
      [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-55',
    name: 'R&B Neo Push',
    genre: 'R&B',
    role: 'drums',
    bpm: 94,
    desc: 'Neo-soul push — kick 1 · &2 · 3, snare ghosts, silk 8ths',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 8],
      [0, 11],
      [1, 4],
      [1, 12],
      [1, 14],
      ...hats8(),
      [4, 14],
    ]),
  },
  {
    id: 'rnb-56',
    name: 'R&B Verse Air',
    genre: 'R&B',
    role: 'drums',
    bpm: 84,
    desc: 'Airy verse — kick 1 · 3 · pickup, snare 2 & 4, quarter hats',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 15],
      [1, 4],
      [1, 12],
      [3, 0],
      [3, 4],
      [3, 8],
      [3, 12],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-57',
    name: 'R&B Chorus Heat',
    genre: 'R&B',
    role: 'drums',
    bpm: 98,
    desc: 'Chorus energy — denser kick, snare+clap, open hat bounce',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 11],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      ...hats8(),
      [4, 2],
      [4, 6],
      [4, 10],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-58',
    name: 'R&B Late Night',
    genre: 'R&B',
    role: 'drums',
    bpm: 76,
    desc: 'Late-night chill — lean kick, half-time snare option + 2&4, soft hats',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 12],
      [0, 14],
      [1, 4],
      [1, 12],
      [3, 2],
      [3, 6],
      [3, 10],
      [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'rnb-59',
    name: 'R&B Double 3',
    genre: 'R&B',
    role: 'drums',
    bpm: 90,
    desc: 'Doubles around beat 3 — kick chatter, snare 2 & 4, rim ghosts',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 9],
      [0, 11],
      [1, 4],
      [1, 12],
      [7, 2],
      [7, 6],
      [7, 10],
      [7, 14],
      ...hats8(),
      [4, 14],
    ]),
  },
  {
    id: 'rnb-60',
    name: 'R&B Swing 8',
    genre: 'R&B',
    role: 'drums',
    bpm: 86,
    desc: 'Swung eighth feel — kick 1 · a2 · &3 · a4, snare 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 5],
      [0, 10],
      [0, 15],
      [1, 4],
      [1, 12],
      [3, 1],
      [3, 3],
      [3, 5],
      [3, 7],
      [3, 9],
      [3, 11],
      [3, 13],
      [3, 15],
      [4, 6],
    ]),
  },

  // ── Up Tempo ──────────────────────────────────────────────────────────────
  {
    id: 'miami-40',
    name: 'Trunk Shake',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 134,
    desc: 'Heavy booty trunk — kick 1·&2·3·&4, snare lock 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 8],
      [0, 14],
      ...miamiSnare(),
      ...miamiHats8(),
      [4, 10],
    ]),
  },
  {
    id: 'miami-41',
    name: 'Bass Drop Club',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 136,
    desc: 'Club drop — kick doubles into 3, snare 2 & 4, lite hats',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 8],
      [0, 11],
      ...miamiSnare(),
      ...miamiHatsLite(),
      [4, 14],
      [7, 6],
    ]),
  },
  {
    id: 'miami-42',
    name: 'Jook Parade',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 138,
    desc: 'Parade bounce — sync kick, snare 2 & 4, jerky 8ths',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 7],
      [0, 8],
      [0, 12],
      [0, 15],
      ...miamiSnare(),
      [3, 0],
      [3, 2],
      [3, 6],
      [3, 8],
      [3, 10],
      [3, 14],
      [4, 2],
    ]),
  },
  {
    id: 'miami-43',
    name: 'Electro Booty',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 132,
    desc: 'Electro pulse kick, snare lock, open hat pump',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 10],
      [0, 12],
      ...miamiSnare(),
      ...miamiHats8(),
      [4, 2],
      [4, 6],
      [4, 10],
      [4, 14],
    ]),
  },
  {
    id: 'miami-44',
    name: '808 Cannon',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 140,
    desc: 'Thunder kicks on the floor, snare 2 & 4, sparse hats',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 12],
      [0, 14],
      ...miamiSnare(),
      ...miamiHatsLite(),
      [7, 8],
    ]),
  },
  {
    id: 'miami-45',
    name: 'Street Lean',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 130,
    desc: 'Street lean pocket — kick 1 · &2 · late 3, snare lock',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 11],
      ...miamiSnare(),
      ...miamiHats8(),
      [4, 14],
    ]),
  },
  {
    id: 'miami-46',
    name: 'Quad Push',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 135,
    desc: 'Four-on trunk with offbeat pushes, snare 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 4],
      [0, 8],
      [0, 12],
      [0, 2],
      [0, 10],
      ...miamiSnare(),
      ...miamiHatsLite(),
      [4, 6],
    ]),
  },
  {
    id: 'miami-47',
    name: 'Rim Club',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 142,
    desc: 'Rim chatter club — busy kick, snare lock, rim offbeats',
    pattern: grid([
      [0, 0],
      [0, 3],
      [0, 8],
      [0, 11],
      [0, 14],
      ...miamiSnare(),
      ...miamiHats8(),
      [7, 2],
      [7, 6],
      [7, 10],
      [7, 14],
    ]),
  },
  {
    id: 'miami-48',
    name: 'Orbit Bounce',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 128,
    desc: 'Orbit drop bounce — sync kick into 3, snare 2 & 4',
    pattern: grid([
      [0, 0],
      [0, 5],
      [0, 8],
      [0, 13],
      ...miamiSnare(),
      ...miamiHatsLite(),
      [4, 10],
      [4, 14],
    ]),
  },
  {
    id: 'miami-49',
    name: 'Block Thunder',
    genre: 'Up Tempo',
    role: 'drums',
    bpm: 137,
    desc: 'Block-party thunder — kick 1·3·&4, snare lock, clap stack',
    pattern: grid([
      [0, 0],
      [0, 8],
      [0, 14],
      ...miamiSnare(),
      [2, 4],
      [2, 12],
      ...miamiHats8(),
      [4, 14],
    ]),
  },
];

/** BPM table entries for getPatternPresetBpm (optional — presets also set bpm). */
export const BEAT_LAB_SE2_BEAT_PADS_BANK_BPM: Readonly<Record<string, number>> = Object.fromEntries(
  BEAT_LAB_SE2_BEAT_PADS_BANK_PACK.filter((p) => typeof p.bpm === 'number').map((p) => [
    p.id,
    p.bpm!,
  ]),
);
