/**
 * Beat Pads Lane Placement — large kick (+ rim/perc) expansion pack.
 * ~20 extra kick patterns per genre, plus more rim/perc placements.
 */
import type {
  BeatPadsDrumRole,
  BeatPadsLanePlacementTemplate,
  BeatPadsPlacementGenre,
} from '@/app/lib/creationStation/beatPadsLanePlacementTemplates';

function bar(...steps: number[]): readonly number[] {
  return steps;
}

function tpl(
  id: string,
  name: string,
  role: BeatPadsDrumRole,
  genre: BeatPadsPlacementGenre,
  desc: string,
  steps: readonly number[],
): BeatPadsLanePlacementTemplate {
  return { id, name, role, genre, desc, steps };
}

/** Merged into ALL_TEMPLATES after core + extended banks. */
export const BEAT_PADS_KICK_PACK_TEMPLATES: readonly BeatPadsLanePlacementTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // TRAP — +30 kicks (+10 solid), +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('trap-kick-drill-stomp', 'Drill Stomp', 'kick', 'trap', 'UK drill — 1 · late 2 · 3 · &4', bar(0, 7, 8, 14)),
  tpl('trap-kick-brooklyn', 'Brooklyn Bounce', 'kick', 'trap', 'East coast bounce — 1 · &2 · late 3', bar(0, 6, 11)),
  tpl('trap-kick-pluggnb', 'Pluggnb Soft', 'kick', 'trap', 'Soft plugg — 1 · ghost 3 · pickup', bar(0, 9, 14)),
  tpl('trap-kick-rage', 'Rage Double', 'kick', 'trap', 'Rage doubles into 3', bar(0, 7, 8, 10, 11)),
  tpl('trap-kick-choppa', 'Choppa', 'kick', 'trap', 'Fast chop before 3', bar(0, 8, 10, 11, 12)),
  tpl('trap-kick-slide808', '808 Slide In', 'kick', 'trap', 'Slide in from &4', bar(0, 8, 13, 14, 15)),
  tpl('trap-kick-ghost3', 'Ghost 3', 'kick', 'trap', '1 · soft ghosts around 3', bar(0, 7, 9, 11)),
  tpl('trap-kick-club140', 'Club 140', 'kick', 'trap', 'Club tempo trunk', bar(0, 4, 8, 11)),
  tpl('trap-kick-darkwave', 'Darkwave', 'kick', 'trap', 'Sparse darkwave 1 · late 3', bar(0, 11)),
  tpl('trap-kick-phonk', 'Phonk Cowbell', 'kick', 'trap', 'Phonk four-lite + sync', bar(0, 4, 8, 12, 14)),
  tpl('trap-kick-jersey', 'Jersey Club', 'kick', 'trap', 'Jersey kick chatter', bar(0, 3, 6, 8, 11, 14)),
  tpl('trap-kick-miami', 'Miami Bass', 'kick', 'trap', 'Miami trunk 1 · 2& · 3', bar(0, 6, 8)),
  tpl('trap-kick-detroit', 'Detroit Lean', 'kick', 'trap', 'Detroit lean 1 · &3 · pickup', bar(0, 10, 14, 15)),
  tpl('trap-kick-houston', 'Houston Chop', 'kick', 'trap', 'Chopped & screwed feel', bar(0, 5, 8, 13)),
  tpl('trap-kick-triple-end', 'Triple End', 'kick', 'trap', 'Triplet finish into bar', bar(0, 8, 13, 14, 15)),
  tpl('trap-kick-half-rush', 'Half Rush', 'kick', 'trap', 'Half-time then rush', bar(0, 8, 12, 14, 15)),
  tpl('trap-kick-offgrid', 'Off-Grid Push', 'kick', 'trap', 'Pushed &s — 1 · a2 · &3 · a4', bar(0, 7, 10, 15)),
  tpl('trap-kick-two-bar-a', 'A Phrase', 'kick', 'trap', 'Phrase A — open trunk', bar(0, 6, 8, 14)),
  tpl('trap-kick-two-bar-b', 'B Answer', 'kick', 'trap', 'Phrase B answer — denser', bar(0, 3, 8, 10, 14)),
  tpl('trap-kick-only-and', 'And Hits', 'kick', 'trap', 'Mostly &s — bounce glue', bar(2, 6, 8, 10, 14)),

  // Solid trap trunks — clean 2–4 hit pockets, no triplet rushes / stacked doubles.
  tpl('trap-kick-solid-13', 'Solid 1 & 3', 'kick', 'trap', 'Clean trunk — beat 1 and 3 only', bar(0, 8)),
  tpl('trap-kick-solid-138', 'Solid 1·3·&4', 'kick', 'trap', 'Classic trap — 1 · 3 · & of 4', bar(0, 8, 14)),
  tpl('trap-kick-solid-metro', 'Solid Metro', 'kick', 'trap', 'Metro pocket — 1 · &2 · 3', bar(0, 6, 8)),
  tpl('trap-kick-solid-1811', 'Solid 1·&2·a3', 'kick', 'trap', 'Modern trap — 1 · beat 3 · late 3', bar(0, 8, 11)),
  tpl('trap-kick-solid-south', 'Solid South', 'kick', 'trap', 'Southern — 1 · &2 · &3', bar(0, 6, 10)),
  tpl('trap-kick-solid-lean', 'Solid Lean', 'kick', 'trap', 'Lean pocket — 1 · late 3', bar(0, 11)),
  tpl('trap-kick-solid-bounce', 'Solid Bounce', 'kick', 'trap', 'Bounce — 1 · &2 · 3 · &4', bar(0, 6, 8, 14)),
  tpl('trap-kick-solid-space', 'Solid Space', 'kick', 'trap', 'Wide space — downbeat only', bar(0)),
  tpl('trap-kick-solid-push', 'Solid Push', 'kick', 'trap', 'Push — 1 · & of 3 · & of 4', bar(0, 10, 14)),
  tpl('trap-kick-solid-club', 'Solid Club', 'kick', 'trap', 'Club trunk — 1 · 2 · 3', bar(0, 4, 8)),

  tpl('trap-rim-tick16', 'Tick 16', 'rim', 'trap', 'Light 16th ticks', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('trap-rim-backbeat', 'Rim Backbeat', 'rim', 'trap', 'Rim on 2 & 4', bar(4, 12)),
  tpl('trap-rim-triplet', 'Rim Triplet', 'rim', 'trap', 'Triplet rim fill', bar(9, 10, 11, 13, 14, 15)),
  tpl('trap-rim-sync', 'Rim Sync', 'rim', 'trap', 'Syncopated rim pocket', bar(3, 6, 11, 14)),
  tpl('trap-rim-ghosts', 'Rim Ghosts', 'rim', 'trap', 'Soft ghost rims', bar(2, 5, 7, 10, 13)),
  tpl('trap-rim-bar-end', 'Bar End', 'rim', 'trap', 'Bar-end rim chatter', bar(12, 13, 14, 15)),
  tpl('trap-rim-skip', 'Skip Rim', 'rim', 'trap', 'Skip downbeats', bar(1, 3, 6, 9, 11, 14)),
  tpl('trap-rim-clave', 'Clave Hint', 'rim', 'trap', '3-2 clave rim hint', bar(0, 3, 6, 10, 12)),

  // ═══════════════════════════════════════════════════════════════════════════
  // R&B — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('rnb-kick-quiet-storm', 'Quiet Storm', 'kick', 'rnb', 'Soft storm pocket', bar(0, 7, 10, 14)),
  tpl('rnb-kick-90s-newjack', '90s New Jack', 'kick', 'rnb', 'New jack swing lean', bar(0, 5, 8, 13)),
  tpl('rnb-kick-alt-rnb', 'Alt R&B', 'kick', 'rnb', 'Sparse alt pocket', bar(0, 10, 13)),
  tpl('rnb-kick-chrisb', 'Contemporary', 'kick', 'rnb', 'Contemporary 1 · &2 · 3', bar(0, 6, 8, 11)),
  tpl('rnb-kick-bryson', 'Silk Trunk', 'kick', 'rnb', 'Silk 1 · late 3', bar(0, 11, 14)),
  tpl('rnb-kick-trap-soul', 'Trap Soul', 'kick', 'rnb', 'Trap-soul hybrid', bar(0, 8, 10, 14)),
  tpl('rnb-kick-church', 'Church Push', 'kick', 'rnb', 'Gospel-tinged push', bar(0, 4, 8, 14)),
  tpl('rnb-kick-bedroom', 'Bedroom', 'kick', 'rnb', 'Bedroom sparse', bar(0, 9)),
  tpl('rnb-kick-bounce-late', 'Late Bounce', 'kick', 'rnb', 'Late bounce pocket', bar(0, 7, 12, 14)),
  tpl('rnb-kick-double3', 'Double 3', 'kick', 'rnb', 'Doubles around 3', bar(0, 8, 9, 11)),
  tpl('rnb-kick-swing8', 'Swing 8', 'kick', 'rnb', 'Swung eighth feel', bar(0, 5, 10, 15)),
  tpl('rnb-kick-verse-air', 'Verse Air', 'kick', 'rnb', 'Airy verse', bar(0, 8, 15)),
  tpl('rnb-kick-chorus-push', 'Chorus Push', 'kick', 'rnb', 'Chorus energy', bar(0, 4, 8, 11, 14)),
  tpl('rnb-kick-bridge', 'Bridge Soft', 'kick', 'rnb', 'Bridge soft trunk', bar(0, 10)),
  tpl('rnb-kick-fill-in', 'Fill In', 'kick', 'rnb', 'Bar-end fill in', bar(0, 8, 12, 13, 14, 15)),
  tpl('rnb-kick-sidechain', 'Sidechain Pulse', 'kick', 'rnb', 'Pulse for pads', bar(0, 4, 8, 12)),
  tpl('rnb-kick-neo-16', 'Neo 16', 'kick', 'rnb', 'Neo-soul 16th lean', bar(0, 3, 8, 11, 14)),
  tpl('rnb-kick-deep-sub', 'Deep Sub', 'kick', 'rnb', 'Deep sub 1 · 3 only', bar(0, 8)),
  tpl('rnb-kick-offbeat', 'Offbeat Soul', 'kick', 'rnb', 'Offbeat soul push', bar(2, 6, 8, 14)),
  tpl('rnb-kick-turnaround', 'Turnaround', 'kick', 'rnb', 'Turnaround kicks', bar(0, 6, 10, 13, 14, 15)),
  tpl('rnb-rim-silk', 'Silk Rim', 'rim', 'rnb', 'Silk offbeat rim', bar(2, 6, 10, 14)),
  tpl('rnb-rim-ghost16', 'Ghost 16', 'rim', 'rnb', 'Soft 16th ghosts', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('rnb-rim-2and4', 'Rim 2&4', 'rim', 'rnb', 'Rim on backbeat', bar(4, 12)),
  tpl('rnb-rim-shuffle', 'Rim Shuffle', 'rim', 'rnb', 'Shuffle rim', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('rnb-rim-fill', 'Rim Fill', 'rim', 'rnb', 'Bar-end rim fill', bar(12, 13, 14, 15)),
  tpl('rnb-rim-clave', 'Rim Clave', 'rim', 'rnb', 'Soft clave rim', bar(0, 3, 6, 10, 12)),
  tpl('rnb-rim-skip', 'Skip Rim', 'rim', 'rnb', 'Skip pulse rim', bar(1, 5, 9, 13)),
  tpl('rnb-rim-brush-late', 'Brush Late', 'rim', 'rnb', 'Late brush ticks', bar(3, 7, 11, 15)),

  // ═══════════════════════════════════════════════════════════════════════════
  // POP — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('pop-kick-radio', 'Radio Ready', 'kick', 'pop', 'Radio 1 · 2 · 3 · 4 lite', bar(0, 4, 8, 12)),
  tpl('pop-kick-tiktok-drop', 'TikTok Drop', 'kick', 'pop', 'Drop punch + pickup', bar(0, 8, 12, 14, 15)),
  tpl('pop-kick-indie', 'Indie Soft', 'kick', 'pop', 'Indie soft trunk', bar(0, 8, 10)),
  tpl('pop-kick-electro', 'Electro Pop', 'kick', 'pop', 'Electro-pop drive', bar(0, 4, 6, 8, 12)),
  tpl('pop-kick-dancepop', 'Dance-Pop', 'kick', 'pop', 'Dance-pop four + sync', bar(0, 4, 8, 10, 12)),
  tpl('pop-kick-ballad-wide', 'Ballad Wide', 'kick', 'pop', 'Wide ballad 1 · 3', bar(0, 8)),
  tpl('pop-kick-prechorus', 'Pre-Chorus', 'kick', 'pop', 'Pre-chorus lift', bar(0, 8, 14, 15)),
  tpl('pop-kick-postchorus', 'Post Chorus', 'kick', 'pop', 'Post-chorus bounce', bar(0, 3, 8, 11)),
  tpl('pop-kick-uk-pop', 'UK Pop', 'kick', 'pop', 'UK pop skip', bar(0, 5, 8, 13)),
  tpl('pop-kick-latin-radio', 'Latin Radio', 'kick', 'pop', 'Latin-pop radio', bar(0, 3, 8, 11, 14)),
  tpl('pop-kick-afro-pop', 'Afro-Pop Cross', 'kick', 'pop', 'Afro-pop crossover', bar(0, 6, 8, 10, 14)),
  tpl('pop-kick-synthwave', 'Synthwave', 'kick', 'pop', 'Synthwave four-on', bar(0, 4, 8, 12)),
  tpl('pop-kick-sparse-verse', 'Sparse Verse', 'kick', 'pop', 'Ultra sparse verse', bar(0)),
  tpl('pop-kick-big-chorus', 'Big Chorus', 'kick', 'pop', 'Big chorus push', bar(0, 4, 8, 10, 12, 14)),
  tpl('pop-kick-sync-16', 'Sync 16', 'kick', 'pop', '16th sync pop', bar(0, 3, 6, 8, 11, 14)),
  tpl('pop-kick-half-drop', 'Half Drop', 'kick', 'pop', 'Half-time drop', bar(0, 8, 14)),
  tpl('pop-kick-garage-pop', 'Garage Pop', 'kick', 'pop', 'Garage-pop skip', bar(0, 5, 8, 13)),
  tpl('pop-kick-double-down', 'Double Down', 'kick', 'pop', 'Doubles on 1 and 3', bar(0, 1, 8, 9)),
  tpl('pop-kick-lift4', 'Lift 4', 'kick', 'pop', 'Lift into beat 4', bar(0, 8, 11, 12)),
  tpl('pop-kick-outro', 'Outro Soft', 'kick', 'pop', 'Soft outro', bar(0, 12)),
  tpl('pop-rim-click', 'Click Rim', 'rim', 'pop', 'Clicky quarter rim', bar(0, 4, 8, 12)),
  tpl('pop-rim-off16', 'Off 16', 'rim', 'pop', 'Offbeat 16ths', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('pop-rim-back', 'Rim Back', 'rim', 'pop', 'Backbeat rim', bar(4, 12)),
  tpl('pop-rim-fill', 'Rim Fill', 'rim', 'pop', 'Bar-end rim', bar(13, 14, 15)),
  tpl('pop-rim-bounce', 'Rim Bounce', 'rim', 'pop', 'Bounce rim', bar(2, 6, 10, 14)),
  tpl('pop-rim-sparse', 'Rim Sparse', 'rim', 'pop', 'Sparse rim', bar(6, 14)),
  tpl('pop-rim-roll', 'Rim Roll', 'rim', 'pop', 'Rim roll end', bar(12, 13, 14, 15)),
  tpl('pop-rim-latin', 'Rim Latin', 'rim', 'pop', 'Latin rim hint', bar(0, 3, 6, 10, 12)),

  // ═══════════════════════════════════════════════════════════════════════════
  // HOUSE — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('house-kick-chicago', 'Chicago Four', 'kick', 'house', 'Classic Chicago four', bar(0, 4, 8, 12)),
  tpl('house-kick-detroit', 'Detroit Techno', 'kick', 'house', 'Detroit hard four', bar(0, 4, 8, 12)),
  tpl('house-kick-ukg-skip', 'UKG Skip', 'kick', 'house', 'UK garage skip twin', bar(0, 5, 8, 13)),
  tpl('house-kick-2step', '2-Step', 'kick', 'house', '2-step garage', bar(0, 6, 8, 14)),
  tpl('house-kick-tech', 'Tech House', 'kick', 'house', 'Tech-house punch', bar(0, 4, 8, 10, 12)),
  tpl('house-kick-deep-soft', 'Deep Soft', 'kick', 'house', 'Deep soft four', bar(0, 4, 8, 12)),
  tpl('house-kick-afrohouse', 'Afro House', 'kick', 'house', 'Afro-house sync', bar(0, 3, 8, 11, 12)),
  tpl('house-kick-organic', 'Organic', 'kick', 'house', 'Organic house lean', bar(0, 4, 8, 11, 12)),
  tpl('house-kick-bassline', 'Bassline', 'kick', 'house', 'Bassline UK feel', bar(0, 4, 7, 8, 12)),
  tpl('house-kick-french', 'French Filter', 'kick', 'house', 'French filter drive', bar(0, 4, 8, 12, 14)),
  tpl('house-kick-minimal-pulse', 'Minimal Pulse', 'kick', 'house', 'Minimal pulse', bar(0, 8)),
  tpl('house-kick-peak', 'Peak Time', 'kick', 'house', 'Peak-time energy', bar(0, 4, 8, 10, 12, 14)),
  tpl('house-kick-breakdown', 'Breakdown', 'kick', 'house', 'Breakdown sparse', bar(0)),
  tpl('house-kick-build16', 'Build 16', 'kick', 'house', 'Build denser end', bar(0, 4, 8, 10, 12, 13, 14, 15)),
  tpl('house-kick-offbeat-push', 'Offbeat Push', 'kick', 'house', 'Offbeat push variant', bar(0, 3, 6, 8, 12)),
  tpl('house-kick-swing-house', 'Swing House', 'kick', 'house', 'Swung house', bar(0, 5, 8, 13)),
  tpl('house-kick-jack', 'Jack', 'kick', 'house', 'Jacking Chicago', bar(0, 4, 6, 8, 12)),
  tpl('house-kick-tribal', 'Tribal', 'kick', 'house', 'Tribal house stomp', bar(0, 3, 4, 8, 11, 12)),
  tpl('house-kick-late3', 'Late 3', 'kick', 'house', 'Four + late 3 ghost', bar(0, 4, 8, 11, 12)),
  tpl('house-kick-drop-in', 'Drop In', 'kick', 'house', 'Drop-in pickup', bar(0, 4, 8, 12, 14, 15)),
  tpl('house-rim-conga', 'Conga Rim', 'rim', 'house', 'Conga-style rim', bar(2, 6, 10, 14)),
  tpl('house-rim-clave', 'House Clave', 'rim', 'house', 'Clave perc', bar(0, 3, 6, 10, 12)),
  tpl('house-rim-16', 'Rim 16', 'rim', 'house', 'Busy 16th rim', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('house-rim-off', 'Rim Off', 'rim', 'house', 'Offbeat rim', bar(2, 6, 10, 14)),
  tpl('house-rim-fill', 'Rim Fill', 'rim', 'house', 'Bar-end rim', bar(13, 14, 15)),
  tpl('house-rim-tom', 'Tom Rim', 'rim', 'house', 'Tom-ish rim hits', bar(0, 6, 8, 14)),
  tpl('house-rim-sparse', 'Rim Sparse', 'rim', 'house', 'Sparse rim', bar(6, 14)),
  tpl('house-rim-shuffle', 'Rim Shuffle+', 'rim', 'house', 'Shuffled rim+', bar(1, 2, 5, 6, 9, 10, 13, 14)),

  // ═══════════════════════════════════════════════════════════════════════════
  // DANCE — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('dance-kick-bigroom', 'Big Room', 'kick', 'dance', 'Big-room four', bar(0, 4, 8, 12)),
  tpl('dance-kick-trance', 'Trance', 'kick', 'dance', 'Trance four-on', bar(0, 4, 8, 12)),
  tpl('dance-kick-dubstep', 'Dubstep Half', 'kick', 'dance', 'Dubstep half-time', bar(0, 8)),
  tpl('dance-kick-futurebass', 'Future Bass', 'kick', 'dance', 'Future bass bounce', bar(0, 6, 8, 14)),
  tpl('dance-kick-hardstyle', 'Hardstyle', 'kick', 'dance', 'Hardstyle reverse feel', bar(0, 4, 8, 12, 14)),
  tpl('dance-kick-psy', 'Psy Kick', 'kick', 'dance', 'Psytrance drive', bar(0, 4, 8, 12)),
  tpl('dance-kick-electrohouse', 'Electro House', 'kick', 'dance', 'Electro-house punch', bar(0, 4, 8, 10, 12)),
  tpl('dance-kick-progressive', 'Progressive', 'kick', 'dance', 'Progressive build', bar(0, 4, 8, 12, 14, 15)),
  tpl('dance-kick-mainstage', 'Mainstage', 'kick', 'dance', 'Mainstage energy', bar(0, 4, 8, 10, 12, 14)),
  tpl('dance-kick-breakdown2', 'Breakdown Soft', 'kick', 'dance', 'Soft breakdown', bar(0)),
  tpl('dance-kick-riser', 'Riser Kick', 'kick', 'dance', 'Riser densifies', bar(0, 8, 12, 13, 14, 15)),
  tpl('dance-kick-drop-wide', 'Drop Wide', 'kick', 'dance', 'Wide drop kicks', bar(0, 4, 8, 12, 14, 15)),
  tpl('dance-kick-melodic', 'Melodic', 'kick', 'dance', 'Melodic techno lean', bar(0, 4, 8, 11, 12)),
  tpl('dance-kick-bass-house', 'Bass House', 'kick', 'dance', 'Bass-house chatter', bar(0, 3, 4, 8, 11, 12)),
  tpl('dance-kick-jersey-x', 'Jersey Cross', 'kick', 'dance', 'Jersey-dance cross', bar(0, 3, 6, 8, 11, 14)),
  tpl('dance-kick-trap-edm', 'Trap EDM', 'kick', 'dance', 'Trap-EDM hybrid', bar(0, 8, 11, 14)),
  tpl('dance-kick-off-sync', 'Off Sync', 'kick', 'dance', 'Off sync dance', bar(0, 6, 8, 14)),
  tpl('dance-kick-double-drop', 'Double Drop', 'kick', 'dance', 'Double into drop', bar(0, 1, 4, 8, 12)),
  tpl('dance-kick-verse-lite', 'Verse Lite', 'kick', 'dance', 'Lite verse', bar(0, 8)),
  tpl('dance-kick-chorus-max', 'Chorus Max', 'kick', 'dance', 'Max chorus density', bar(0, 4, 6, 8, 10, 12, 14)),
  tpl('dance-rim-laser', 'Laser Rim', 'rim', 'dance', 'Laser perc ticks', bar(1, 5, 9, 13)),
  tpl('dance-rim-off', 'Dance Off', 'rim', 'dance', 'Offbeat dance rim', bar(2, 6, 10, 14)),
  tpl('dance-rim-build', 'Rim Build', 'rim', 'dance', 'Build rim chatter', bar(8, 9, 10, 11, 12, 13, 14, 15)),
  tpl('dance-rim-drop', 'Rim Drop', 'rim', 'dance', 'Drop rim hits', bar(4, 12)),
  tpl('dance-rim-16', 'Rim 16', 'rim', 'dance', '16th rim layer', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('dance-rim-sparse', 'Rim Sparse', 'rim', 'dance', 'Sparse rim', bar(6, 14)),
  tpl('dance-rim-fill', 'Rim Fill', 'rim', 'dance', 'Bar-end rim', bar(13, 14, 15)),
  tpl('dance-rim-tribal', 'Tribal Rim', 'rim', 'dance', 'Tribal perc rim', bar(0, 3, 6, 8, 11, 14)),

  // ═══════════════════════════════════════════════════════════════════════════
  // K-POP — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('kpop-kick-idol-chorus', 'Idol Chorus', 'kick', 'kpop', 'Idol chorus drive', bar(0, 4, 6, 8, 10, 12)),
  tpl('kpop-kick-title-drop', 'Title Drop', 'kick', 'kpop', 'Title-track drop', bar(0, 8, 12, 14, 15)),
  tpl('kpop-kick-verse-soft', 'Verse Soft', 'kick', 'kpop', 'Soft verse', bar(0, 8, 10)),
  tpl('kpop-kick-bridge', 'Bridge Lift', 'kick', 'kpop', 'Bridge lift', bar(0, 8, 14)),
  tpl('kpop-kick-edm-hook', 'EDM Hook', 'kick', 'kpop', 'EDM-hook four', bar(0, 4, 8, 12)),
  tpl('kpop-kick-hiphop', 'Hip-Hop Side', 'kick', 'kpop', 'Hip-hop side track', bar(0, 6, 8, 11)),
  tpl('kpop-kick-rnb-side', 'R&B Side', 'kick', 'kpop', 'R&B-side pocket', bar(0, 7, 10, 14)),
  tpl('kpop-kick-dancebreak', 'Dance Break', 'kick', 'kpop', 'Dance-break stomp', bar(0, 3, 8, 11)),
  tpl('kpop-kick-double-chorus', 'Double Chorus', 'kick', 'kpop', 'Double-chorus push', bar(0, 4, 8, 10, 12, 14)),
  tpl('kpop-kick-pre', 'Pre Hook', 'kick', 'kpop', 'Pre-hook pickup', bar(0, 8, 13, 14, 15)),
  tpl('kpop-kick-trap-idol', 'Trap Idol', 'kick', 'kpop', 'Trap-idol hybrid', bar(0, 8, 11, 14)),
  tpl('kpop-kick-latin-k', 'Latin K', 'kick', 'kpop', 'Latin K-pop', bar(0, 3, 6, 10, 13)),
  tpl('kpop-kick-city-pop', 'City Pop', 'kick', 'kpop', 'City-pop soft four', bar(0, 4, 8, 12)),
  tpl('kpop-kick-minimal-hook', 'Minimal Hook', 'kick', 'kpop', 'Minimal hook', bar(0, 8)),
  tpl('kpop-kick-sync-bright', 'Sync Bright', 'kick', 'kpop', 'Bright sync', bar(0, 6, 8, 14)),
  tpl('kpop-kick-stack-end', 'Stack End', 'kick', 'kpop', 'Stack into bar end', bar(0, 8, 12, 13, 14, 15)),
  tpl('kpop-kick-half-chorus', 'Half Chorus', 'kick', 'kpop', 'Half-time chorus', bar(0, 8, 14)),
  tpl('kpop-kick-bounce-k', 'Bounce K', 'kick', 'kpop', 'Bounce pocket', bar(0, 3, 8, 11, 14)),
  tpl('kpop-kick-outro', 'Outro Soft', 'kick', 'kpop', 'Soft outro', bar(0, 12)),
  tpl('kpop-kick-intro', 'Intro Pulse', 'kick', 'kpop', 'Intro pulse', bar(0, 8, 12)),
  tpl('kpop-rim-idol', 'Idol Rim', 'rim', 'kpop', 'Idol perc ticks', bar(1, 5, 9, 13)),
  tpl('kpop-rim-16', 'Rim 16', 'rim', 'kpop', 'Busy 16ths', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('kpop-rim-back', 'Rim Back', 'rim', 'kpop', 'Backbeat rim', bar(4, 12)),
  tpl('kpop-rim-dance', 'Dance Rim', 'rim', 'kpop', 'Dance-break rim', bar(2, 6, 10, 14)),
  tpl('kpop-rim-fill+', 'Fill+', 'rim', 'kpop', 'Bigger bar-end fill', bar(12, 13, 14, 15)),
  tpl('kpop-rim-clave', 'Clave K', 'rim', 'kpop', 'Clave rim', bar(0, 3, 6, 10, 12)),
  tpl('kpop-rim-ghost', 'Ghost Rim', 'rim', 'kpop', 'Ghost rim', bar(3, 7, 11, 15)),
  tpl('kpop-rim-roll', 'Rim Roll', 'rim', 'kpop', 'Rim roll', bar(11, 12, 13, 14, 15)),

  // ═══════════════════════════════════════════════════════════════════════════
  // SOUL BLUES — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('soulblues-kick-memphis', 'Memphis Stomp', 'kick', 'soulBlues', 'Memphis stomp', bar(0, 5, 8, 13)),
  tpl('soulblues-kick-stax', 'Stax', 'kick', 'soulBlues', 'Stax pocket', bar(0, 8, 10)),
  tpl('soulblues-kick-muscle', 'Muscle Shoals', 'kick', 'soulBlues', 'Muscle Shoals lean', bar(0, 7, 11)),
  tpl('soulblues-kick-chicago-b', 'Chicago Blues', 'kick', 'soulBlues', 'Chicago blues walk', bar(0, 4, 8, 12)),
  tpl('soulblues-kick-delta', 'Delta', 'kick', 'soulBlues', 'Delta sparse', bar(0, 10)),
  tpl('soulblues-kick-gospel2', 'Gospel 2', 'kick', 'soulBlues', 'Gospel push variant', bar(0, 4, 8, 11, 14)),
  tpl('soulblues-kick-motown', 'Motown', 'kick', 'soulBlues', 'Motown 1 · 3 · &4', bar(0, 8, 14)),
  tpl('soulblues-kick-philly', 'Philly', 'kick', 'soulBlues', 'Philly soul', bar(0, 6, 8, 14)),
  tpl('soulblues-kick-neo2', 'Neo 2', 'kick', 'soulBlues', 'Neo-soul blues', bar(0, 7, 10, 14)),
  tpl('soulblues-kick-shuffle2', 'Shuffle 2', 'kick', 'soulBlues', 'Deeper shuffle', bar(0, 5, 10, 15)),
  tpl('soulblues-kick-backbeat', 'Kick Backbeat', 'kick', 'soulBlues', 'Backbeat emphasis', bar(0, 4, 8, 12)),
  tpl('soulblues-kick-slowjam', 'Slow Jam', 'kick', 'soulBlues', 'Slow jam half', bar(0, 8)),
  tpl('soulblues-kick-turn2', 'Turn 2', 'kick', 'soulBlues', 'Turnaround denser', bar(0, 8, 12, 13, 14, 15)),
  tpl('soulblues-kick-boogie', 'Boogie', 'kick', 'soulBlues', 'Boogie four', bar(0, 4, 8, 12)),
  tpl('soulblues-kick-late', 'Late Pocket', 'kick', 'soulBlues', 'Late pocket', bar(0, 7, 12, 14)),
  tpl('soulblues-kick-double', 'Double Hit', 'kick', 'soulBlues', 'Double on 1', bar(0, 1, 8)),
  tpl('soulblues-kick-swing', 'Swing Trunk', 'kick', 'soulBlues', 'Swing trunk', bar(0, 5, 8, 13)),
  tpl('soulblues-kick-church2', 'Church 2', 'kick', 'soulBlues', 'Church shout push', bar(0, 3, 8, 11, 14)),
  tpl('soulblues-kick-verse', 'Verse Dry', 'kick', 'soulBlues', 'Dry verse', bar(0, 8, 15)),
  tpl('soulblues-kick-chorus', 'Chorus Fat', 'kick', 'soulBlues', 'Fat chorus', bar(0, 4, 8, 11, 14)),
  tpl('soulblues-rim-shuffle+', 'Shuffle+', 'rim', 'soulBlues', 'Full shuffle rim', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('soulblues-rim-back', 'Rim Back', 'rim', 'soulBlues', 'Backbeat rim', bar(4, 12)),
  tpl('soulblues-rim-train', 'Train', 'rim', 'soulBlues', 'Train beat rim', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('soulblues-rim-ghost+', 'Ghost+', 'rim', 'soulBlues', 'Ghost rim+', bar(2, 3, 6, 7, 10, 11, 14, 15)),
  tpl('soulblues-rim-fill+', 'Fill+', 'rim', 'soulBlues', 'Turnaround fill', bar(12, 13, 14, 15)),
  tpl('soulblues-rim-click', 'Click', 'rim', 'soulBlues', 'Click quarters', bar(0, 4, 8, 12)),
  tpl('soulblues-rim-off', 'Off Rim', 'rim', 'soulBlues', 'Offbeat rim', bar(2, 6, 10, 14)),
  tpl('soulblues-rim-sparse2', 'Sparse 2', 'rim', 'soulBlues', 'Sparse rim variant', bar(6, 14)),

  // ═══════════════════════════════════════════════════════════════════════════
  // AFRO — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('afro-kick-afrobeats', 'Afrobeats', 'kick', 'afro', 'Classic afrobeats', bar(0, 6, 8, 14)),
  tpl('afro-kick-amapiano2', 'Amapiano 2', 'kick', 'afro', 'Amapiano log pocket', bar(0, 8, 10, 14)),
  tpl('afro-kick-gqom', 'Gqom', 'kick', 'afro', 'Gqom stomp', bar(0, 3, 8, 11)),
  tpl('afro-kick-azonto', 'Azonto', 'kick', 'afro', 'Azonto bounce', bar(0, 5, 8, 13)),
  tpl('afro-kick-fuji', 'Fuji', 'kick', 'afro', 'Fuji pulse', bar(0, 4, 8, 12)),
  tpl('afro-kick-soukous', 'Soukous', 'kick', 'afro', 'Soukous drive', bar(0, 4, 8, 10, 12)),
  tpl('afro-kick-highlife2', 'Highlife 2', 'kick', 'afro', 'Highlife variant', bar(0, 6, 8, 12)),
  tpl('afro-kick-dembow2', 'Dembow 2', 'kick', 'afro', 'Dembow denser', bar(0, 3, 6, 8, 11, 14)),
  tpl('afro-kick-afrohouse2', 'Afro House', 'kick', 'afro', 'Afro-house four', bar(0, 4, 8, 12)),
  tpl('afro-kick-naija-pop', 'Naija Pop', 'kick', 'afro', 'Naija pop trunk', bar(0, 6, 8, 10)),
  tpl('afro-kick-accra', 'Accra', 'kick', 'afro', 'Accra swing', bar(0, 5, 10, 13)),
  tpl('afro-kick-lagos2', 'Lagos 2', 'kick', 'afro', 'Lagos denser', bar(0, 3, 6, 8, 10, 14)),
  tpl('afro-kick-sparse2', 'Sparse 2', 'kick', 'afro', 'Sparse trunk 2', bar(0, 8)),
  tpl('afro-kick-push2', 'Push 2', 'kick', 'afro', 'Push variant', bar(0, 7, 10, 13, 14)),
  tpl('afro-kick-shaku2', 'Shaku 2', 'kick', 'afro', 'Shaku denser', bar(0, 3, 6, 8, 11)),
  tpl('afro-kick-3-2', '3-2 Pulse', 'kick', 'afro', '3-2 pulse', bar(0, 3, 6, 10, 12)),
  tpl('afro-kick-2-3', '2-3 Pulse', 'kick', 'afro', '2-3 pulse', bar(0, 4, 8, 11, 14)),
  tpl('afro-kick-pickup2', 'Pickup 2', 'kick', 'afro', 'Pickup denser', bar(0, 8, 13, 14, 15)),
  tpl('afro-kick-chorus', 'Chorus Fat', 'kick', 'afro', 'Fat chorus', bar(0, 4, 6, 8, 12, 14)),
  tpl('afro-kick-verse', 'Verse Light', 'kick', 'afro', 'Light verse', bar(0, 10)),
  tpl('afro-rim-shekere', 'Shekere', 'rim', 'afro', 'Shekere-style ticks', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('afro-rim-clave', 'Afro Clave', 'rim', 'afro', 'Clave rim', bar(0, 3, 6, 10, 12)),
  tpl('afro-rim-talk2', 'Talk 2', 'rim', 'afro', 'Talking-drum rim', bar(2, 5, 8, 11, 14)),
  tpl('afro-rim-conga', 'Conga', 'rim', 'afro', 'Conga rim', bar(2, 6, 10, 14)),
  tpl('afro-rim-fill+', 'Fill+', 'rim', 'afro', 'Bar-end perc+', bar(12, 13, 14, 15)),
  tpl('afro-rim-sparse2', 'Sparse 2', 'rim', 'afro', 'Sparse rim 2', bar(6, 14)),
  tpl('afro-rim-djembe', 'Djembe', 'rim', 'afro', 'Djembe-ish hits', bar(0, 3, 5, 8, 11, 13)),
  tpl('afro-rim-off16', 'Off 16', 'rim', 'afro', 'Off 16ths', bar(1, 2, 5, 6, 9, 10, 13, 14)),

  // ═══════════════════════════════════════════════════════════════════════════
  // REGGAE — +20 kicks, +8 rim
  // ═══════════════════════════════════════════════════════════════════════════
  tpl('reggae-kick-onedrop2', 'One Drop 2', 'kick', 'reggae', 'One-drop + ghost', bar(8, 15)),
  tpl('reggae-kick-steppers2', 'Steppers 2', 'kick', 'reggae', 'Steppers with lift', bar(0, 4, 8, 12, 14)),
  tpl('reggae-kick-rockers2', 'Rockers 2', 'kick', 'reggae', 'Rockers denser', bar(0, 6, 8)),
  tpl('reggae-kick-dancehall2', 'Dancehall 2', 'kick', 'reggae', 'Dancehall denser', bar(0, 6, 8, 11, 14)),
  tpl('reggae-kick-dub2', 'Dub 2', 'kick', 'reggae', 'Dub with echo hit', bar(0, 14)),
  tpl('reggae-kick-roots2', 'Roots 2', 'kick', 'reggae', 'Roots with &4', bar(0, 8, 14)),
  tpl('reggae-kick-ska', 'Ska Up', 'kick', 'reggae', 'Ska upbeat lean', bar(2, 6, 10, 14)),
  tpl('reggae-kick-rocksteady', 'Rocksteady', 'kick', 'reggae', 'Rocksteady 1 & 3', bar(0, 8)),
  tpl('reggae-kick-lovers', 'Lovers Rock', 'kick', 'reggae', 'Lovers rock soft', bar(0, 8, 10)),
  tpl('reggae-kick-rub2', 'Rub 2', 'kick', 'reggae', 'Rub-a-dub denser', bar(0, 5, 8, 10, 13)),
  tpl('reggae-kick-bashment', 'Bashment', 'kick', 'reggae', 'Bashment push', bar(0, 3, 8, 11, 14)),
  tpl('reggae-kick-island2', 'Island 2', 'kick', 'reggae', 'Island variant', bar(8, 12, 14)),
  tpl('reggae-kick-bubble2', 'Bubble 2', 'kick', 'reggae', 'Bubble denser', bar(0, 6, 8, 10, 14)),
  tpl('reggae-kick-nyabinghi-k', 'Nyabinghi K', 'kick', 'reggae', 'Nyabinghi kick pulse', bar(0, 4, 8, 12)),
  tpl('reggae-kick-half-drop', 'Half Drop', 'kick', 'reggae', 'Half-drop feel', bar(8)),
  tpl('reggae-kick-digital', 'Digital', 'kick', 'reggae', 'Digital dancehall', bar(0, 7, 8, 14)),
  tpl('reggae-kick-verse', 'Verse Soft', 'kick', 'reggae', 'Soft verse', bar(8, 12)),
  tpl('reggae-kick-chorus', 'Chorus Push', 'kick', 'reggae', 'Chorus push', bar(0, 4, 8, 12)),
  tpl('reggae-kick-pickup2', 'Pickup 2', 'kick', 'reggae', 'Turnaround denser', bar(12, 13, 14, 15)),
  tpl('reggae-kick-step-sync', 'Step Sync', 'kick', 'reggae', 'Steppers sync', bar(0, 4, 6, 8, 12)),
  tpl('reggae-rim-skank2', 'Skank 2', 'rim', 'reggae', 'Skank denser', bar(2, 3, 6, 7, 10, 11, 14, 15)),
  tpl('reggae-rim-count2', 'Count 2', 'rim', 'reggae', 'Faster count rim', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('reggae-rim-nya2', 'Nyabinghi 2', 'rim', 'reggae', 'Nyabinghi denser', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('reggae-rim-dub', 'Dub Rim', 'rim', 'reggae', 'Dub rim space', bar(6, 14)),
  tpl('reggae-rim-fill+', 'Fill+', 'rim', 'reggae', 'Bar-end rim+', bar(12, 13, 14, 15)),
  tpl('reggae-rim-back', 'Rim Back', 'rim', 'reggae', 'Backbeat rim', bar(4, 12)),
  tpl('reggae-rim-ghost', 'Ghost Rim', 'rim', 'reggae', 'Ghost rim', bar(3, 7, 11, 15)),
  tpl('reggae-rim-clave', 'Rim Clave', 'rim', 'reggae', 'Clave hint', bar(0, 3, 6, 10, 12)),
];
