/**
 * Platinum Urban Series — BeatPads Pattern Bank B (Trap / Hip-Hop / R&B / Pop).
 *
 * Trap · Hip-Hop tab uses proven hand-tuned grids from the Street / Signature Trap
 * series (Metro, ATL, TM88, Zay pockets) — not algorithmic stutter rolls.
 *
 * Row layout: 0=Kick  1=Snare  2=Clap  3=Hi-Hat  4=Open Hat  5=TomHi  6=808  7=Rim/Perc
 */

import type { PatternPreset } from '@/app/lib/patternPresets';
import {
  trapAtlMemphisBounce,
  trapBackbeatStack,
  trapCoreClassic,
  trapCoreFinisher,
  trapCoreMetro,
  trapCoreSouth,
  trapHatsEightThenRoll,
  trapHatsRollEnd,
  trapHatsSteadyThenRoll,
  trapHatsTwoStep,
  trapKickBarRush,
  trapOh24,
  trapSnare24,
  trapSnareBarPush,
} from '@/app/lib/creationStation/beatLabTrapPatternGrid';
import {
  platinumPopBar,
  platinumPopHatStack,
  platinumPopKickBarA,
  platinumPopKickBarB,
  platinumPopPercPush,
  platinumRnbClosedHats,
  platinumRnbKickPocket,
  platinumRnbClapBeat3,
  platinumRnbOpenHatBreath,
  platinumRnbSnareGhost,
  platinumRnbTrapsoulBar,
} from '@/app/lib/creationStation/beatLabPlatinumUrbanEngine';

const R = 8;
const S = 16;

function grid(hits: ReadonlyArray<[number, number]>): boolean[][] {
  const g: boolean[][] = Array.from({ length: R }, () => new Array<boolean>(S).fill(false));
  for (const [row, step] of hits) {
    if (row >= 0 && row < R && step >= 0 && step < S) g[row]![step] = true;
  }
  return g;
}

export function isBeatLabPlatinumUrbanPattern(presetId: string): boolean {
  return presetId.startsWith('platinum-');
}

export const BEAT_LAB_PLATINUM_URBAN_PATTERNS: readonly PatternPreset[] = [
  // ── Trap · Hip-Hop (pro hand-tuned — Street / Signature Trap pockets) ───────
  {
    id: 'platinum-trap-metro-bounce',
    name: 'Metro · Bounce',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Current Metro pocket — sync kick 1/&2/3/&4, snap snare+clap 2 & 4, steady→roll hats',
    pattern: grid(trapCoreMetro()),
  },
  {
    id: 'platinum-trap-chrome-atl',
    name: 'Chrome · ATL',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 142,
    desc: 'ATL club bounce — metro kick, hard 2 & 4, 8ths→roll, open hat lift on &4',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-redd-block',
    name: 'Redd · Block Stomp',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Redd Block / Memphis stomp — kick bar rush, snap 2 & 4, 8ths→roll, rim grit',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 11],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      [4, 10], [4, 14],
      [7, 2], [7, 6], [7, 10], [7, 14],
    ]),
  },
  {
    id: 'platinum-trap-phantom-roll',
    name: 'Phantom · Roll',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Drop finisher — sync into 3, kick bar rush, snap 2 & 4 + push, steady→burst hats',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 11],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      [1, 15],
      ...trapHatsSteadyThenRoll(),
      [4, 10], [4, 14],
    ]),
  },
  {
    id: 'platinum-trap-vault-mirage',
    name: 'Vault · Mirage',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 147,
    desc: 'Pink Vault ATL — sync into 3 + bar rush, snare pocket 2 & 4, 8ths→roll, block perc',
    pattern: grid([
      ...trapAtlMemphisBounce(),
      [7, 3], [7, 11],
    ]),
  },
  {
    id: 'platinum-trap-southside',
    name: 'Southside · Stack',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Southern bounce — sync kick phrase, triplet hat fill, rim push, 808 follows kick',
    pattern: grid(trapCoreSouth()),
  },
  {
    id: 'platinum-trap-tm88-haze',
    name: 'TM88 · Night Haze',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 146,
    desc: 'TM88 night pocket — sync kick, snap 2 & 4 + bar double, steady→roll, breathed OH',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapSnare24(),
      ...trapSnareBarPush(),
      [1, 15],
      ...trapHatsSteadyThenRoll(),
      [4, 7], [4, 15],
      [7, 5], [7, 13],
    ]),
  },
  {
    id: 'platinum-trap-zay-slide',
    name: 'Zay · Tunnel Slide',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 74,
    desc: 'Zay 808 Mafia tunnel @ felt 74 — metro kick + slide pickup, snare+clap 2 & 4, two-step→roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 11], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      [4, 14],
    ]),
  },
  {
    id: 'platinum-trap-bell-stack',
    name: 'Bell Trap · Stack',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Bell bounce club — metro kick, snare+clap stacked 2 & 4, two-step hats → bar-end roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      [4, 14],
    ]),
  },
  {
    id: 'platinum-trap-trunk-pressure',
    name: 'Trunk · SK Pressure',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Trunk 808 pressure — sync kicks + bar rush, snap 2 & 4, hat burst, 808 locked to kick',
    pattern: grid([
      [0, 0], [0, 8], [0, 10], [0, 11],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      [4, 6], [4, 14],
      [6, 0], [6, 8], [6, 11], [6, 14],
    ]),
  },
  {
    id: 'platinum-trap-classic-pocket',
    name: 'Cyborg · Classic',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Canonical trap — sparse kick, snap 2 & 4, 8ths→roll hats, OH on &s, 808 on 1 & 3',
    pattern: grid(trapCoreClassic()),
  },
  {
    id: 'platinum-trap-hat-finisher',
    name: 'Hat Roll · Finisher',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 150,
    desc: 'Drop finisher — lean kick + bar rush, dense hat burst, open lift, 808 tail',
    pattern: grid(trapCoreFinisher()),
  },

  // ── Modern R&B / Trapsoul (80–100 BPM) ────────────────────────────────────
  {
    id: 'platinum-rnb-trapsoul-night',
    name: 'Trapsoul · Night',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 88,
    desc: 'Beat-3 snare + ghost rim after beat 4, open hat &1/&3, laid-back kick',
    pattern: grid(platinumRnbTrapsoulBar(false)),
  },
  {
    id: 'platinum-rnb-ghost-bounce',
    name: 'Ghost Bounce · Trapsoul',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 92,
    desc: 'Mandatory soft rim ghost on & after 4 — clap stack beat 3, OH choke pocket',
    pattern: grid([
      ...platinumRnbKickPocket(),
      ...platinumRnbSnareGhost(),
      [2, 8],
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
      [6, 0],
      [6, 10],
      [7, 13],
    ]),
  },
  {
    id: 'platinum-rnb-space-breath',
    name: 'Space · Breath',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 86,
    desc: 'Sparse pocket — minimal kick on beat 3 pickup, ghost rim, breathed hats',
    pattern: grid([
      [0, 10], [0, 14],
      ...platinumRnbSnareGhost(),
      [2, 8],
      [3, 4], [3, 8], [3, 12],
      ...platinumRnbOpenHatBreath(),
      [6, 0], [6, 10],
    ]),
  },
  {
    id: 'platinum-rnb-velvet-late',
    name: 'Velvet · Late Night',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 90,
    desc: 'Sparse 40% pocket — minimal kick, open hat breathing, soft ghost stack',
    pattern: grid([
      [0, 0],
      [0, 14],
      ...platinumRnbSnareGhost(),
      [2, 8],
      [3, 4],
      [3, 8],
      [3, 12],
      ...platinumRnbOpenHatBreath(),
      [6, 0],
      [7, 2],
      [7, 10],
    ]),
  },
  {
    id: 'platinum-rnb-silk-groove',
    name: 'Silk Groove · R&B',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 96,
    desc: 'Full trapsoul — behind-grid kick, beat-3 snare, OH &1/&3, shaker air',
    pattern: grid([
      [0, 0],
      [0, 7],
      [0, 11],
      ...platinumRnbSnareGhost(),
      ...platinumRnbClapBeat3(),
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
      [6, 0],
      [6, 14],
      [7, 0],
      [7, 8],
    ]),
  },

  // ── Modern Pop / Radio (100–120 BPM) ──────────────────────────────────────
  {
    id: 'platinum-pop-sync-bar-a',
    name: 'Pop Sync · Bar A',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 110,
    desc: 'Afrobeats-adjacent kick — beat 1 + & of 2, perc pushed 5–12 ticks early',
    pattern: grid(platinumPopBar('A')),
  },
  {
    id: 'platinum-pop-sync-bar-b',
    name: 'Pop Sync · Bar B',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 110,
    desc: 'Alternating pop pocket — beat 1, 3, & of 4 + micro-timing percussion',
    pattern: grid(platinumPopBar('B')),
  },
  {
    id: 'platinum-pop-radio-drive',
    name: 'Radio Drive · Pop',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 115,
    desc: 'Syncopated kick cycle A+B merge feel — stacked clap 2&4, driving shaker push',
    pattern: grid([
      ...platinumPopKickBarA(),
      ...platinumPopKickBarB(),
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      ...platinumPopHatStack(),
      ...platinumPopPercPush(),
      [4, 6],
    ]),
  },
  {
    id: 'platinum-pop-afro-pocket',
    name: 'Afro Pocket · Pop',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 108,
    desc: 'Reggaeton-adjacent sync kick, early percussion swing, open lift on &2',
    pattern: grid([
      [0, 0],
      [0, 6],
      [0, 8],
      [0, 14],
      [1, 4],
      [1, 12],
      [2, 4],
      [2, 12],
      ...platinumPopHatStack(),
      ...platinumPopPercPush(),
      [4, 6],
      [7, 3],
      [7, 11],
    ]),
  },

  // ── Trap · Hip-Hop solid pack (+15) — kick on 1 ───────────────────────────
  {
    id: 'platinum-trap-solid-thump',
    name: 'Solid · Thump',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Solid trap thump — kick on 1, trunk 1·3·&4, snare+clap 2&4, two-step→roll',
    pattern: grid([
      [0, 0], [0, 8], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-metro',
    name: 'Solid · Metro',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Solid metro — kick on 1, metro bounce, snap 2&4, steady→roll',
    pattern: grid(trapCoreMetro()),
  },
  {
    id: 'platinum-trap-solid-south',
    name: 'Solid · South',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 138,
    desc: 'Solid south — kick on 1, southern pocket, snap 2&4',
    pattern: grid(trapCoreSouth()),
  },
  {
    id: 'platinum-trap-solid-classic',
    name: 'Solid · Classic',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Solid classic — kick on 1, sparse trunk, snap 2&4, 8ths→roll',
    pattern: grid(trapCoreClassic()),
  },
  {
    id: 'platinum-trap-solid-chrome',
    name: 'Solid · Chrome',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 143,
    desc: 'Solid chrome ATL — kick on 1, metro kick, hard 2&4, 8ths→roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-block',
    name: 'Solid · Block',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Solid block stomp — kick on 1, bar rush, snap 2&4, rim grit',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 11],
      ...trapKickBarRush(),
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsEightThenRoll(),
      [4, 10], [4, 14],
      [7, 2], [7, 6], [7, 10], [7, 14],
    ]),
  },
  {
    id: 'platinum-trap-solid-roll',
    name: 'Solid · Roll',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Solid roll — kick on 1, trunk kick, snap 2&4, steady→roll hats',
    pattern: grid([
      [0, 0], [0, 8], [0, 14],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-push',
    name: 'Solid · Push',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 144,
    desc: 'Solid push — kick on 1, metro + bar-push snare, two-step→roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapSnare24(),
      ...trapSnareBarPush(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-trunk',
    name: 'Solid · Trunk',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 141,
    desc: 'Solid trunk — kick on 1, heavy 1·3·&4, snap+clap, 8ths→roll',
    pattern: grid([
      [0, 0], [0, 8], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsEightThenRoll(),
      [4, 14],
    ]),
  },
  {
    id: 'platinum-trap-solid-finisher',
    name: 'Solid · Finisher',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 148,
    desc: 'Solid finisher — kick on 1, drop pocket, hat burst',
    pattern: grid(trapCoreFinisher()),
  },
  {
    id: 'platinum-trap-solid-sync',
    name: 'Solid · Sync',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 143,
    desc: 'Solid sync — kick on 1, sync pocket, snare+clap 2&4, two-step→roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 11], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-slide',
    name: 'Solid · Slide',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 145,
    desc: 'Solid slide — kick on 1, slide phrase into 2&4, steady→roll',
    pattern: grid([
      [0, 0], [0, 3], [0, 8], [0, 11], [0, 13], [0, 14], [0, 15],
      ...trapSnare24(),
      ...trapHatsSteadyThenRoll(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-double',
    name: 'Solid · Double',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 142,
    desc: 'Solid double — kick on 1, open doubles into 3, snap 2&4, hats→roll',
    pattern: grid([
      [0, 0], [0, 2], [0, 8], [0, 10],
      ...trapBackbeatStack(),
      ...trapHatsSteadyThenRoll(),
      [4, 14],
    ]),
  },
  {
    id: 'platinum-trap-solid-club',
    name: 'Solid · Club',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 146,
    desc: 'Solid club — kick on 1, metro bounce, snap+clap, two-step→roll',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      ...trapBackbeatStack(),
      ...trapHatsTwoStep(),
      ...trapHatsRollEnd(),
      ...trapOh24(),
    ]),
  },
  {
    id: 'platinum-trap-solid-forever',
    name: 'Solid · Forever',
    genre: 'Platinum Trap',
    role: 'drums',
    bpm: 140,
    desc: 'Solid forever — kick on 1, classic pocket, snap 2&4, 8ths→roll',
    pattern: grid(trapCoreClassic()),
  },

  // ── R&B · Pop solid pack (+15) — kick on 1 ────────────────────────────────
  {
    id: 'platinum-rnb-solid-pocket',
    name: 'Solid · R&B Pocket',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 88,
    desc: 'Solid R&B — kick on 1, snare+clap 2&4, closed hats, OH breath',
    pattern: grid([
      ...platinumRnbKickPocket(),
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
    ]),
  },
  {
    id: 'platinum-rnb-solid-trapsoul',
    name: 'Solid · Trap Soul',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 94,
    desc: 'Solid trap-soul — kick on 1, trapsoul bar pocket',
    pattern: grid(platinumRnbTrapsoulBar()),
  },
  {
    id: 'platinum-rnb-solid-ghost',
    name: 'Solid · Ghost',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 86,
    desc: 'Solid ghost — kick on 1, snare + ghosts, closed hats',
    pattern: grid([
      ...platinumRnbKickPocket(),
      [1, 4], [1, 12],
      ...platinumRnbSnareGhost(),
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
    ]),
  },
  {
    id: 'platinum-rnb-solid-velvet',
    name: 'Solid · Velvet',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 84,
    desc: 'Solid velvet — kick on 1, soft 2&4, breath OH',
    pattern: grid([
      [0, 0], [0, 7], [0, 10], [0, 14],
      [1, 4], [1, 12],
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
    ]),
  },
  {
    id: 'platinum-rnb-solid-silk',
    name: 'Solid · Silk',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 90,
    desc: 'Solid silk — kick on 1, clap on 3 option + 2&4, closed hats',
    pattern: grid([
      [0, 0], [0, 10], [0, 14],
      [1, 4], [1, 12],
      ...platinumRnbClapBeat3(),
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
    ]),
  },
  {
    id: 'platinum-rnb-solid-night',
    name: 'Solid · Night',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 82,
    desc: 'Solid night — kick on 1, late pocket, snare 2&4, soft hats',
    pattern: grid([
      [0, 0], [0, 7], [0, 12], [0, 14],
      [1, 4], [1, 12],
      [3, 2], [3, 6], [3, 10], [3, 14],
      [4, 14],
    ]),
  },
  {
    id: 'platinum-rnb-solid-space',
    name: 'Solid · Space',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 80,
    desc: 'Solid space — kick on 1, sparse snare 2&4, breath OH',
    pattern: grid([
      [0, 0], [0, 9], [0, 14],
      [1, 4], [1, 12],
      ...platinumRnbOpenHatBreath(),
      [3, 0], [3, 4], [3, 8], [3, 12],
    ]),
  },
  {
    id: 'platinum-rnb-solid-warm',
    name: 'Solid · Warm',
    genre: 'Platinum R&B',
    role: 'drums',
    bpm: 87,
    desc: 'Solid warm — kick on 1, snare+clap 2&4, closed hats',
    pattern: grid([
      [0, 0], [0, 6], [0, 11], [0, 14],
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumRnbClosedHats(),
      ...platinumRnbOpenHatBreath(),
    ]),
  },
  {
    id: 'platinum-pop-solid-sync-a',
    name: 'Solid · Pop Sync A',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 110,
    desc: 'Solid pop sync A — kick on 1, bar A pocket',
    pattern: grid(platinumPopBar('A')),
  },
  {
    id: 'platinum-pop-solid-sync-b',
    name: 'Solid · Pop Sync B',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 110,
    desc: 'Solid pop sync B — kick on 1, bar B pocket',
    pattern: grid(platinumPopBar('B')),
  },
  {
    id: 'platinum-pop-solid-radio',
    name: 'Solid · Radio',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 115,
    desc: 'Solid radio — kick on 1, sync A+B, clap 2&4, hat stack',
    pattern: grid([
      ...platinumPopKickBarA(),
      ...platinumPopKickBarB(),
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumPopHatStack(),
      ...platinumPopPercPush(),
      [4, 6],
    ]),
  },
  {
    id: 'platinum-pop-solid-afro',
    name: 'Solid · Afro Pop',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 108,
    desc: 'Solid afro pop — kick on 1, sync pocket, clap 2&4, perc push',
    pattern: grid([
      [0, 0], [0, 6], [0, 8], [0, 14],
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumPopHatStack(),
      ...platinumPopPercPush(),
      [4, 6],
      [7, 3], [7, 11],
    ]),
  },
  {
    id: 'platinum-pop-solid-drive',
    name: 'Solid · Pop Drive',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 112,
    desc: 'Solid pop drive — kick on 1, four lite + sync, snare+clap, hats',
    pattern: grid([
      [0, 0], [0, 4], [0, 8], [0, 12], [0, 14],
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumPopHatStack(),
      [4, 6], [4, 14],
    ]),
  },
  {
    id: 'platinum-pop-solid-chart',
    name: 'Solid · Chart',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 116,
    desc: 'Solid chart — kick on 1, sync push, clap 2&4, hat stack + perc',
    pattern: grid([
      [0, 0], [0, 6], [0, 10], [0, 14],
      [1, 4], [1, 12],
      [2, 4], [2, 12],
      ...platinumPopHatStack(),
      ...platinumPopPercPush(),
      [4, 14],
    ]),
  },
  {
    id: 'platinum-pop-solid-forever',
    name: 'Solid · Forever Pop',
    genre: 'Platinum Pop',
    role: 'drums',
    bpm: 110,
    desc: 'Solid forever pop — kick on 1, bar A feel, clap 2&4',
    pattern: grid(platinumPopBar('A')),
  },
];
