/**
 * Beat Pads Lane Placements — Techno pack.
 * 20 each: kick · snare · clap · hihat · openHat · rim (one-lane 16th patterns).
 */
import type {
  BeatPadsDrumRole,
  BeatPadsLanePlacementTemplate,
  BeatPadsPlacementGenre,
} from '@/app/lib/creationStation/beatPadsLanePlacementTemplates';

function bar(...steps: number[]): readonly number[] {
  return steps;
}

function tpl(
  id: string,
  name: string,
  role: BeatPadsDrumRole,
  genre: BeatPadsPlacementGenre,
  desc: string,
  steps: readonly number[],
): BeatPadsLanePlacementTemplate {
  return { id, name, role, genre, desc, steps };
}

/** @internal Merged into ALL_TEMPLATES. */
export const BEAT_PADS_TECHNO_LANE_TEMPLATES: readonly BeatPadsLanePlacementTemplate[] = [
  // ── TECHNO KICK (20) ──
  tpl('techno-kick-four-floor', 'Four on the Floor', 'kick', 'techno', 'Classic pounding quarter-note floor', bar(0, 4, 8, 12)),
  tpl('techno-kick-floor-pickup', 'Floor + Pickup', 'kick', 'techno', 'Four floor with bar-end double pickup', bar(0, 4, 8, 12, 14, 15)),
  tpl('techno-kick-warehouse', 'Warehouse Pulse', 'kick', 'techno', 'Floor kick + extra hit on & of 1', bar(0, 2, 4, 8, 12)),
  tpl('techno-kick-berlin-swing', 'Berlin Swing', 'kick', 'techno', 'Floor kick + push on & of 2', bar(0, 4, 6, 8, 12)),
  tpl('techno-kick-driving-off3', 'Driving Off-3', 'kick', 'techno', 'Floor kick + extra hit on & of 3', bar(0, 4, 8, 10, 12)),
  tpl('techno-kick-minimal-two', 'Minimal Two', 'kick', 'techno', 'Stripped-back 1 and 3 only', bar(0, 8)),
  tpl('techno-kick-minimal-three', 'Minimal Three', 'kick', 'techno', 'Sparse 1 · 2 · 3 — no beat 4', bar(0, 4, 8)),
  tpl('techno-kick-acid-pulse', 'Acid Pulse', 'kick', 'techno', 'Floor kick + acid-line push before beat 3', bar(0, 4, 8, 9, 12)),
  tpl('techno-kick-detroit-roll', 'Detroit Roll', 'kick', 'techno', 'Floor kick + Detroit-style roll before beat 3', bar(0, 4, 7, 8, 12)),
  tpl('techno-kick-dub-lean', 'Dub Techno Lean', 'kick', 'techno', 'Floor kick + late lean before beat 3', bar(0, 4, 5, 8, 12)),
  tpl('techno-kick-industrial-stomp', 'Industrial Stomp', 'kick', 'techno', 'Floor kick + hard stomp right after 1', bar(0, 1, 4, 8, 12)),
  tpl('techno-kick-hard-drive-roll', 'Hard Drive Roll', 'kick', 'techno', 'Floor kick with relentless bar-end roll', bar(0, 4, 8, 12, 13, 14, 15)),
  tpl('techno-kick-off-push', 'Off-Kick Push', 'kick', 'techno', 'Floor kick + pickup push before beat 2', bar(0, 3, 4, 8, 12)),
  tpl('techno-kick-double-four', 'Double Four', 'kick', 'techno', 'Floor kick with doubled bar-end hit', bar(0, 4, 8, 12, 15)),
  tpl('techno-kick-rolling-8ths', 'Rolling 8ths', 'kick', 'techno', 'Relentless eighth-note kick roll', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('techno-kick-peak-time', 'Peak Time', 'kick', 'techno', 'Floor kick + push right before beat 4', bar(0, 4, 8, 11, 12)),
  tpl('techno-kick-rolling-offbeat', 'Rolling Offbeat', 'kick', 'techno', 'Floor kick + every & of the bar', bar(0, 3, 4, 7, 8, 11, 12, 15)),
  tpl('techno-kick-no-one-loop', 'No-One Loop', 'kick', 'techno', 'Downbeat dropped — kicks on 2 · 3 · 4 only', bar(4, 8, 12)),
  tpl('techno-kick-ghost-pair', 'Ghost Pair', 'kick', 'techno', 'Floor kick + ghost hits after 1 and 3', bar(0, 1, 4, 8, 9, 12)),
  tpl('techno-kick-half-warehouse', 'Half Warehouse', 'kick', 'techno', 'Floor kick + single accent on & of 2', bar(0, 6, 8, 12)),

  // ── TECHNO SNARE (20) ──
  tpl('techno-snare-beat3-only', 'Beat 3 Only', 'snare', 'techno', 'Single sparse hit on beat 3', bar(8)),
  tpl('techno-snare-24-minimal', '2 & 4 Minimal', 'snare', 'techno', 'Minimal-techno backbeat', bar(4, 12)),
  tpl('techno-snare-beat4-only', 'Beat 4 Only', 'snare', 'techno', 'Single sparse hit on beat 4', bar(12)),
  tpl('techno-snare-off24', 'Offbeat 2 & 4', 'snare', 'techno', 'Snare shifted to the & of 2 and & of 4', bar(6, 14)),
  tpl('techno-snare-late3', 'Late 3', 'snare', 'techno', 'Snare sits behind beat 3', bar(10)),
  tpl('techno-snare-beat2-only', 'Beat 2 Only', 'snare', 'techno', 'Single sparse hit on beat 2', bar(4)),
  tpl('techno-snare-off13', 'Off 1 & 3', 'snare', 'techno', 'Snare on the & of 1 and & of 3', bar(2, 10)),
  tpl('techno-snare-3-tail', '3 + Tail', 'snare', 'techno', 'Beat 3 hit plus a late bar tail', bar(8, 14)),
  tpl('techno-snare-double4', 'Double 4', 'snare', 'techno', 'Beat 4 doubled for extra punch', bar(12, 14)),
  tpl('techno-snare-2-late3', '2 + Late 3', 'snare', 'techno', 'Beat 2 plus a late push into 3', bar(4, 10)),
  tpl('techno-snare-13-accent', '1 & 3 Accent', 'snare', 'techno', 'Unusual accent locked to the kick', bar(0, 8)),
  tpl('techno-snare-tail-only', 'Tail Only', 'snare', 'techno', 'Single ghost hit at the bar tail', bar(14)),
  tpl('techno-snare-off2-only', 'Off 2 Only', 'snare', 'techno', 'Single hit on the & of 2', bar(6)),
  tpl('techno-snare-24-tail', '2 & 4 + Tail', 'snare', 'techno', 'Backbeat plus a late-bar ghost', bar(4, 12, 14)),
  tpl('techno-snare-off1-only', 'Off 1 Only', 'snare', 'techno', 'Single hit on the & of 1', bar(2)),
  tpl('techno-snare-34-industrial', '3 & 4 Industrial', 'snare', 'techno', 'Heavier industrial pairing on 3 and 4', bar(8, 12)),
  tpl('techno-snare-late24', 'Late 2 & 4', 'snare', 'techno', 'Backbeat sitting slightly behind the grid', bar(5, 13)),
  tpl('techno-snare-ghost-sync', 'Ghost Sync', 'snare', 'techno', 'Single syncopated ghost before beat 3', bar(9)),
  tpl('techno-snare-bar-end-duo', 'Bar End Duo', 'snare', 'techno', 'Two ghost hits closing out the bar', bar(13, 15)),
  tpl('techno-snare-industrial-pound', 'Industrial Pound', 'snare', 'techno', 'Snare pounding on every quarter note', bar(0, 4, 8, 12)),

  // ── TECHNO CLAP (20) ──
  tpl('techno-clap-24-classic', 'Classic 2 & 4', 'clap', 'techno', 'Standard techno clap backbeat', bar(4, 12)),
  tpl('techno-clap-beat4-only', 'Beat 4 Only', 'clap', 'techno', 'Sparse single clap on beat 4', bar(12)),
  tpl('techno-clap-off24', 'Offbeat Clap', 'clap', 'techno', 'Clap shifted to & of 2 and & of 4', bar(6, 14)),
  tpl('techno-clap-beat2-only', 'Beat 2 Only', 'clap', 'techno', 'Sparse single clap on beat 2', bar(4)),
  tpl('techno-clap-beat3-only', 'Beat 3 Only', 'clap', 'techno', 'Sparse single clap on beat 3', bar(8)),
  tpl('techno-clap-tail-only', 'Tail Clap', 'clap', 'techno', 'Single ghost clap at the bar tail', bar(14)),
  tpl('techno-clap-off13', 'Off 1 & 3', 'clap', 'techno', 'Clap on the & of 1 and & of 3', bar(2, 10)),
  tpl('techno-clap-wide-stack', 'Wide Stack', 'clap', 'techno', 'Layered clap width on the backbeat', bar(4, 5, 12, 13)),
  tpl('techno-clap-double-tap', 'Double Tap', 'clap', 'techno', 'Beat 4 clap doubled', bar(12, 13)),
  tpl('techno-clap-late3', 'Late 3', 'clap', 'techno', 'Single clap sitting behind beat 3', bar(10)),
  tpl('techno-clap-off2-only', 'Off 2 Only', 'clap', 'techno', 'Single clap on the & of 2', bar(6)),
  tpl('techno-clap-pound-13', 'Pound 1 & 3', 'clap', 'techno', 'Unusual clap locked to the kick', bar(0, 8)),
  tpl('techno-clap-triangulated', 'Triangulated', 'clap', 'techno', 'Clap on 2, mid-bar, and 4', bar(4, 10, 12)),
  tpl('techno-clap-ghost-tail', 'Ghost Tail', 'clap', 'techno', 'Single ghost clap just before the bar line', bar(13)),
  tpl('techno-clap-off1-only', 'Off 1 Only', 'clap', 'techno', 'Single clap on the & of 1', bar(2)),
  tpl('techno-clap-24-pickup', '2 & 4 + Pickup', 'clap', 'techno', 'Backbeat plus a bar-end pickup', bar(4, 12, 15)),
  tpl('techno-clap-sync-duo', 'Sync Duo', 'clap', 'techno', 'Two syncopated hits mid-to-late bar', bar(9, 13)),
  tpl('techno-clap-industrial-pound', 'Industrial Pound', 'clap', 'techno', 'Clap pounding on every quarter note', bar(0, 4, 8, 12)),
  tpl('techno-clap-late-pair', 'Late Pair', 'clap', 'techno', 'Backbeat sitting slightly behind the grid', bar(5, 13)),
  tpl('techno-clap-pickup-only', 'Pickup Only', 'clap', 'techno', 'Single clap right at the bar-end pickup', bar(15)),

  // ── TECHNO HI-HAT (20) ──
  tpl('techno-hat-straight-8ths', 'Straight 8ths', 'hihat', 'techno', 'Steady closed eighth-note hats', bar(0, 2, 4, 6, 8, 10, 12, 14)),
  tpl('techno-hat-offbeat-8ths', 'Offbeat 8ths', 'hihat', 'techno', 'Classic techno offbeat "chick" hats', bar(2, 6, 10, 14)),
  tpl('techno-hat-machine-16', 'Machine 16ths', 'hihat', 'techno', 'Full relentless sixteenth-note machine roll', bar(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)),
  tpl('techno-hat-upbeat-16', 'Upbeat 16ths', 'hihat', 'techno', 'Hats on every off-sixteenth', bar(1, 3, 5, 7, 9, 11, 13, 15)),
  tpl('techno-hat-quarter-march', 'Quarter March', 'hihat', 'techno', 'Marching quarter-note hats', bar(0, 4, 8, 12)),
  tpl('techno-hat-driving-skip', 'Driving Skip', 'hihat', 'techno', 'Skipping pattern that drives the groove', bar(2, 4, 6, 10, 12, 14)),
  tpl('techno-hat-dense-push', 'Dense Push', 'hihat', 'techno', 'Dense offbeat hats with extra pushes', bar(0, 2, 4, 6, 8, 9, 10, 12, 14)),
  tpl('techno-hat-off16-only', 'Off-16th Only', 'hihat', 'techno', 'Sparse hats on the final sixteenth of each beat', bar(3, 7, 11, 15)),
  tpl('techno-hat-warehouse-chug', 'Warehouse Chug', 'hihat', 'techno', 'Chugging warehouse hat pattern', bar(2, 6, 8, 10, 14)),
  tpl('techno-hat-syncopated-march', 'Syncopated March', 'hihat', 'techno', 'Syncopated marching hat pattern', bar(0, 2, 3, 6, 7, 10, 11, 14, 15)),
  tpl('techno-hat-second-half-drive', 'Second-Half Drive', 'hihat', 'techno', 'Driving hats through the back half of the bar', bar(4, 6, 8, 10, 12, 14)),
  tpl('techno-hat-build-roll', 'Build Roll', 'hihat', 'techno', 'Dense roll building into the bar line', bar(0, 2, 4, 6, 8, 10, 12, 13, 14, 15)),
  tpl('techno-hat-minimal-two', 'Minimal Two', 'hihat', 'techno', 'Two sparse hat hits per bar', bar(2, 10)),
  tpl('techno-hat-minimal-off', 'Minimal Off', 'hihat', 'techno', 'Two sparse offbeat hits', bar(6, 14)),
  tpl('techno-hat-perc-march', 'Perc March', 'hihat', 'techno', 'Percussive marching hat pattern', bar(0, 3, 4, 7, 8, 11, 12, 15)),
  tpl('techno-hat-off-quarter-ticks', 'Off-Quarter Ticks', 'hihat', 'techno', 'Ticking hats between the beats', bar(1, 5, 9, 13)),
  tpl('techno-hat-chug-tail', 'Chug + Tail', 'hihat', 'techno', 'Offbeat chug with a bar-end tail hit', bar(2, 4, 6, 8, 10, 12, 14, 15)),
  tpl('techno-hat-acid-drive', 'Acid Drive', 'hihat', 'techno', 'Driving acid-line hat pattern', bar(0, 2, 4, 5, 6, 8, 10, 12, 14)),
  tpl('techno-hat-peak-drive', 'Peak Drive', 'hihat', 'techno', 'High-energy peak-time hat pattern', bar(2, 6, 8, 9, 10, 14)),
  tpl('techno-hat-industrial-relentless', 'Industrial Relentless', 'hihat', 'techno', 'Dense industrial pattern skipping the downbeat', bar(1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15)),

  // ── TECHNO OPEN HAT (20) ──
  tpl('techno-oh-classic-off', 'Classic Off OH', 'openHat', 'techno', 'Open hat on the & of every beat', bar(2, 6, 10, 14)),
  tpl('techno-oh-24', 'OH 2 & 4', 'openHat', 'techno', 'Open hat on & of 2 and & of 4', bar(6, 14)),
  tpl('techno-oh-tail-lift', 'Tail Lift', 'openHat', 'techno', 'Single open hat lift at the bar tail', bar(14)),
  tpl('techno-oh-off1-only', 'Off 1 Only', 'openHat', 'techno', 'Single open hat on the & of 1', bar(2)),
  tpl('techno-oh-off2-only', 'Off 2 Only', 'openHat', 'techno', 'Single open hat on the & of 2', bar(6)),
  tpl('techno-oh-off3-only', 'Off 3 Only', 'openHat', 'techno', 'Single open hat on the & of 3', bar(10)),
  tpl('techno-oh-off13', 'Off 1 & 3', 'openHat', 'techno', 'Open hat on & of 1 and & of 3', bar(2, 10)),
  tpl('techno-oh-triple-no4', 'Triple (no 4)', 'openHat', 'techno', 'Open hat on every & except beat 4', bar(2, 6, 10)),
  tpl('techno-oh-triple-no1', 'Triple (no 1)', 'openHat', 'techno', 'Open hat on every & except beat 1', bar(6, 10, 14)),
  tpl('techno-oh-tribal-duo', 'Tribal Duo', 'openHat', 'techno', 'Two open hits closing the bar', bar(13, 15)),
  tpl('techno-oh-sync-open', 'Sync Open', 'openHat', 'techno', 'Syncopated open hat pair', bar(1, 9)),
  tpl('techno-oh-off-triplet', 'Off Triplet Feel', 'openHat', 'techno', 'Triplet-leaning open hat pair', bar(3, 11)),
  tpl('techno-oh-tribal-wide', 'Tribal Wide', 'openHat', 'techno', 'Wide tribal open pattern with a bar-tail lean', bar(2, 6, 10, 13, 14)),
  tpl('techno-oh-late-duo', 'Late Duo', 'openHat', 'techno', 'Two late open hits per bar', bar(7, 15)),
  tpl('techno-oh-downbeat-open', 'Downbeat Open', 'openHat', 'techno', 'Unusual open hat on the downbeats', bar(0, 8)),
  tpl('techno-oh-beat-open', 'Beat Open', 'openHat', 'techno', 'Open hat locked to beats 2 and 4', bar(4, 12)),
  tpl('techno-oh-dense-tribal', 'Dense Tribal', 'openHat', 'techno', 'Dense tribal open hat groove', bar(2, 4, 6, 10, 12, 14)),
  tpl('techno-oh-bar-end-duo', 'Bar-End Duo', 'openHat', 'techno', 'Open hats closing out the very end of the bar', bar(14, 15)),
  tpl('techno-oh-off-sync', 'Off Sync', 'openHat', 'techno', 'Syncopated open hat pair sitting late', bar(5, 13)),
  tpl('techno-oh-tribal-push', 'Tribal Push', 'openHat', 'techno', 'Tribal open hat groove with a push before beat 3', bar(2, 6, 9, 10, 14)),

  // ── TECHNO RIM / PERC (20) ──
  tpl('techno-rim-off16-ticks', 'Off-16th Ticks', 'rim', 'techno', 'Percussive ticks on the final sixteenth of each beat', bar(3, 7, 11, 15)),
  tpl('techno-rim-off-quarter-ticks', 'Off-Quarter Ticks', 'rim', 'techno', 'Percussive ticks between the beats', bar(1, 5, 9, 13)),
  tpl('techno-rim-24', 'Perc 2 & 4', 'rim', 'techno', 'Rim perc locked to the backbeat', bar(6, 14)),
  tpl('techno-rim-13', 'Perc 1 & 3', 'rim', 'techno', 'Rim perc on the & of 1 and & of 3', bar(2, 10)),
  tpl('techno-rim-downbeat', 'Downbeat Perc', 'rim', 'techno', 'Rim perc locked to the kick downbeats', bar(0, 8)),
  tpl('techno-rim-duo', 'Perc Duo', 'rim', 'techno', 'Two percussive ticks per bar', bar(3, 11)),
  tpl('techno-rim-late-duo', 'Late Duo', 'rim', 'techno', 'Two late percussive ticks per bar', bar(7, 15)),
  tpl('techno-rim-sync-pair', 'Sync Pair', 'rim', 'techno', 'Syncopated percussive pair', bar(1, 9)),
  tpl('techno-rim-off-pair', 'Off Pair', 'rim', 'techno', 'Offbeat percussive pair sitting late', bar(5, 13)),
  tpl('techno-rim-steady', 'Steady Perc', 'rim', 'techno', 'Steady percussive ticks on every offbeat', bar(2, 6, 10, 14)),
  tpl('techno-rim-beat-perc', 'Beat Perc', 'rim', 'techno', 'Percussive ticks on beats 2 and 4', bar(4, 12)),
  tpl('techno-rim-pulse-perc', 'Pulse Perc', 'rim', 'techno', 'Percussive pulse on every quarter note', bar(0, 4, 8, 12)),
  tpl('techno-rim-ghost-perc', 'Ghost Perc', 'rim', 'techno', 'Two syncopated ghost ticks late in the bar', bar(9, 13)),
  tpl('techno-rim-flam', 'Flam Perc', 'rim', 'techno', 'Flammed percussive hits around 1 and 3', bar(2, 3, 10, 11)),
  tpl('techno-rim-flam-tail', 'Flam Tail', 'rim', 'techno', 'Flammed percussive hits around 2 and 4', bar(6, 7, 14, 15)),
  tpl('techno-rim-skip', 'Skip Perc', 'rim', 'techno', 'Skipping percussive pattern in the front half', bar(1, 3, 9, 11)),
  tpl('techno-rim-skip-tail', 'Skip Tail', 'rim', 'techno', 'Skipping percussive pattern in the back half', bar(5, 7, 13, 15)),
  tpl('techno-rim-triplet', 'Triplet Perc', 'rim', 'techno', 'Triplet-feel percussive pattern across the bar', bar(0, 3, 6, 9, 12, 15)),
  tpl('techno-rim-loose', 'Loose Perc', 'rim', 'techno', 'Loosely syncopated percussive pattern', bar(2, 5, 10, 13)),
  tpl('techno-rim-single-tick', 'Single Tick', 'rim', 'techno', 'One percussive tick at the bar tail', bar(14)),
];
