/**
 * Auto Drum phrase library — genre profiles + instruction rules.
 * Grows independently from matcher/scoring in beatPadsAutoDrum.ts.
 */
import type { BeatPadsDrumRole, BeatPadsPlacementGenre } from '@/app/lib/creationStation/beatPadsLanePlacementTemplates';

export type AutoDrumGenreProfile = {
  genre: BeatPadsPlacementGenre;
  strong: readonly string[];
  medium: readonly string[];
  weak: readonly string[];
};

export type AutoDrumInstructionRule = {
  roles: readonly BeatPadsDrumRole[];
  genres?: readonly BeatPadsPlacementGenre[];
  anyOf: readonly string[];
  allOf?: readonly string[];
  idBoosts?: readonly string[];
  pickByGenre?: Partial<Record<BeatPadsPlacementGenre, string>>;
  pickId?: string;
  label: string;
};

export const KICK_808_TOKENS = [
  '808',
  'eight o eight',
  'eight oh eight',
  'eight zero eight',
] as const;

export const ROLE_ALIASES: readonly { role: BeatPadsDrumRole; tokens: readonly string[] }[] = [
  { role: 'kick', tokens: ['kick', 'kicks', 'bass drum', 'bassdrum', 'bd', 'bass', 'trunk', 'sub', 'woofer', 'boom', 'stomp', 'low end', 'lowend'] },
  { role: 'snare', tokens: ['snare', 'snares', 'backbeat', 'crack', 'rimshot', 'slap'] },
  { role: 'clap', tokens: ['clap', 'claps', 'handclap', 'hand clap'] },
  { role: 'hihat', tokens: ['hat', 'hats', 'hihat', 'hi-hat', 'hi hat', 'hh', 'closed hat', 'closed', 'cymbal', 'tick', 'ticking', 'chick'] },
  { role: 'openHat', tokens: ['open', 'openhat', 'open hat', 'oh', 'splash', 'sizzle'] },
  { role: 'rim', tokens: ['rim', 'perc', 'percussion', 'shaker', 'groove', 'tamb', 'tambourine', 'conga', 'cowbell'] },
];

export const GENRE_PROFILES: readonly AutoDrumGenreProfile[] = [
  {
    genre: 'trap',
    strong: ['trap', 'drill', 'metro', 'trunk', 'atlanta', 'atl', 'memphis', 'phonk', 'plugg'],
    medium: ['south', 'lex', 'sync pocket', 'half time', 'halftime', '808', 'dark', 'slime', 'rage'],
    weak: ['bounce', 'lean', 'slide', 'sparse', 'hard', 'heavy'],
  },
  {
    genre: 'dance',
    strong: ['dance', 'edm', 'festival', 'mainstage', 'bigroom', 'big room', 'anthem', 'rave', 'club banger'],
    medium: ['drop', 'build up', 'pre drop', 'energy', 'main stage', 'brostep', 'electro'],
    weak: ['build', 'lift', 'roll', 'peak'],
  },
  {
    genre: 'house',
    strong: ['house', 'chicago', 'deep house', 'garage', 'techno', 'tech house', 'deep'],
    medium: ['four on the floor', 'fouronthefloor', 'four floor', 'driving', 'warehouse', 'jack'],
    weak: ['clap', 'rim', 'punch', 'groove'],
  },
  {
    genre: 'rnb',
    strong: ['rnb', 'r and b', 'r&b', 'soul', 'neo soul', 'neo', 'slow jam', 'bedroom'],
    medium: ['velvet', 'silk', 'shuffle', 'laid back', 'laidback', 'smooth', 'intimate'],
    weak: ['soft', 'brush', 'night', 'warm', 'mellow'],
  },
  {
    genre: 'pop',
    strong: ['pop', 'radio', 'top40', 'top 40', 'tiktok', 'billboard', 'mainstream'],
    medium: ['chorus', 'verse', 'ballad', 'latin pop', 'hook', 'radio edit'],
    weak: ['lift', 'bounce', 'driving', 'bright'],
  },
  {
    genre: 'kpop',
    strong: ['kpop', 'k-pop', 'k pop', 'korean', 'idol', 'k drama'],
    medium: ['chant', 'bright', 'hook', 'chorus', 'comeback', 'title track'],
    weak: ['stack', 'snap', 'verse', 'cute'],
  },
  {
    genre: 'soulBlues',
    strong: ['soul blues', 'southern soul', 'southern blues', 'soul-blues', 'memphis soul', 'blues rock'],
    medium: ['blues', 'shuffle', 'gospel soul', 'southern', 'swamp', 'delta', 'chitlin'],
    weak: ['brush', 'swung', 'slow', 'walk', 'gritty'],
  },
  {
    genre: 'afro',
    strong: ['afro', 'afrobeats', 'afropop', 'naija', 'amapiano', 'afrobeat', 'afroswing'],
    medium: ['lagos', 'highlife', 'dembow', 'shaku', 'wizkid', 'burna', 'log drum', 'piano'],
    weak: ['bounce', 'skitter', 'makosa', 'gbedu'],
  },
  {
    genre: 'reggae',
    strong: ['reggae', 'dub', 'dancehall', 'rocksteady', 'ska', 'roots', 'ragga'],
    medium: ['one drop', 'onedrop', 'steppers', 'island', 'rub a dub', 'rub-a-dub', 'riddim'],
    weak: ['offbeat', 'skank', 'rockers', 'lazy'],
  },
  {
    genre: 'lofi',
    strong: ['lofi', 'lo-fi', 'lo fi', 'chill hop', 'chillhop', 'study beat', 'studybeat'],
    medium: ['dusty', 'vinyl', 'cassette', 'bedroom', 'jazzy hip hop', 'boom bap soft'],
    weak: ['chill', 'soft', 'lazy', 'mellow', 'warm', 'night'],
  },
] as const;

/** 2 & 4 backbeat + bar-end roll/fill — per genre. */
const SNARE_BACKBEAT_ROLL: Partial<Record<BeatPadsPlacementGenre, string>> = {
  trap: 'trap-snare-fill',
  rnb: 'rnb-snare-fill',
  pop: 'pop-snare-fill',
  house: 'house-snare-fill',
  dance: 'dance-snare-fill',
  kpop: 'kpop-snare-fill',
  soulBlues: 'soulblues-snare-fill',
  afro: 'afro-snare-fill',
  reggae: 'reggae-snare-fill',
  lofi: 'lofi-snare-fill',
};

export const INSTRUCTION_RULES: readonly AutoDrumInstructionRule[] = [
  {
    roles: ['kick'],
    genres: ['trap', 'rnb'],
    allOf: ['808', 'long'],
    anyOf: [...KICK_808_TOKENS, 'long', 'sustained', 'held', 'drawn', 'tail'],
    pickByGenre: { trap: 'trap-kick-808-min', rnb: 'rnb-kick-bloom' },
    label: '808 long kick',
  },
  {
    roles: ['kick'],
    genres: ['trap', 'rnb', 'afro'],
    anyOf: [...KICK_808_TOKENS, 'sub bass', 'subbass', 'woofer', 'trunk'],
    idBoosts: ['808', 'bloom', 'minimal', 'sparse', 'trunk', 'sub'],
    label: '808 kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['metro', 'bounce', 'ni', 'metro boomin', 'boomin'],
    pickId: 'trap-kick-metro',
    label: 'metro bounce',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['dirty south', 'dirtysouth', 'south', 'southern trap', 'atl', 'atlanta'],
    pickId: 'trap-kick-south',
    label: 'dirty south kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['lean', 'behind', 'late pocket', 'lay back', 'layback'],
    pickId: 'trap-kick-lean',
    label: 'lean back kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['sync', 'syncopated', 'pocket', 'triplet', 'swung trap'],
    idBoosts: ['sync', 'pocket', 'triplet', 'lean'],
    label: 'sync pocket kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['sparse', 'minimal', 'few hits', 'two hit', 'two-hit', 'simple'],
    idBoosts: ['sparse', 'minimal', 'two-hit'],
    pickId: 'trap-kick-minimal',
    label: 'sparse trap kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['half time', 'halftime', 'half-time', 'slow trap'],
    pickId: 'trap-kick-half',
    label: 'half-time kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['slide', 'glide', '808 slide'],
    pickId: 'trap-kick-slide',
    label: 'slide kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['rush', 'double', 'doubles', 'pickup', 'fill', 'bar end'],
    idBoosts: ['rush', 'double', 'pickup', 'drop'],
    label: 'bar rush kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['modern', '2020', 'new trap', 'current'],
    pickId: 'trap-kick-modern-138',
    label: 'modern trap kick',
  },
  {
    roles: ['kick'],
    genres: ['trap'],
    anyOf: ['memphis', 'redd', 'phonk kick'],
    pickId: 'trap-kick-atl-memphis',
    label: 'memphis kick',
  },
  {
    roles: ['kick'],
    anyOf: ['long', 'sustained', 'held', 'drawn out', 'sustain'],
    pickByGenre: {
      trap: 'trap-kick-minimal',
      rnb: 'rnb-kick-slow',
      pop: 'pop-kick-ballad',
      dance: 'dance-kick-minimal',
      house: 'house-kick-minimal',
      kpop: 'kpop-kick-verse',
      soulBlues: 'soulblues-kick-one',
      afro: 'afro-kick-minimal',
      reggae: 'reggae-kick-dub',
    },
    label: 'long kick',
  },
  {
    roles: ['kick'],
    anyOf: ['sparse', 'minimal', 'few hits', 'one hit', 'one-hit', 'dry'],
    idBoosts: ['sparse', 'minimal', 'one', 'two-hit'],
    label: 'sparse kick',
  },
  {
    roles: ['kick'],
    anyOf: ['four on the floor', 'fouronthefloor', 'four floor', 'steady four', 'four four', '4 on the floor'],
    pickByGenre: {
      house: 'house-kick-four',
      dance: 'dance-kick-four',
      pop: 'pop-kick-four',
      kpop: 'kpop-kick-four',
    },
    label: 'four-on-floor kick',
  },
  {
    roles: ['kick'],
    genres: ['house'],
    anyOf: ['deep', 'deep house', 'groove', 'warehouse'],
    pickId: 'house-kick-deep-groove',
    label: 'deep house kick',
  },
  {
    roles: ['kick'],
    genres: ['house'],
    anyOf: ['garage', 'uk garage', '2 step', '2step'],
    pickId: 'house-kick-garage',
    label: 'garage kick',
  },
  {
    roles: ['kick'],
    genres: ['house'],
    anyOf: ['techno', 'hard', 'driving house'],
    pickId: 'house-kick-techno',
    label: 'techno kick',
  },
  {
    roles: ['kick'],
    genres: ['house'],
    anyOf: ['build', 'drop', 'pickup'],
    pickId: 'house-kick-build',
    label: 'house build kick',
  },
  {
    roles: ['kick'],
    genres: ['dance'],
    anyOf: ['drop', 'festival', 'mainstage', 'big room'],
    pickId: 'dance-kick-festival',
    label: 'festival kick',
  },
  {
    roles: ['kick'],
    genres: ['dance'],
    anyOf: ['build', 'pre drop', 'predrop', 'rise'],
    pickId: 'dance-kick-build',
    label: 'build kick',
  },
  {
    roles: ['kick'],
    genres: ['dance'],
    anyOf: ['energy', 'anthem', 'chorus'],
    pickId: 'dance-kick-chorus',
    label: 'dance chorus kick',
  },
  {
    roles: ['kick'],
    genres: ['dance'],
    anyOf: ['breakdown', 'break down', 'break'],
    pickId: 'dance-kick-minimal',
    label: 'breakdown kick',
  },
  {
    roles: ['kick'],
    genres: ['rnb'],
    anyOf: ['neo', 'neo soul', 'trap soul', 'modern rnb'],
    pickId: 'rnb-kick-neo-pocket',
    label: 'neo soul kick',
  },
  {
    roles: ['kick'],
    genres: ['rnb'],
    anyOf: ['shuffle', 'swing', 'swung', 'laid back', 'laidback'],
    pickId: 'rnb-kick-shuffle',
    label: 'shuffle kick',
  },
  {
    roles: ['kick'],
    genres: ['rnb'],
    anyOf: ['velvet', 'soft', 'silky', 'silk', 'smooth'],
    idBoosts: ['velvet', 'soft', 'brush', 'bloom'],
    label: 'soft rnb kick',
  },
  {
    roles: ['kick'],
    genres: ['rnb'],
    anyOf: ['night', 'dark rnb', 'after hours'],
    pickId: 'rnb-kick-night',
    label: 'night kick',
  },
  {
    roles: ['kick'],
    genres: ['rnb'],
    anyOf: ['heavy', 'punch', 'hard'],
    pickId: 'rnb-kick-heavy',
    label: 'heavy rnb kick',
  },
  {
    roles: ['kick'],
    genres: ['pop'],
    anyOf: ['chorus', 'hook', 'lift', 'big chorus'],
    pickId: 'pop-kick-chorus',
    label: 'chorus kick',
  },
  {
    roles: ['kick'],
    genres: ['pop'],
    anyOf: ['verse', 'light', 'sparse pop'],
    pickId: 'pop-kick-verse',
    label: 'verse kick',
  },
  {
    roles: ['kick'],
    genres: ['pop'],
    anyOf: ['ballad', 'slow pop', 'slow'],
    pickId: 'pop-kick-ballad',
    label: 'ballad kick',
  },
  {
    roles: ['kick'],
    genres: ['pop'],
    anyOf: ['latin', 'reggaeton pop', 'dembow pop'],
    pickId: 'pop-kick-latin',
    label: 'latin pop kick',
  },
  {
    roles: ['kick'],
    genres: ['pop'],
    anyOf: ['pickup', 'fill into', 'pre chorus'],
    pickId: 'pop-kick-pickup',
    label: 'pickup kick',
  },
  {
    roles: ['kick'],
    genres: ['kpop'],
    anyOf: ['chorus', 'hook', 'drop', 'title track'],
    pickId: 'kpop-kick-chorus',
    label: 'chorus kick',
  },
  {
    roles: ['kick'],
    genres: ['kpop'],
    anyOf: ['verse', 'light', 'sparse'],
    pickId: 'kpop-kick-verse',
    label: 'verse kick',
  },
  {
    roles: ['kick'],
    genres: ['kpop'],
    anyOf: ['drop', 'pre chorus', 'prechorus'],
    pickId: 'kpop-kick-drop',
    label: 'drop kick',
  },
  {
    roles: ['kick'],
    genres: ['soulBlues'],
    anyOf: ['shuffle', 'swung', 'swing', 'blues', 'walk', 'swamp'],
    pickId: 'soulblues-kick-shuffle',
    label: 'shuffle kick',
  },
  {
    roles: ['kick'],
    genres: ['soulBlues'],
    anyOf: ['slow', 'memphis', 'gritty', 'grit'],
    pickId: 'soulblues-kick-slow',
    label: 'slow blues kick',
  },
  {
    roles: ['kick'],
    genres: ['soulBlues'],
    anyOf: ['walk', 'walking', 'blues walk'],
    pickId: 'soulblues-kick-walk',
    label: 'walking kick',
  },
  {
    roles: ['kick'],
    genres: ['afro'],
    anyOf: ['dembow', 'amapiano', 'log drum', 'logdrum', 'piano'],
    pickId: 'afro-kick-dembow',
    label: 'dembow kick',
  },
  {
    roles: ['kick'],
    genres: ['afro'],
    anyOf: ['lagos', 'naija', 'afrobeats'],
    idBoosts: ['lagos', 'pulse', 'dembow', 'minimal'],
    label: 'afro kick',
  },
  {
    roles: ['kick'],
    genres: ['reggae'],
    anyOf: ['one drop', 'onedrop', 'one-drop'],
    pickId: 'reggae-kick-onedrop',
    label: 'one drop kick',
  },
  {
    roles: ['kick'],
    genres: ['reggae'],
    anyOf: ['steppers', 'stepper', 'four floor reggae'],
    pickId: 'reggae-kick-steppers',
    label: 'steppers kick',
  },
  {
    roles: ['kick'],
    genres: ['reggae'],
    anyOf: ['dub', 'lazy', 'roots', 'heavy dub'],
    pickId: 'reggae-kick-dub',
    label: 'dub kick',
  },
  {
    roles: ['kick'],
    genres: ['reggae'],
    anyOf: ['rocksteady', 'slow reggae'],
    pickId: 'reggae-kick-rockers',
    label: 'rocksteady kick',
  },

  // —— Snare ——
  {
    roles: ['snare'],
    anyOf: [
      'roll at end',
      'fill at end',
      'tail at end',
      'bar end roll',
      'bar end fill',
      'end of bar roll',
      'end of bar fill',
      'roll to finish',
      'roll at finish',
      'snare roll at end',
      'then roll',
      'with roll at end',
      'with roll',
      'make it roll',
      'make a roll',
      'add roll',
      'give me a roll',
    ],
    pickByGenre: SNARE_BACKBEAT_ROLL,
    label: 'snare roll at end',
  },
  {
    roles: ['snare'],
    allOf: ['roll'],
    anyOf: [
      'backbeat',
      '2 & 4',
      'regular',
      'normal',
      'classic',
      'straight',
      'standard',
      'typical',
      'plain',
      'basic',
      'then',
    ],
    pickByGenre: SNARE_BACKBEAT_ROLL,
    label: 'regular snare with roll',
  },
  {
    roles: ['snare'],
    allOf: ['snare', 'roll'],
    anyOf: ['regular', 'normal', 'classic', 'backbeat', 'give me', 'want a', 'need a'],
    pickByGenre: SNARE_BACKBEAT_ROLL,
    label: 'snare with roll',
  },
  {
    roles: ['snare'],
    anyOf: ['roll', 'rolls', 'rolling', 'fill', 'build', 'tail', 'triplet roll'],
    pickByGenre: SNARE_BACKBEAT_ROLL,
    idBoosts: ['fill', 'build', 'roll', 'tail'],
    label: 'snare roll',
  },
  {
    roles: ['snare'],
    genres: ['trap'],
    anyOf: ['pocket', 'club', 'bounce snare'],
    pickId: 'trap-snare-pocket',
    label: 'club pocket snare',
  },
  {
    roles: ['snare'],
    genres: ['trap'],
    anyOf: ['half time', 'halftime', 'beat 3'],
    pickId: 'trap-snare-half',
    label: 'half-time snare',
  },
  {
    roles: ['snare'],
    genres: ['trap'],
    anyOf: ['ghost', 'soft ghost', 'layer'],
    pickId: 'trap-snare-ghost',
    label: 'ghost snare',
  },
  {
    roles: ['snare'],
    genres: ['trap'],
    anyOf: ['late', 'behind', 'lazy snare'],
    pickId: 'trap-snare-late-2',
    label: 'late snare',
  },
  {
    roles: ['snare'],
    genres: ['trap'],
    anyOf: ['offbeat', 'off beat', 'sync snare'],
    pickId: 'trap-snare-off',
    label: 'offbeat snare',
  },
  {
    roles: ['snare'],
    genres: ['dance'],
    anyOf: ['anthem', 'festival', 'bigroom', 'big room', 'clap stack'],
    pickId: 'dance-snare-anthem',
    label: 'anthem snare',
  },
  {
    roles: ['snare'],
    genres: ['house'],
    anyOf: ['clap', 'rim clap', 'house clap'],
    pickId: 'house-snare-24',
    label: 'house clap snare',
  },
  {
    roles: ['snare'],
    genres: ['house'],
    anyOf: ['rim', 'rimshot'],
    pickId: 'house-snare-rim',
    label: 'rim snare',
  },
  {
    roles: ['snare'],
    genres: ['rnb'],
    anyOf: ['brush', 'soft', 'silky', 'velvet'],
    pickId: 'rnb-snare-brush',
    label: 'brush snare',
  },
  {
    roles: ['snare'],
    genres: ['rnb'],
    anyOf: ['ghost', 'layer', 'soft ghost'],
    pickId: 'rnb-snare-ghost',
    label: 'ghost rnb snare',
  },
  {
    roles: ['snare'],
    genres: ['kpop'],
    anyOf: ['clap', 'stack', 'double'],
    pickId: 'kpop-snare-clap',
    label: 'clap stack snare',
  },
  {
    roles: ['snare'],
    genres: ['soulBlues'],
    anyOf: ['brush', 'swung', 'shuffle snare'],
    pickId: 'soulblues-snare-brush',
    label: 'blues brush snare',
  },
  {
    roles: ['snare'],
    genres: ['afro'],
    anyOf: ['cross stick', 'crossstick', 'rim afro'],
    idBoosts: ['cross', 'rim', 'snap'],
    label: 'afro snare',
  },
  {
    roles: ['snare'],
    genres: ['reggae'],
    anyOf: ['one drop snare', 'beat 3 reggae'],
    pickId: 'reggae-snare-onedrop',
    label: 'one drop snare',
  },
  {
    roles: ['snare'],
    anyOf: ['ghost', 'soft', 'light'],
    idBoosts: ['ghost', 'soft', 'brush'],
    label: 'ghost snare',
  },
  {
    roles: ['snare'],
    anyOf: ['backbeat', '2 and 4', '2 & 4', '24', 'classic', 'on the 2', 'on the 4'],
    idBoosts: ['24', 'snap', 'stack', 'backbeat'],
    label: '2 & 4 snare',
  },
  {
    roles: ['snare'],
    anyOf: ['sparse', 'minimal', 'one hit'],
    idBoosts: ['sparse', 'minimal', 'one'],
    label: 'sparse snare',
  },

  // —— Hi-hat ——
  {
    roles: ['hihat'],
    genres: ['trap'],
    anyOf: ['roll', 'rolls', 'fill', 'burst', 'build', '16', '16th', '32nd', 'machine gun'],
    idBoosts: ['roll', '16', 'steady', 'burst', 'machine'],
    label: 'trap hat roll',
  },
  {
    roles: ['hihat'],
    genres: ['trap'],
    anyOf: ['two step', 'twostep', '8th', 'eighth', 'straight'],
    idBoosts: ['two-step', 'twostep', '8th', '8'],
    label: '8th hats',
  },
  {
    roles: ['hihat'],
    genres: ['trap'],
    anyOf: ['open close', 'bounce hat', 'trap bounce'],
    idBoosts: ['bounce', 'open', 'sync'],
    label: 'bounce hats',
  },
  {
    roles: ['hihat'],
    genres: ['dance'],
    anyOf: ['roll', 'rolls', 'fill', 'build', 'energy'],
    pickId: 'dance-hat-roll',
    label: 'dance hat roll',
  },
  {
    roles: ['hihat'],
    genres: ['dance'],
    anyOf: ['four', 'steady', 'driving hat'],
    idBoosts: ['four', 'steady', '16'],
    label: 'steady dance hats',
  },
  {
    roles: ['hihat'],
    genres: ['house'],
    anyOf: ['open close', 'offbeat', 'shuffle hat'],
    idBoosts: ['off', 'shuffle', 'open'],
    label: 'house hats',
  },
  {
    roles: ['hihat'],
    genres: ['rnb'],
    anyOf: ['shuffle', 'swing', 'silk', 'swung hat'],
    pickId: 'rnb-hat-silk-roll',
    label: 'shuffle hats',
  },
  {
    roles: ['hihat'],
    genres: ['rnb'],
    anyOf: ['soft', 'brush hat', 'light'],
    idBoosts: ['silk', 'soft', 'brush'],
    label: 'soft rnb hats',
  },
  {
    roles: ['hihat'],
    genres: ['afro'],
    anyOf: ['dembow', 'amapiano', 'log drum', 'logdrum'],
    idBoosts: ['dembow', 'skitter', '16', 'steady'],
    label: 'dembow hats',
  },
  {
    roles: ['hihat'],
    genres: ['afro'],
    anyOf: ['shaker', 'skitter', 'groove hat'],
    idBoosts: ['shaker', 'skitter', 'groove'],
    label: 'afro hats',
  },
  {
    roles: ['hihat'],
    genres: ['reggae'],
    anyOf: ['skank', 'offbeat', 'chick'],
    pickId: 'reggae-hat-off',
    label: 'skank hats',
  },
  {
    roles: ['hihat'],
    anyOf: ['sparse', 'minimal', 'quarter', 'few hats'],
    idBoosts: ['sparse', 'minimal', 'quarter'],
    label: 'sparse hats',
  },
  {
    roles: ['hihat'],
    anyOf: ['steady', '8th note', '8th notes', 'running'],
    idBoosts: ['8', 'steady', '16'],
    label: 'steady hats',
  },

  // —— Clap ——
  {
    roles: ['clap'],
    anyOf: ['roll', 'fill', 'build', 'double', 'echo'],
    idBoosts: ['fill', 'double', 'echo', 'stack', 'roll'],
    label: 'clap fill',
  },
  {
    roles: ['clap'],
    anyOf: ['2 and 4', '2 & 4', 'backbeat clap'],
    idBoosts: ['24', 'stack'],
    label: '2 & 4 clap',
  },
  {
    roles: ['clap'],
    genres: ['house'],
    anyOf: ['four', 'house clap', 'offbeat clap'],
    idBoosts: ['off', 'four', 'clap'],
    label: 'house clap',
  },
  {
    roles: ['clap'],
    genres: ['trap'],
    anyOf: ['stack', 'layer', 'snare clap'],
    idBoosts: ['stack', 'clap'],
    label: 'stack clap',
  },

  // —— Open hat ——
  {
    roles: ['openHat'],
    anyOf: ['sparse', 'minimal', 'one', 'single open'],
    idBoosts: ['sparse', 'minimal', 'one'],
    label: 'sparse open hat',
  },
  {
    roles: ['openHat'],
    anyOf: ['fill', 'lift', 'roll', 'accent'],
    idBoosts: ['fill', 'lift', 'double', 'chorus'],
    label: 'open hat fill',
  },
  {
    roles: ['openHat'],
    genres: ['house'],
    anyOf: ['offbeat', 'open close', 'house open'],
    idBoosts: ['off', 'open'],
    label: 'house open hat',
  },
  {
    roles: ['openHat'],
    genres: ['dance'],
    anyOf: ['drop', 'build', 'energy open'],
    idBoosts: ['drop', 'build', 'lift'],
    label: 'dance open hat',
  },
  {
    roles: ['openHat'],
    genres: ['kpop'],
    anyOf: ['chorus', 'hook open'],
    pickId: 'kpop-oh-chorus',
    label: 'chorus open hat',
  },

  // —— Rim / perc ——
  {
    roles: ['rim'],
    anyOf: ['ghost', 'soft', 'layer', 'light'],
    idBoosts: ['ghost', 'soft'],
    label: 'ghost rim',
  },
  {
    roles: ['rim'],
    anyOf: ['fill', 'roll', 'build', 'tail'],
    idBoosts: ['fill', 'roll', 'build'],
    label: 'rim fill',
  },
  {
    roles: ['rim'],
    genres: ['reggae'],
    anyOf: ['skank', 'offbeat', 'perc skank'],
    pickId: 'reggae-rim-skank',
    label: 'skank rim',
  },
  {
    roles: ['rim'],
    genres: ['soulBlues'],
    anyOf: ['shuffle', 'swung rim', 'brush'],
    idBoosts: ['shuffle', 'brush', 'swung'],
    label: 'shuffle rim',
  },
  {
    roles: ['rim'],
    genres: ['afro'],
    anyOf: ['shaker', 'conga', 'perc groove'],
    idBoosts: ['shaker', 'groove', 'skitter'],
    label: 'afro perc',
  },
  {
    roles: ['rim'],
    genres: ['house'],
    anyOf: ['groove', 'rim groove', 'perc house'],
    idBoosts: ['groove', 'rim'],
    label: 'house rim',
  },
];
