/**
 * Groove Lead — smooth lead presets (category banks).
 * Web Audio synth + optional real guitar one-shots (guitar-licks manifest).
 */
import {
  WAVE_LEAF_LIVE_GUITAR_PRESETS,
  WAVE_LEAF_LIVE_GUITAR_PRESET_ORDER,
  type WaveLeafLiveGuitarPresetId,
} from '@/app/lib/creationStation/waveLeafGuitarLive';

export type WaveLeafPresetId =
  | 'rnb-silk'
  | 'neo-glide'
  | 'g-funk-brass'
  | 'analog-warm'
  | 'pop-shine'
  | 'trap-bell'
  | 'retrowave'
  | 'gospel-cry'
  | 'kompa-glow'
  | 'edm-hook'
  | 'afro-pluck'
  | 'cinematic-pad-lead'
  | 'moog-classic'
  | 'moog-glide'
  | 'moog-bite'
  | 'wah-funk'
  | 'wah-cry'
  | 'crunch-guitar'
  | 'clean-pluck'
  | 'mute-funk'
  | 'spark-pluck'
  | 'hook-stab'
  | 'fusion-brass'
  | 'nylon-hook'
  | 'moog-high'
  | 'moog-legato'
  | 'moog-mini'
  | 'moog-mini-gtr'
  | 'moog-mini-wah'
  | 'flute-air'
  | 'flute-moog'
  | 'strat-glass'
  | 'wah-disco'
  | 'talk-wah'
  | 'brass-stab'
  | 'shimmer-hook'
  | 'velvet-lead'
  | 'zone-pluck'
  | 'saw-hook'
  | WaveLeafLiveGuitarPresetId;

export type WaveLeafOscWave = 'sine' | 'triangle' | 'sawtooth';

export interface WaveLeafPreset {
  id: WaveLeafPresetId;
  label: string;
  category: string;
  /** Real guitar one-shot (`guitar-licks/manifest.json`). Synth fields = offline fallback. */
  sampleLickId?: string;
  sampleWah?: number;
  sampleWahRateHz?: number;
  sampleDrive?: number;
  samplePluck?: boolean;
  /** Pad subtitle in Groove Lead UI (e.g. "LIVE · wah pluck"). */
  voiceTag?: string;
  osc1: WaveLeafOscWave;
  osc2: WaveLeafOscWave;
  osc2Level: number;
  detuneCents: number;
  filterHz: number;
  filterQ: number;
  filterAttack: number;
  filterDecay: number;
  filterSustain: number;
  ampAttack: number;
  ampDecay: number;
  ampSustain: number;
  ampRelease: number;
  glideMs: number;
  vibratoHz: number;
  vibratoDepthCents: number;
  chorusMix: number;
  drive: number;
}

export const WAVE_LEAF_DEFAULT_PRESET: WaveLeafPresetId = 'rnb-silk';

export const WAVE_LEAF_PRESETS: Record<WaveLeafPresetId, WaveLeafPreset> = {
  'rnb-silk': {
    id: 'rnb-silk',
    label: 'R&B Silk',
    category: 'R&B / Neo Soul',
    osc1: 'sine',
    osc2: 'triangle',
    osc2Level: 0.35,
    detuneCents: 6,
    filterHz: 5200,
    filterQ: 0.7,
    filterAttack: 0.04,
    filterDecay: 0.35,
    filterSustain: 0.55,
    ampAttack: 0.018,
    ampDecay: 0.22,
    ampSustain: 0.72,
    ampRelease: 0.42,
    glideMs: 95,
    vibratoHz: 5.2,
    vibratoDepthCents: 9,
    chorusMix: 0.22,
    drive: 0.08,
  },
  'neo-glide': {
    id: 'neo-glide',
    label: 'Neo Glide',
    category: 'R&B / Neo Soul',
    osc1: 'sawtooth',
    osc2: 'sine',
    osc2Level: 0.28,
    detuneCents: 11,
    filterHz: 3800,
    filterQ: 1.1,
    filterAttack: 0.06,
    filterDecay: 0.4,
    filterSustain: 0.48,
    ampAttack: 0.012,
    ampDecay: 0.28,
    ampSustain: 0.68,
    ampRelease: 0.38,
    glideMs: 140,
    vibratoHz: 4.8,
    vibratoDepthCents: 11,
    chorusMix: 0.28,
    drive: 0.12,
  },
  'g-funk-brass': {
    id: 'g-funk-brass',
    label: 'G-Funk Brass',
    category: 'Hip Hop / G-Funk',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.42,
    detuneCents: 18,
    filterHz: 2400,
    filterQ: 2.2,
    filterAttack: 0.02,
    filterDecay: 0.18,
    filterSustain: 0.35,
    ampAttack: 0.008,
    ampDecay: 0.16,
    ampSustain: 0.55,
    ampRelease: 0.28,
    glideMs: 45,
    vibratoHz: 6.5,
    vibratoDepthCents: 5,
    chorusMix: 0.14,
    drive: 0.28,
  },
  'analog-warm': {
    id: 'analog-warm',
    label: 'Analog Warm',
    category: 'Classic Synth',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.38,
    detuneCents: 14,
    filterHz: 3100,
    filterQ: 1.4,
    filterAttack: 0.05,
    filterDecay: 0.5,
    filterSustain: 0.42,
    ampAttack: 0.02,
    ampDecay: 0.32,
    ampSustain: 0.65,
    ampRelease: 0.45,
    glideMs: 70,
    vibratoHz: 5,
    vibratoDepthCents: 7,
    chorusMix: 0.32,
    drive: 0.15,
  },
  'pop-shine': {
    id: 'pop-shine',
    label: 'Pop Shine',
    category: 'Pop / EDM',
    osc1: 'triangle',
    osc2: 'sine',
    osc2Level: 0.5,
    detuneCents: 8,
    filterHz: 6800,
    filterQ: 0.5,
    filterAttack: 0.01,
    filterDecay: 0.2,
    filterSustain: 0.7,
    ampAttack: 0.006,
    ampDecay: 0.18,
    ampSustain: 0.78,
    ampRelease: 0.32,
    glideMs: 55,
    vibratoHz: 5.8,
    vibratoDepthCents: 6,
    chorusMix: 0.38,
    drive: 0.06,
  },
  'trap-bell': {
    id: 'trap-bell',
    label: 'Trap Bell',
    category: 'Trap',
    osc1: 'sine',
    osc2: 'triangle',
    osc2Level: 0.55,
    detuneCents: 4,
    filterHz: 8200,
    filterQ: 0.4,
    filterAttack: 0.002,
    filterDecay: 0.12,
    filterSustain: 0.2,
    ampAttack: 0.002,
    ampDecay: 0.14,
    ampSustain: 0.35,
    ampRelease: 0.22,
    glideMs: 25,
    vibratoHz: 7,
    vibratoDepthCents: 4,
    chorusMix: 0.18,
    drive: 0.04,
  },
  retrowave: {
    id: 'retrowave',
    label: 'Retrowave',
    category: 'Retrowave',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.22,
    detuneCents: 22,
    filterHz: 4200,
    filterQ: 1.8,
    filterAttack: 0.03,
    filterDecay: 0.25,
    filterSustain: 0.5,
    ampAttack: 0.01,
    ampDecay: 0.2,
    ampSustain: 0.6,
    ampRelease: 0.35,
    glideMs: 110,
    vibratoHz: 4.2,
    vibratoDepthCents: 12,
    chorusMix: 0.45,
    drive: 0.2,
  },
  'gospel-cry': {
    id: 'gospel-cry',
    label: 'Gospel Cry',
    category: 'Gospel / Soul',
    osc1: 'sine',
    osc2: 'sawtooth',
    osc2Level: 0.3,
    detuneCents: 9,
    filterHz: 4600,
    filterQ: 0.9,
    filterAttack: 0.08,
    filterDecay: 0.45,
    filterSustain: 0.58,
    ampAttack: 0.025,
    ampDecay: 0.3,
    ampSustain: 0.75,
    ampRelease: 0.5,
    glideMs: 120,
    vibratoHz: 5.5,
    vibratoDepthCents: 14,
    chorusMix: 0.26,
    drive: 0.1,
  },
  'kompa-glow': {
    id: 'kompa-glow',
    label: 'Kompa Glow',
    category: 'Kompa / Afrobeats',
    osc1: 'triangle',
    osc2: 'sine',
    osc2Level: 0.45,
    detuneCents: 7,
    filterHz: 5500,
    filterQ: 0.6,
    filterAttack: 0.015,
    filterDecay: 0.28,
    filterSustain: 0.62,
    ampAttack: 0.01,
    ampDecay: 0.24,
    ampSustain: 0.7,
    ampRelease: 0.4,
    glideMs: 80,
    vibratoHz: 5,
    vibratoDepthCents: 8,
    chorusMix: 0.3,
    drive: 0.07,
  },
  'edm-hook': {
    id: 'edm-hook',
    label: 'EDM Hook',
    category: 'Pop / EDM',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.35,
    detuneCents: 16,
    filterHz: 7200,
    filterQ: 0.85,
    filterAttack: 0.004,
    filterDecay: 0.15,
    filterSustain: 0.55,
    ampAttack: 0.004,
    ampDecay: 0.12,
    ampSustain: 0.72,
    ampRelease: 0.25,
    glideMs: 40,
    vibratoHz: 6.2,
    vibratoDepthCents: 5,
    chorusMix: 0.4,
    drive: 0.18,
  },
  'afro-pluck': {
    id: 'afro-pluck',
    label: 'Afro Pluck',
    category: 'Kompa / Afrobeats',
    osc1: 'triangle',
    osc2: 'triangle',
    osc2Level: 0.4,
    detuneCents: 5,
    filterHz: 6100,
    filterQ: 0.55,
    filterAttack: 0.003,
    filterDecay: 0.1,
    filterSustain: 0.25,
    ampAttack: 0.003,
    ampDecay: 0.1,
    ampSustain: 0.4,
    ampRelease: 0.18,
    glideMs: 30,
    vibratoHz: 5.5,
    vibratoDepthCents: 4,
    chorusMix: 0.2,
    drive: 0.05,
  },
  'cinematic-pad-lead': {
    id: 'cinematic-pad-lead',
    label: 'Cinematic Lead',
    category: 'Cinematic',
    osc1: 'sine',
    osc2: 'sawtooth',
    osc2Level: 0.25,
    detuneCents: 12,
    filterHz: 3400,
    filterQ: 0.75,
    filterAttack: 0.12,
    filterDecay: 0.6,
    filterSustain: 0.65,
    ampAttack: 0.04,
    ampDecay: 0.4,
    ampSustain: 0.8,
    ampRelease: 0.65,
    glideMs: 160,
    vibratoHz: 4.5,
    vibratoDepthCents: 10,
    chorusMix: 0.35,
    drive: 0.06,
  },
  'moog-classic': {
    id: 'moog-classic',
    label: 'Moog Classic',
    category: 'Moog / Analog',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.5,
    detuneCents: 7,
    filterHz: 2900,
    filterQ: 1.65,
    filterAttack: 0.006,
    filterDecay: 0.24,
    filterSustain: 0.34,
    ampAttack: 0.005,
    ampDecay: 0.2,
    ampSustain: 0.58,
    ampRelease: 0.32,
    glideMs: 58,
    vibratoHz: 5.4,
    vibratoDepthCents: 6,
    chorusMix: 0.12,
    drive: 0.16,
  },
  'moog-glide': {
    id: 'moog-glide',
    label: 'Moog Glide',
    category: 'Moog / Analog',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.44,
    detuneCents: 11,
    filterHz: 3600,
    filterQ: 1.25,
    filterAttack: 0.02,
    filterDecay: 0.42,
    filterSustain: 0.52,
    ampAttack: 0.018,
    ampDecay: 0.3,
    ampSustain: 0.7,
    ampRelease: 0.42,
    glideMs: 185,
    vibratoHz: 4.6,
    vibratoDepthCents: 9,
    chorusMix: 0.2,
    drive: 0.12,
  },
  'moog-bite': {
    id: 'moog-bite',
    label: 'Moog Scream',
    category: 'Moog / Analog',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.38,
    detuneCents: 19,
    filterHz: 2100,
    filterQ: 2.75,
    filterAttack: 0.004,
    filterDecay: 0.18,
    filterSustain: 0.28,
    ampAttack: 0.004,
    ampDecay: 0.17,
    ampSustain: 0.52,
    ampRelease: 0.28,
    glideMs: 48,
    vibratoHz: 6,
    vibratoDepthCents: 7,
    chorusMix: 0.1,
    drive: 0.24,
  },
  'wah-funk': {
    id: 'wah-funk',
    label: 'Wah Funk',
    category: 'Guitar / Wah',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.32,
    detuneCents: 10,
    filterHz: 1650,
    filterQ: 3.1,
    filterAttack: 0.01,
    filterDecay: 0.38,
    filterSustain: 0.1,
    ampAttack: 0.003,
    ampDecay: 0.22,
    ampSustain: 0.48,
    ampRelease: 0.26,
    glideMs: 38,
    vibratoHz: 5.8,
    vibratoDepthCents: 8,
    chorusMix: 0.08,
    drive: 0.36,
  },
  'wah-cry': {
    id: 'wah-cry',
    label: 'Wah Cry',
    category: 'Guitar / Wah',
    osc1: 'sawtooth',
    osc2: 'sine',
    osc2Level: 0.28,
    detuneCents: 6,
    filterHz: 1400,
    filterQ: 2.55,
    filterAttack: 0.025,
    filterDecay: 0.58,
    filterSustain: 0.22,
    ampAttack: 0.012,
    ampDecay: 0.35,
    ampSustain: 0.62,
    ampRelease: 0.4,
    glideMs: 95,
    vibratoHz: 5.2,
    vibratoDepthCents: 16,
    chorusMix: 0.16,
    drive: 0.22,
  },
  'crunch-guitar': {
    id: 'crunch-guitar',
    label: 'Crunch Guitar',
    category: 'Guitar / Wah',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.36,
    detuneCents: 9,
    filterHz: 4100,
    filterQ: 1.35,
    filterAttack: 0.008,
    filterDecay: 0.28,
    filterSustain: 0.4,
    ampAttack: 0.006,
    ampDecay: 0.24,
    ampSustain: 0.6,
    ampRelease: 0.3,
    glideMs: 42,
    vibratoHz: 5.5,
    vibratoDepthCents: 5,
    chorusMix: 0.1,
    drive: 0.44,
  },
  'clean-pluck': {
    id: 'clean-pluck',
    label: 'Clean Pluck',
    category: 'Guitar / Wah',
    osc1: 'triangle',
    osc2: 'sawtooth',
    osc2Level: 0.3,
    detuneCents: 5,
    filterHz: 5800,
    filterQ: 0.85,
    filterAttack: 0.002,
    filterDecay: 0.09,
    filterSustain: 0.18,
    ampAttack: 0.002,
    ampDecay: 0.1,
    ampSustain: 0.32,
    ampRelease: 0.16,
    glideMs: 22,
    vibratoHz: 0,
    vibratoDepthCents: 0,
    chorusMix: 0.12,
    drive: 0.06,
  },
  'mute-funk': {
    id: 'mute-funk',
    label: 'Mute Funk',
    category: 'Guitar / Wah',
    osc1: 'triangle',
    osc2: 'triangle',
    osc2Level: 0.42,
    detuneCents: 4,
    filterHz: 3200,
    filterQ: 1.1,
    filterAttack: 0.001,
    filterDecay: 0.07,
    filterSustain: 0.12,
    ampAttack: 0.001,
    ampDecay: 0.06,
    ampSustain: 0.22,
    ampRelease: 0.12,
    glideMs: 18,
    vibratoHz: 0,
    vibratoDepthCents: 0,
    chorusMix: 0.06,
    drive: 0.14,
  },
  'spark-pluck': {
    id: 'spark-pluck',
    label: 'Spark Pluck',
    category: 'Pluck / Hook',
    osc1: 'triangle',
    osc2: 'sine',
    osc2Level: 0.52,
    detuneCents: 6,
    filterHz: 7600,
    filterQ: 0.65,
    filterAttack: 0.001,
    filterDecay: 0.08,
    filterSustain: 0.15,
    ampAttack: 0.001,
    ampDecay: 0.09,
    ampSustain: 0.28,
    ampRelease: 0.14,
    glideMs: 20,
    vibratoHz: 6.5,
    vibratoDepthCents: 3,
    chorusMix: 0.24,
    drive: 0.05,
  },
  'hook-stab': {
    id: 'hook-stab',
    label: 'Hook Stab',
    category: 'Pluck / Hook',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.4,
    detuneCents: 14,
    filterHz: 6400,
    filterQ: 1.05,
    filterAttack: 0.001,
    filterDecay: 0.11,
    filterSustain: 0.2,
    ampAttack: 0.001,
    ampDecay: 0.11,
    ampSustain: 0.35,
    ampRelease: 0.15,
    glideMs: 28,
    vibratoHz: 0,
    vibratoDepthCents: 0,
    chorusMix: 0.15,
    drive: 0.1,
  },
  'fusion-brass': {
    id: 'fusion-brass',
    label: 'Fusion Brass',
    category: 'R&B / Neo Soul',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.4,
    detuneCents: 13,
    filterHz: 3900,
    filterQ: 1.95,
    filterAttack: 0.015,
    filterDecay: 0.32,
    filterSustain: 0.45,
    ampAttack: 0.01,
    ampDecay: 0.26,
    ampSustain: 0.66,
    ampRelease: 0.36,
    glideMs: 88,
    vibratoHz: 5.6,
    vibratoDepthCents: 10,
    chorusMix: 0.22,
    drive: 0.18,
  },
  'nylon-hook': {
    id: 'nylon-hook',
    label: 'Nylon Hook',
    category: 'R&B / Neo Soul',
    osc1: 'sine',
    osc2: 'triangle',
    osc2Level: 0.38,
    detuneCents: 5,
    filterHz: 4800,
    filterQ: 0.55,
    filterAttack: 0.02,
    filterDecay: 0.32,
    filterSustain: 0.5,
    ampAttack: 0.014,
    ampDecay: 0.28,
    ampSustain: 0.68,
    ampRelease: 0.38,
    glideMs: 72,
    vibratoHz: 4.8,
    vibratoDepthCents: 7,
    chorusMix: 0.18,
    drive: 0.04,
  },
  'moog-high': {
    id: 'moog-high',
    label: 'Moog High',
    category: 'Moog / Analog',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.42,
    detuneCents: 15,
    filterHz: 5200,
    filterQ: 1.45,
    filterAttack: 0.005,
    filterDecay: 0.2,
    filterSustain: 0.48,
    ampAttack: 0.004,
    ampDecay: 0.18,
    ampSustain: 0.62,
    ampRelease: 0.3,
    glideMs: 65,
    vibratoHz: 5.8,
    vibratoDepthCents: 8,
    chorusMix: 0.16,
    drive: 0.14,
  },
  'moog-legato': {
    id: 'moog-legato',
    label: 'Moog Legato',
    category: 'Moog / Analog',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.36,
    detuneCents: 8,
    filterHz: 3000,
    filterQ: 1.05,
    filterAttack: 0.035,
    filterDecay: 0.55,
    filterSustain: 0.62,
    ampAttack: 0.028,
    ampDecay: 0.38,
    ampSustain: 0.78,
    ampRelease: 0.52,
    glideMs: 210,
    vibratoHz: 4.4,
    vibratoDepthCents: 11,
    chorusMix: 0.24,
    drive: 0.1,
  },
  'moog-mini': {
    id: 'moog-mini',
    label: 'Moog Mini',
    category: 'Moog / Analog',
    voiceTag: 'Mini Moog',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.46,
    detuneCents: 9,
    filterHz: 2550,
    filterQ: 1.9,
    filterAttack: 0.012,
    filterDecay: 0.4,
    filterSustain: 0.56,
    ampAttack: 0.01,
    ampDecay: 0.34,
    ampSustain: 0.76,
    ampRelease: 0.52,
    glideMs: 92,
    vibratoHz: 5.1,
    vibratoDepthCents: 7,
    chorusMix: 0.14,
    drive: 0.14,
  },
  'moog-mini-gtr': {
    id: 'moog-mini-gtr',
    label: 'Mini Moog Gtr',
    category: 'Guitar / Wah',
    voiceTag: 'Mini Moog',
    osc1: 'sawtooth',
    osc2: 'triangle',
    osc2Level: 0.4,
    detuneCents: 7,
    filterHz: 2280,
    filterQ: 1.75,
    filterAttack: 0.014,
    filterDecay: 0.42,
    filterSustain: 0.5,
    ampAttack: 0.01,
    ampDecay: 0.36,
    ampSustain: 0.72,
    ampRelease: 0.46,
    glideMs: 78,
    vibratoHz: 5.4,
    vibratoDepthCents: 6,
    chorusMix: 0.1,
    drive: 0.2,
  },
  'moog-mini-wah': {
    id: 'moog-mini-wah',
    label: 'Mini Moog Wah',
    category: 'Guitar / Wah',
    voiceTag: 'Mini Moog · wah',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.34,
    detuneCents: 11,
    filterHz: 1750,
    filterQ: 2.65,
    filterAttack: 0.038,
    filterDecay: 0.62,
    filterSustain: 0.38,
    ampAttack: 0.012,
    ampDecay: 0.38,
    ampSustain: 0.7,
    ampRelease: 0.44,
    glideMs: 86,
    vibratoHz: 5.6,
    vibratoDepthCents: 9,
    chorusMix: 0.12,
    drive: 0.26,
  },
  'flute-air': {
    id: 'flute-air',
    label: 'Flute Air',
    category: 'Flute / Woodwind',
    voiceTag: 'Breathy',
    osc1: 'sine',
    osc2: 'triangle',
    osc2Level: 0.38,
    detuneCents: 4,
    filterHz: 4400,
    filterQ: 0.55,
    filterAttack: 0.045,
    filterDecay: 0.55,
    filterSustain: 0.68,
    ampAttack: 0.042,
    ampDecay: 0.45,
    ampSustain: 0.82,
    ampRelease: 0.68,
    glideMs: 42,
    vibratoHz: 5.9,
    vibratoDepthCents: 16,
    chorusMix: 0.22,
    drive: 0.04,
  },
  'flute-moog': {
    id: 'flute-moog',
    label: 'Flute Moog',
    category: 'Flute / Woodwind',
    voiceTag: 'Mini Moog · flute',
    osc1: 'sine',
    osc2: 'sawtooth',
    osc2Level: 0.26,
    detuneCents: 6,
    filterHz: 3100,
    filterQ: 1.15,
    filterAttack: 0.032,
    filterDecay: 0.5,
    filterSustain: 0.6,
    ampAttack: 0.035,
    ampDecay: 0.4,
    ampSustain: 0.8,
    ampRelease: 0.58,
    glideMs: 108,
    vibratoHz: 5.4,
    vibratoDepthCents: 14,
    chorusMix: 0.2,
    drive: 0.1,
  },
  'strat-glass': {
    id: 'strat-glass',
    label: 'Strat Glass',
    category: 'Guitar / Wah',
    osc1: 'triangle',
    osc2: 'sawtooth',
    osc2Level: 0.26,
    detuneCents: 4,
    filterHz: 6200,
    filterQ: 0.5,
    filterAttack: 0.008,
    filterDecay: 0.22,
    filterSustain: 0.55,
    ampAttack: 0.008,
    ampDecay: 0.26,
    ampSustain: 0.65,
    ampRelease: 0.34,
    glideMs: 52,
    vibratoHz: 5.2,
    vibratoDepthCents: 6,
    chorusMix: 0.2,
    drive: 0.08,
  },
  'wah-disco': {
    id: 'wah-disco',
    label: 'Wah Disco',
    category: 'Guitar / Wah',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.3,
    detuneCents: 12,
    filterHz: 2200,
    filterQ: 2.4,
    filterAttack: 0.006,
    filterDecay: 0.2,
    filterSustain: 0.18,
    ampAttack: 0.004,
    ampDecay: 0.16,
    ampSustain: 0.5,
    ampRelease: 0.24,
    glideMs: 35,
    vibratoHz: 6.2,
    vibratoDepthCents: 5,
    chorusMix: 0.22,
    drive: 0.2,
  },
  'talk-wah': {
    id: 'talk-wah',
    label: 'Talk Wah',
    category: 'Guitar / Wah',
    osc1: 'sawtooth',
    osc2: 'sine',
    osc2Level: 0.45,
    detuneCents: 3,
    filterHz: 1100,
    filterQ: 3.4,
    filterAttack: 0.018,
    filterDecay: 0.48,
    filterSustain: 0.15,
    ampAttack: 0.01,
    ampDecay: 0.3,
    ampSustain: 0.55,
    ampRelease: 0.32,
    glideMs: 70,
    vibratoHz: 5,
    vibratoDepthCents: 18,
    chorusMix: 0.1,
    drive: 0.26,
  },
  'brass-stab': {
    id: 'brass-stab',
    label: 'Brass Stab',
    category: 'Pluck / Hook',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.45,
    detuneCents: 16,
    filterHz: 3400,
    filterQ: 2.1,
    filterAttack: 0.003,
    filterDecay: 0.14,
    filterSustain: 0.22,
    ampAttack: 0.002,
    ampDecay: 0.13,
    ampSustain: 0.38,
    ampRelease: 0.2,
    glideMs: 32,
    vibratoHz: 0,
    vibratoDepthCents: 0,
    chorusMix: 0.12,
    drive: 0.2,
  },
  'shimmer-hook': {
    id: 'shimmer-hook',
    label: 'Shimmer Hook',
    category: 'Pluck / Hook',
    osc1: 'triangle',
    osc2: 'sine',
    osc2Level: 0.58,
    detuneCents: 9,
    filterHz: 8800,
    filterQ: 0.45,
    filterAttack: 0.002,
    filterDecay: 0.14,
    filterSustain: 0.35,
    ampAttack: 0.003,
    ampDecay: 0.16,
    ampSustain: 0.55,
    ampRelease: 0.28,
    glideMs: 45,
    vibratoHz: 6,
    vibratoDepthCents: 5,
    chorusMix: 0.42,
    drive: 0.05,
  },
  'velvet-lead': {
    id: 'velvet-lead',
    label: 'Velvet Lead',
    category: 'R&B / Neo Soul',
    osc1: 'sine',
    osc2: 'sawtooth',
    osc2Level: 0.22,
    detuneCents: 6,
    filterHz: 4400,
    filterQ: 0.65,
    filterAttack: 0.05,
    filterDecay: 0.4,
    filterSustain: 0.6,
    ampAttack: 0.02,
    ampDecay: 0.32,
    ampSustain: 0.74,
    ampRelease: 0.45,
    glideMs: 105,
    vibratoHz: 5.1,
    vibratoDepthCents: 12,
    chorusMix: 0.3,
    drive: 0.06,
  },
  'zone-pluck': {
    id: 'zone-pluck',
    label: 'Zone Pluck',
    category: 'Hip Hop / G-Funk',
    osc1: 'triangle',
    osc2: 'sawtooth',
    osc2Level: 0.38,
    detuneCents: 7,
    filterHz: 7000,
    filterQ: 0.7,
    filterAttack: 0.001,
    filterDecay: 0.07,
    filterSustain: 0.1,
    ampAttack: 0.001,
    ampDecay: 0.08,
    ampSustain: 0.25,
    ampRelease: 0.12,
    glideMs: 24,
    vibratoHz: 0,
    vibratoDepthCents: 0,
    chorusMix: 0.14,
    drive: 0.12,
  },
  'saw-hook': {
    id: 'saw-hook',
    label: 'Saw Hook',
    category: 'Pop / EDM',
    osc1: 'sawtooth',
    osc2: 'sawtooth',
    osc2Level: 0.32,
    detuneCents: 20,
    filterHz: 5800,
    filterQ: 0.95,
    filterAttack: 0.003,
    filterDecay: 0.16,
    filterSustain: 0.42,
    ampAttack: 0.003,
    ampDecay: 0.14,
    ampSustain: 0.58,
    ampRelease: 0.22,
    glideMs: 50,
    vibratoHz: 5.5,
    vibratoDepthCents: 4,
    chorusMix: 0.28,
    drive: 0.15,
  },
  ...WAVE_LEAF_LIVE_GUITAR_PRESETS,
};

export const WAVE_LEAF_PRESET_ORDER: readonly WaveLeafPresetId[] = [
  'moog-mini',
  'moog-mini-gtr',
  'moog-mini-wah',
  'flute-air',
  'flute-moog',
  'moog-classic',
  'moog-glide',
  'moog-bite',
  'moog-high',
  'moog-legato',
  'wah-funk',
  'wah-cry',
  'wah-disco',
  'talk-wah',
  'crunch-guitar',
  'clean-pluck',
  'mute-funk',
  'strat-glass',
  'spark-pluck',
  'hook-stab',
  'brass-stab',
  'shimmer-hook',
  'zone-pluck',
  'saw-hook',
  'rnb-silk',
  'neo-glide',
  'gospel-cry',
  'fusion-brass',
  'nylon-hook',
  'velvet-lead',
  'g-funk-brass',
  'analog-warm',
  'pop-shine',
  'trap-bell',
  'edm-hook',
  'kompa-glow',
  'afro-pluck',
  'retrowave',
  'cinematic-pad-lead',
];

export const WAVE_LEAF_PRESET_GROUPS: ReadonlyArray<{
  label: string;
  ids: readonly WaveLeafPresetId[];
}> = [
  { label: 'All Leads', ids: WAVE_LEAF_PRESET_ORDER },
  {
    label: 'Moog / Analog',
    ids: [
      'moog-mini',
      'moog-classic',
      'moog-glide',
      'moog-legato',
      'moog-bite',
      'moog-high',
      'analog-warm',
      'retrowave',
      'neo-glide',
    ],
  },
  {
    label: 'Flute / Woodwind',
    ids: ['flute-air', 'flute-moog', 'moog-mini', 'cinematic-pad-lead', 'velvet-lead'],
  },
  {
    label: 'Guitar / Wah',
    ids: [
      'moog-mini-gtr',
      'moog-mini-wah',
      ...WAVE_LEAF_LIVE_GUITAR_PRESET_ORDER,
      'wah-funk',
      'wah-cry',
      'wah-disco',
      'talk-wah',
      'crunch-guitar',
      'clean-pluck',
      'mute-funk',
      'strat-glass',
    ],
  },
  {
    label: 'Pluck / Hook',
    ids: [
      'live-harmonic',
      'live-clean-pick',
      'spark-pluck',
      'hook-stab',
      'brass-stab',
      'shimmer-hook',
      'afro-pluck',
      'trap-bell',
      'pop-shine',
      'zone-pluck',
    ],
  },
  {
    label: 'R&B / Neo Soul',
    ids: ['rnb-silk', 'gospel-cry', 'fusion-brass', 'nylon-hook', 'velvet-lead', 'kompa-glow'],
  },
  { label: 'Hip Hop / G-Funk', ids: ['g-funk-brass', 'trap-bell', 'edm-hook', 'zone-pluck', 'saw-hook'] },
  { label: 'Pop / EDM', ids: ['pop-shine', 'edm-hook', 'shimmer-hook', 'saw-hook'] },
  { label: 'World / Cinematic', ids: ['cinematic-pad-lead', 'retrowave'] },
];

export function waveLeafPreset(id: WaveLeafPresetId): WaveLeafPreset {
  return WAVE_LEAF_PRESETS[id];
}

export function waveLeafNormalizePresetId(raw: string | null | undefined): WaveLeafPresetId {
  if (raw && raw in WAVE_LEAF_PRESETS) return raw as WaveLeafPresetId;
  return WAVE_LEAF_DEFAULT_PRESET;
}

/**
 * Bank index for a preset — skips "All Leads" (index 0 lists every id, so findIndex always hits 0).
 * Used only for initial UI; picking a sound must not jump banks (see WaveLeafSynthPanel).
 */
export function waveLeafPresetBankIndex(
  presetId: WaveLeafPresetId,
  preferBankIdx?: number,
): number {
  if (
    preferBankIdx != null &&
    preferBankIdx >= 0 &&
    preferBankIdx < WAVE_LEAF_PRESET_GROUPS.length &&
    WAVE_LEAF_PRESET_GROUPS[preferBankIdx]!.ids.includes(presetId)
  ) {
    return preferBankIdx;
  }
  for (let i = 1; i < WAVE_LEAF_PRESET_GROUPS.length; i += 1) {
    if (WAVE_LEAF_PRESET_GROUPS[i]!.ids.includes(presetId)) return i;
  }
  return 0;
}

/** Pad tap / preview keys — legato Moog & flute need longer hold than pluck one-shots. */
export function waveLeafPresetPreviewHoldBeats(p: WaveLeafPreset): number {
  if (p.sampleLickId?.trim()) return 0.45;
  if (p.ampSustain >= 0.72 && p.ampRelease >= 0.45) return 1.4;
  if (p.ampSustain >= 0.65 && p.glideMs >= 70) return 1.15;
  return 0.45;
}

export type WaveLeafPresetBackdropHighlight = 'both' | 'guitar' | 'flute' | 'moog';

export function waveLeafPresetBackdropHighlight(bankLabel: string): WaveLeafPresetBackdropHighlight {
  if (bankLabel.includes('Guitar')) return 'guitar';
  if (bankLabel.includes('Flute')) return 'flute';
  if (bankLabel.includes('Moog')) return 'moog';
  return 'both';
}
