/**
 * Geno Ultra — factory-derived preset bank (variations from core factory sounds).
 */
import {
  genoUltraDefaultModSlots,
  GENO_ULTRA_FX_DEFAULTS,
  type GenoUltraFxParams,
  type GenoUltraModSlot,
  type GenoUltraOscParams,
  type GenoUltraSynthVoiceParams,
} from '@/app/lib/studio/genoUltraSynthTypes';

type VoicePatch = Partial<
  Omit<GenoUltraSynthVoiceParams, 'osc1' | 'osc2' | 'osc3' | 'fx' | 'modSlots' | 'id' | 'label' | 'category'>
> & {
  osc1?: Partial<GenoUltraOscParams>;
  osc2?: Partial<GenoUltraOscParams>;
  osc3?: Partial<GenoUltraOscParams>;
  fx?: Partial<GenoUltraFxParams>;
  modSlots?: readonly GenoUltraModSlot[];
};

function cloneVoice(v: GenoUltraSynthVoiceParams): GenoUltraSynthVoiceParams {
  return {
    ...v,
    modSlots: v.modSlots.map((s) => ({ ...s })),
    fx: { ...v.fx },
    osc1: { ...v.osc1 },
    osc2: { ...v.osc2 },
    osc3: { ...v.osc3 },
  };
}

function findBase(factory: readonly GenoUltraSynthVoiceParams[], id: string): GenoUltraSynthVoiceParams {
  return factory.find((p) => p.id === id) ?? factory[0]!;
}

function derive(
  factory: readonly GenoUltraSynthVoiceParams[],
  baseId: string,
  id: string,
  label: string,
  category: GenoUltraSynthVoiceParams['category'],
  patch: VoicePatch,
): GenoUltraSynthVoiceParams {
  const v = cloneVoice(findBase(factory, baseId));
  const { osc1, osc2, osc3, fx, modSlots, ...rest } = patch;
  Object.assign(v, rest, { id, label, category });
  if (osc1) v.osc1 = { ...v.osc1, ...osc1 };
  if (osc2) v.osc2 = { ...v.osc2, ...osc2 };
  if (osc3) v.osc3 = { ...v.osc3, ...osc3 };
  if (fx) v.fx = { ...v.fx, ...fx };
  if (modSlots) v.modSlots = modSlots.map((s) => ({ ...s }));
  return v;
}

type DerivedSpec = {
  baseId: string;
  id: string;
  label: string;
  category: GenoUltraSynthVoiceParams['category'];
  patch: VoicePatch;
};

const DERIVED_SPECS: DerivedSpec[] = [
  // Bass
  { baseId: 'ultra-sub-808', id: 'ultra-dub-sub', label: 'Dub Sub', category: 'bass', patch: { subLevel: 0.88, filterCutoffHz: 160, filterDrive: 0.12, ampDecayMs: 680, fx: { ...GENO_ULTRA_FX_DEFAULTS, delayMix: 0.42, delayTimeMs: 420, delayFeedback: 0.38, reverbMix: 0.18 } } },
  { baseId: 'ultra-reese-wide', id: 'ultra-phase-bass', label: 'Phase Bass', category: 'bass', patch: { filterMode: 'bandpass', filterCutoffHz: 520, filterResonanceQ: 2.1, lfo1Depth: 0.62, modSlots: [{ source: 'lfo1', dest: 'filterCutoff', amount: 0.72 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-rubber-funk', id: 'ultra-slap-house', label: 'Slap House', category: 'bass', patch: { osc1: { wave: 'square', pwm: 0.22 }, filterCutoffHz: 780, ampAttackMs: 1, ampDecayMs: 190, ampSustain: 0.45, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.15 } } },
  { baseId: 'ultra-deep-roller', id: 'ultra-warehouse', label: 'Warehouse', category: 'bass', patch: { filterDrive: 0.48, filterCutoffHz: 420, noiseLevel: 0.04, ampAttackMs: 8, fx: { ...GENO_ULTRA_FX_DEFAULTS, delayMix: 0.35, delayTimeMs: 240, eqLowDb: 4.5, eqLoMidDb: -2 } } },
  { baseId: 'ultra-moog-bass', id: 'ultra-boogie-bass', label: 'Boogie Bass', category: 'bass', patch: { osc2: { level: 0.38, semitone: 12 }, filterCutoffHz: 680, filterResonanceQ: 1.25, ampDecayMs: 320, ampSustain: 0.55, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.82 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-growl-808', id: 'ultra-trap-sub', label: 'Trap Sub', category: 'bass', patch: { subLevel: 0.95, filterDrive: 0.62, ampDecayMs: 380, ampReleaseMs: 160, fx: { ...GENO_ULTRA_FX_DEFAULTS, eqLowDb: 6, eqHiMidDb: -3 } } },
  { baseId: 'ultra-pluck-bass', id: 'ultra-brass-bass', label: 'Brass Bass', category: 'bass', patch: { ampAttackMs: 18, ampDecayMs: 420, ampSustain: 0.58, filterCutoffHz: 1100, filterResonanceQ: 1.1, osc2: { level: 0.52, semitone: -7 } } },
  { baseId: 'ultra-reese-wide', id: 'ultra-wobble-bass', label: 'Wobble Bass', category: 'bass', patch: { lfo1RateHz: 1.8, lfo1Depth: 0.85, filterResonanceQ: 2.4, modSlots: [{ source: 'lfo1', dest: 'filterCutoff', amount: 0.92 }, { source: 'lfo1', dest: 'filterRes', amount: 0.35 }, ...genoUltraDefaultModSlots().slice(2)] } },
  // Twilight 22 Siberian Nights — punchy poppy 80s techno Moog bass (1984)
  {
    baseId: 'ultra-moog-bass',
    id: 'ultra-siberian-moog',
    label: 'Siberian Moog',
    category: 'bass',
    patch: {
      osc1: { wave: 'saw', level: 0.8 },
      osc2: { wave: 'square', level: 0.26, semitone: -12 },
      subLevel: 0.5,
      filterCutoffHz: 780,
      filterResonanceQ: 1.62,
      filterDrive: 0.46,
      filterKeyTrack: 0.42,
      ampAttackMs: 1,
      ampDecayMs: 165,
      ampSustain: 0.32,
      ampReleaseMs: 75,
      filterAttackMs: 1,
      filterDecayMs: 195,
      filterSustain: 0.18,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.92 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.38 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        chorusMix: 0.1,
        delayMix: 0.14,
        delayTimeMs: 210,
        delayFeedback: 0.22,
        eqLowDb: 4.5,
        eqLoMidDb: 2.5,
        eqHiMidDb: -1.5,
      },
    },
  },
  // Twilight 22 Electric Kingdom — ARP Odyssey live electro bass (1984)
  {
    baseId: 'ultra-moog-bass',
    id: 'ultra-kingdom-bass',
    label: 'Kingdom Bass',
    category: 'bass',
    patch: {
      osc1: { wave: 'saw', level: 0.64 },
      osc2: { level: 0.32, semitone: -12 },
      subLevel: 0.42,
      filterCutoffHz: 540,
      filterResonanceQ: 1.35,
      filterKeyTrack: 0.48,
      ampAttackMs: 5,
      ampDecayMs: 260,
      ampSustain: 0.58,
      ampReleaseMs: 110,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.78 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.22 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        delayMix: 0.2,
        delayTimeMs: 280,
        delayFeedback: 0.28,
        eqLowDb: 5,
        eqLoMidDb: 1.5,
      },
    },
  },
  // Leads
  { baseId: 'ultra-hook-lead', id: 'ultra-neon-lead', label: 'Neon Lead', category: 'lead', patch: { filterCutoffHz: 7800, filterResonanceQ: 1.4, fx: { ...GENO_ULTRA_FX_DEFAULTS, delayMix: 0.38, delayTimeMs: 260, eqHiMidDb: 4, eqHighDb: 3 } } },
  { baseId: 'ultra-velvet-lead', id: 'ultra-dream-lead', label: 'Dream Lead', category: 'lead', patch: { unisonVoices: 4, ampAttackMs: 120, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.45, chorusMix: 0.35, delayMix: 0.28, delayTimeMs: 480 } } },
  { baseId: 'ultra-warm-lead', id: 'ultra-chorus-lead', label: 'Chorus Lead', category: 'lead', patch: { osc2: { level: 0.55, wave: 'triangle' }, unisonVoices: 3, unisonDetuneCents: 12, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.42, chorusRateHz: 0.55 } } },
  { baseId: 'ultra-analog-memory', id: 'ultra-porta-lead', label: 'Porta Lead', category: 'lead', patch: { ampAttackMs: 85, filterCutoffHz: 5200, filterKeyTrack: 0.65, lfo1Depth: 0.55, modSlots: [{ source: 'lfo1', dest: 'osc1Pitch', amount: 0.12 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-supersaw-hook', id: 'ultra-bright-hook', label: 'Bright Hook', category: 'lead', patch: { filterCutoffHz: 9200, outputLevel: 0.52, fx: { ...GENO_ULTRA_FX_DEFAULTS, eqHighDb: 5.5, delayMix: 0.32 } } },
  { baseId: 'ultra-laser-lead', id: 'ultra-wire-lead', label: 'Wire Lead', category: 'lead', patch: { osc1: { wave: 'square', level: 0.58, pwm: 0.18 }, osc2: { level: 0.22 }, filterCutoffHz: 9800, filterResonanceQ: 1.6 } },
  { baseId: 'ultra-soft-saw-lead', id: 'ultra-mellow-lead', label: 'Mellow Lead', category: 'lead', patch: { filterCutoffHz: 2400, filterResonanceQ: 0.35, ampAttackMs: 95, ampSustain: 0.88, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.32 } } },
  { baseId: 'ultra-hook-lead', id: 'ultra-sync-lead', label: 'Sync Lead', category: 'lead', patch: { osc3: { wave: 'square', level: 0.42, semitone: 19 }, filterDrive: 0.28, modSlots: [{ source: 'velocity', dest: 'filterCutoff', amount: 0.48 }, { source: 'lfo2', dest: 'osc2Pitch', amount: 0.22 }, ...genoUltraDefaultModSlots().slice(2)] } },
  // Plucks
  {
    baseId: 'ultra-marimba-pluck',
    id: 'ultra-uke-pluck',
    label: 'Uke Pluck',
    category: 'pluck',
    patch: {
      osc1: { wave: 'triangle', level: 0.6 },
      osc2: { wave: 'triangle', semitone: 7, level: 0.42, fineCents: 2 },
      filterCutoffHz: 6200,
      filterResonanceQ: 0.95,
      filterKeyTrack: 0.52,
      filterAttackMs: 1,
      filterDecayMs: 76,
      filterSustain: 0.08,
      ampAttackMs: 1,
      ampDecayMs: 250,
      ampSustain: 0,
      ampReleaseMs: 155,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.82 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.18 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.1, eqLoMidDb: 1.5, reverbMix: 0.14 },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-guitar-pluck',
    label: 'Guitar Pluck',
    category: 'pluck',
    patch: {
      osc1: { wave: 'triangle', level: 0.62 },
      osc2: { wave: 'sine', level: 0.28, semitone: 12 },
      filterCutoffHz: 5800,
      filterResonanceQ: 1.15,
      filterKeyTrack: 0.54,
      filterAttackMs: 1,
      filterDecayMs: 92,
      filterSustain: 0.1,
      ampAttackMs: 1,
      ampDecayMs: 300,
      ampSustain: 0.04,
      ampReleaseMs: 150,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.86 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.22 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: { ...GENO_ULTRA_FX_DEFAULTS, eqLoMidDb: 1.8, reverbMix: 0.12 },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-wah-guitar',
    label: 'Wah Guitar',
    category: 'pluck',
    patch: {
      osc1: { wave: 'triangle', level: 0.54 },
      osc2: { wave: 'saw', level: 0.34, semitone: 0, fineCents: 5 },
      osc3: { wave: 'sine', level: 0.12, semitone: 12, fineCents: 0 },
      unisonVoices: 1,
      filterCutoffHz: 3200,
      filterResonanceQ: 2.4,
      filterKeyTrack: 0.46,
      filterAttackMs: 4,
      filterDecayMs: 195,
      filterSustain: 0.16,
      ampAttackMs: 2,
      ampDecayMs: 540,
      ampSustain: 0.1,
      ampReleaseMs: 340,
      lfo1RateHz: 2.35,
      lfo1Shape: 'sine',
      lfo1Depth: 0.94,
      lfo2RateHz: 0.36,
      lfo2Shape: 'sine',
      lfo2Depth: 0.4,
      modSlots: [
        { source: 'lfo1', dest: 'filterCutoff', amount: 0.98 },
        { source: 'lfo2', dest: 'filterRes', amount: 0.55 },
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.45 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.24 },
        ...genoUltraDefaultModSlots().slice(4),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        delayMix: 0.5,
        delayTimeMs: 505,
        delayFeedback: 0.48,
        chorusMix: 0.06,
        reverbMix: 0.08,
        eqLoMidDb: 2.8,
        eqHiMidDb: 3.2,
      },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-wah-funk',
    label: 'Funk Wah',
    category: 'pluck',
    patch: {
      osc1: { wave: 'triangle', level: 0.52 },
      osc2: { wave: 'saw', level: 0.38, semitone: -7, fineCents: 3 },
      osc3: { wave: 'sine', level: 0.16, semitone: 0, fineCents: 0 },
      unisonVoices: 1,
      filterCutoffHz: 2800,
      filterResonanceQ: 2.15,
      filterKeyTrack: 0.42,
      filterAttackMs: 5,
      filterDecayMs: 220,
      filterSustain: 0.2,
      ampAttackMs: 3,
      ampDecayMs: 620,
      ampSustain: 0.12,
      ampReleaseMs: 420,
      lfo1RateHz: 1.45,
      lfo1Shape: 'sine',
      lfo1Depth: 0.88,
      lfo2RateHz: 0.28,
      lfo2Shape: 'triangle',
      lfo2Depth: 0.35,
      modSlots: [
        { source: 'lfo1', dest: 'filterCutoff', amount: 0.94 },
        { source: 'lfo2', dest: 'filterRes', amount: 0.48 },
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.38 },
        { source: 'velocity', dest: 'ampLevel', amount: 0.28 },
        ...genoUltraDefaultModSlots().slice(4),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        delayMix: 0.46,
        delayTimeMs: 680,
        delayFeedback: 0.52,
        chorusMix: 0.1,
        reverbMix: 0.12,
        eqLowDb: 1.5,
        eqLoMidDb: 3.5,
        eqHiMidDb: 2.4,
      },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-wah-cry',
    label: 'Cry Wah',
    category: 'pluck',
    patch: {
      osc1: { wave: 'triangle', level: 0.48 },
      osc2: { wave: 'saw', level: 0.42, semitone: 0, fineCents: 8 },
      osc3: { wave: 'triangle', level: 0.18, semitone: 12, fineCents: -3 },
      unisonVoices: 1,
      filterCutoffHz: 4400,
      filterResonanceQ: 2.85,
      filterKeyTrack: 0.52,
      filterAttackMs: 2,
      filterDecayMs: 145,
      filterSustain: 0.12,
      ampAttackMs: 1,
      ampDecayMs: 480,
      ampSustain: 0.08,
      ampReleaseMs: 280,
      lfo1RateHz: 3.85,
      lfo1Shape: 'sine',
      lfo1Depth: 0.96,
      lfo2RateHz: 0.62,
      lfo2Shape: 'sine',
      lfo2Depth: 0.52,
      modSlots: [
        { source: 'lfo1', dest: 'filterCutoff', amount: 1 },
        { source: 'lfo2', dest: 'filterRes', amount: 0.62 },
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.52 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.32 },
        ...genoUltraDefaultModSlots().slice(4),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        delayMix: 0.38,
        delayTimeMs: 320,
        delayFeedback: 0.4,
        chorusMix: 0.04,
        reverbMix: 0.06,
        eqHiMidDb: 4,
        eqHighDb: 2.8,
      },
    },
  },
  { baseId: 'ultra-mallet-pop', id: 'ultra-digi-pluck', label: 'Digi Pluck', category: 'pluck', patch: { osc1: { wave: 'triangle', level: 0.32 }, osc2: { wave: 'sine', level: 0.68 }, filterCutoffHz: 7600, filterResonanceQ: 1.55, filterAttackMs: 0, filterDecayMs: 48, filterSustain: 0, ampDecayMs: 118, ampReleaseMs: 72, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.98 }, ...genoUltraDefaultModSlots().slice(1)], fx: { ...GENO_ULTRA_FX_DEFAULTS, delayMix: 0.18, delayTimeMs: 160, eqHiMidDb: 2.5 } } },
  { baseId: 'ultra-koto-strike', id: 'ultra-sitar-pluck', label: 'Sitar Pluck', category: 'pluck', patch: { osc2: { semitone: 5, fineCents: 14, level: 0.24 }, filterCutoffHz: 5600, filterAttackMs: 1, filterDecayMs: 62, filterSustain: 0.05, noiseLevel: 0.055, ampDecayMs: 195, ampReleaseMs: 92, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.94 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-bell-spark', id: 'ultra-chime-pluck', label: 'Chime Pluck', category: 'pluck', patch: { osc3: { level: 0.48, semitone: 24 }, filterCutoffHz: 9600, filterAttackMs: 1, filterDecayMs: 155, filterSustain: 0.09, ampDecayMs: 480, ampReleaseMs: 520, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.58 }, ...genoUltraDefaultModSlots().slice(1)], fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.36, reverbDecay: 0.52, eqHighDb: 4 } } },
  { baseId: 'ultra-harp-spark', id: 'ultra-wood-pluck', label: 'Wood Pluck', category: 'pluck', patch: { osc1: { wave: 'triangle', level: 0.68 }, filterCutoffHz: 4500, filterAttackMs: 2, filterDecayMs: 92, filterSustain: 0.12, filterKeyTrack: 0.48, ampDecayMs: 380, ampSustain: 0.01, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.72 }, ...genoUltraDefaultModSlots().slice(1)], fx: { ...GENO_ULTRA_FX_DEFAULTS, eqLoMidDb: 2.5, reverbMix: 0.16 } } },
  // Keys
  { baseId: 'ultra-rhodes-keys', id: 'ultra-stage-keys', label: 'Stage Keys', category: 'keys', patch: { unisonVoices: 2, unisonDetuneCents: 6, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.32, reverbMix: 0.28, delayMix: 0.12 } } },
  { baseId: 'ultra-wurli-keys', id: 'ultra-vintage-keys', label: 'Vintage Keys', category: 'keys', patch: { filterDrive: 0.32, filterCutoffHz: 3600, ampDecayMs: 220, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.28, eqLoMidDb: 3 } } },
  { baseId: 'ultra-clav-digi', id: 'ultra-mark-keys', label: 'Mark Keys', category: 'keys', patch: { osc2: { level: 0.48, semitone: 12 }, filterCutoffHz: 6400, ampAttackMs: 0, ampDecayMs: 110, ampSustain: 0.28 } },
  { baseId: 'ultra-fm-bell-keys', id: 'ultra-celeste-keys', label: 'Celeste Keys', category: 'keys', patch: { osc3: { semitone: 19, level: 0.52 }, filterCutoffHz: 7800, ampDecayMs: 420, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.35 } } },
  { baseId: 'ultra-jazz-organ', id: 'ultra-lounge-organ', label: 'Lounge Organ', category: 'keys', patch: { filterCutoffHz: 2800, lfo1RateHz: 4.8, ampSustain: 0.92, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.25, reverbMix: 0.22 } } },
  { baseId: 'ultra-grand-piano', id: 'ultra-ballad-keys', label: 'Ballad Keys', category: 'keys', patch: { ampAttackMs: 8, ampDecayMs: 380, ampSustain: 0.52, filterCutoffHz: 5200, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.38, reverbDecay: 0.52 } } },
  // Pads
  { baseId: 'ultra-silk-pad', id: 'ultra-choir-pad', label: 'Choir Pad', category: 'pad', patch: { osc3: { level: 0.42, semitone: 12 }, unisonVoices: 4, unisonDetuneCents: 16, ampAttackMs: 620, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.38, reverbMix: 0.52 } } },
  { baseId: 'ultra-air-pad', id: 'ultra-string-pad', label: 'String Pad', category: 'pad', patch: { osc1: { wave: 'saw', level: 0.42 }, filterCutoffHz: 1800, ampAttackMs: 880, ampReleaseMs: 1200, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.48 } } },
  { baseId: 'ultra-dark-cine', id: 'ultra-sci-fi-pad', label: 'Sci-Fi Pad', category: 'pad', patch: { filterMode: 'bandpass', filterCutoffHz: 980, lfo2Depth: 0.48, modSlots: [{ source: 'lfo2', dest: 'filterCutoff', amount: 0.55 }, ...genoUltraDefaultModSlots().slice(1)], fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.55, delayMix: 0.25 } } },
  { baseId: 'ultra-silk-pad', id: 'ultra-warm-pad', label: 'Warm Pad', category: 'pad', patch: { filterCutoffHz: 1600, subLevel: 0.28, ampSustain: 0.9, fx: { ...GENO_ULTRA_FX_DEFAULTS, eqLowDb: 3, chorusMix: 0.22 } } },
  { baseId: 'ultra-air-pad', id: 'ultra-shimmer-pad', label: 'Shimmer Pad', category: 'pad', patch: { osc3: { level: 0.48, semitone: 19 }, filterCutoffHz: 4200, noiseLevel: 0.06, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.45, eqHighDb: 4 } } },
  // FX / special
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-cinema-rise',
    label: 'Cinema Rise',
    category: 'fx',
    patch: {
      osc1: { wave: 'saw', level: 0.44 },
      osc2: { wave: 'triangle', level: 0.36, semitone: 12 },
      osc3: { wave: 'sine', level: 0.3, semitone: 19 },
      noiseLevel: 0.2,
      unisonVoices: 4,
      unisonDetuneCents: 20,
      filterCutoffHz: 620,
      filterResonanceQ: 1.38,
      filterKeyTrack: 0.18,
      filterAttackMs: 3100,
      filterDecayMs: 380,
      filterSustain: 0.9,
      filterReleaseMs: 950,
      ampAttackMs: 3500,
      ampDecayMs: 260,
      ampSustain: 0.94,
      ampReleaseMs: 1200,
      modSlots: [
        { source: 'ampEnv', dest: 'osc1Pitch', amount: 0.54 },
        { source: 'ampEnv', dest: 'osc2Pitch', amount: 0.48 },
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.78 },
        ...genoUltraDefaultModSlots().slice(3),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.6,
        reverbDecay: 0.74,
        delayMix: 0.2,
        delayTimeMs: 360,
        eqLoMidDb: 1.5,
        eqHighDb: 3.8,
      },
      outputLevel: 0.58,
    },
  },
  {
    baseId: 'ultra-air-pad',
    id: 'ultra-grand-rise',
    label: 'Grand Rise',
    category: 'fx',
    patch: {
      osc1: { wave: 'saw', level: 0.56 },
      osc2: { wave: 'saw', level: 0.46, semitone: 7 },
      osc3: { wave: 'triangle', level: 0.34, semitone: 12 },
      noiseLevel: 0.15,
      unisonVoices: 5,
      unisonDetuneCents: 24,
      filterCutoffHz: 480,
      filterResonanceQ: 1.72,
      filterDrive: 0.24,
      filterAttackMs: 2300,
      filterDecayMs: 440,
      filterSustain: 0.92,
      filterReleaseMs: 820,
      ampAttackMs: 2700,
      ampDecayMs: 300,
      ampSustain: 0.9,
      ampReleaseMs: 950,
      modSlots: [
        { source: 'ampEnv', dest: 'osc1Pitch', amount: 0.62 },
        { source: 'ampEnv', dest: 'osc3Pitch', amount: 0.44 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.18 },
        ...genoUltraDefaultModSlots().slice(3),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.54,
        reverbDecay: 0.7,
        chorusMix: 0.2,
        eqHiMidDb: 2.8,
        eqHighDb: 5.2,
      },
      outputLevel: 0.62,
    },
  },
  { baseId: 'ultra-acid-line', id: 'ultra-riser-fx', label: 'Riser FX', category: 'fx', patch: { ampAttackMs: 1200, ampDecayMs: 400, ampSustain: 0.75, filterCutoffHz: 2200, modSlots: [{ source: 'ampEnv', dest: 'filterCutoff', amount: 0.65 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-acid-line', id: 'ultra-noise-sweep', label: 'Noise Sweep', category: 'fx', patch: { noiseLevel: 0.22, osc1: { level: 0.35 }, filterMode: 'highpass', filterCutoffHz: 800, lfo2Depth: 0.72, modSlots: [{ source: 'lfo2', dest: 'filterCutoff', amount: 0.88 }, ...genoUltraDefaultModSlots().slice(1)] } },
  { baseId: 'ultra-acid-line', id: 'ultra-stab-fx', label: 'Stab FX', category: 'fx', patch: { ampAttackMs: 1, ampDecayMs: 120, ampSustain: 0, ampReleaseMs: 80, filterResonanceQ: 3.2, filterCutoffHz: 1800 } },
  { baseId: 'ultra-dark-cine', id: 'ultra-ghost-fx', label: 'Ghost FX', category: 'fx', patch: { noiseLevel: 0.12, filterCutoffHz: 680, ampAttackMs: 400, ampSustain: 0.35, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.62, delayMix: 0.45, delayTimeMs: 520 } } },
  { baseId: 'ultra-acid-line', id: 'ultra-crush-fx', label: 'Crush FX', category: 'fx', patch: { filterDrive: 0.78, filterResonanceQ: 3.5, osc1: { wave: 'square', pwm: 0.15 }, fx: { ...GENO_ULTRA_FX_DEFAULTS, eqHiMidDb: 6, eqHighDb: 4 } } },
  // Extra variety (fill to ~38)
  { baseId: 'ultra-warm-lead', id: 'ultra-glow-lead', label: 'Glow Lead', category: 'lead', patch: { osc3: { level: 0.32, semitone: 12 }, filterCutoffHz: 4800, lfo1Depth: 0.48, fx: { ...GENO_ULTRA_FX_DEFAULTS, delayMix: 0.3, chorusMix: 0.28 } } },
  { baseId: 'ultra-sub-808', id: 'ultra-cinema-sub', label: 'Cinema Sub', category: 'bass', patch: { subLevel: 0.78, filterCutoffHz: 140, ampAttackMs: 35, ampReleaseMs: 680, fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.28, delayMix: 0.18 } } },
  { baseId: 'ultra-pluck-glass', id: 'ultra-crystal-pluck', label: 'Crystal Pluck', category: 'pluck', patch: { filterCutoffHz: 9200, filterResonanceQ: 1.15, filterAttackMs: 1, filterDecayMs: 125, filterSustain: 0.11, filterKeyTrack: 0.6, osc2: { semitone: 19, level: 0.36, wave: 'sine' }, ampDecayMs: 360, ampSustain: 0.02, ampReleaseMs: 190, modSlots: [{ source: 'filterEnv', dest: 'filterCutoff', amount: 0.82 }, { source: 'velocity', dest: 'filterCutoff', amount: 0.35 }, ...genoUltraDefaultModSlots().slice(2)], fx: { ...GENO_ULTRA_FX_DEFAULTS, reverbMix: 0.22, eqHighDb: 4.5 } } },
  { baseId: 'ultra-rhodes-keys', id: 'ultra-comp-keys', label: 'Comp Keys', category: 'keys', patch: { filterDrive: 0.18, ampAttackMs: 2, ampSustain: 0.62, fx: { ...GENO_ULTRA_FX_DEFAULTS, chorusMix: 0.2, eqLoMidDb: 2.5 } } },
  // Horror / cinematic arp keys (Computer Age family)
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-horror-keys',
    label: 'Horror Keys',
    category: 'keys',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 720,
      filterResonanceQ: 2.1,
      filterDrive: 0.22,
      osc1: { wave: 'saw', level: 0.42 },
      osc2: { wave: 'triangle', level: 0.38, semitone: -5 },
      osc3: { wave: 'sine', level: 0.18, semitone: 6 },
      subLevel: 0.24,
      noiseLevel: 0.045,
      ampAttackMs: 3,
      ampDecayMs: 260,
      ampSustain: 0.12,
      ampReleaseMs: 240,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.58 },
        { source: 'velocity', dest: 'filterCutoff', amount: 0.22 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.58,
        reverbDecay: 0.82,
        delayMix: 0.34,
        delayTimeMs: 420,
        delayFeedback: 0.32,
        eqHighDb: -5.5,
        eqHiMidDb: -2.5,
        eqLowDb: 4,
      },
    },
  },
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-dread-lead',
    label: 'Dread Lead',
    category: 'lead',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 580,
      filterResonanceQ: 2.6,
      osc1: { wave: 'square', level: 0.36, pwm: 0.12 },
      osc2: { wave: 'saw', level: 0.32, semitone: -7 },
      osc3: { level: 0.14, semitone: 3 },
      subLevel: 0.3,
      noiseLevel: 0.06,
      ampAttackMs: 2,
      ampDecayMs: 220,
      ampSustain: 0.08,
      ampReleaseMs: 190,
      lfo2RateHz: 0.35,
      lfo2Depth: 0.42,
      modSlots: [
        { source: 'lfo2', dest: 'filterCutoff', amount: 0.48 },
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.52 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.62,
        reverbDecay: 0.88,
        delayMix: 0.38,
        delayTimeMs: 480,
        eqHighDb: -6,
        eqHiMidDb: -3,
        eqLowDb: 5,
      },
    },
  },
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-haunt-keys',
    label: 'Haunt Keys',
    category: 'keys',
    patch: {
      filterCutoffHz: 840,
      filterResonanceQ: 1.65,
      osc2: { semitone: -5, level: 0.44, wave: 'triangle' },
      osc3: { semitone: -12, level: 0.2 },
      subLevel: 0.32,
      noiseLevel: 0.035,
      ampAttackMs: 5,
      ampDecayMs: 310,
      ampSustain: 0.1,
      ampReleaseMs: 280,
      unisonVoices: 2,
      unisonDetuneCents: 18,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.48 },
        ...genoUltraDefaultModSlots().slice(1),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.55,
        reverbDecay: 0.76,
        chorusMix: 0.12,
        delayMix: 0.28,
        delayTimeMs: 360,
        eqHighDb: -4.5,
        eqLoMidDb: 1.5,
        eqLowDb: 3.5,
      },
    },
  },
  {
    baseId: 'ultra-acid-line',
    id: 'ultra-evil-arp',
    label: 'Evil Arp',
    category: 'fx',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 620,
      filterResonanceQ: 3.1,
      filterDrive: 0.32,
      osc1: { wave: 'saw', level: 0.62 },
      osc2: { wave: 'square', level: 0.12, semitone: -5 },
      noiseLevel: 0.05,
      subLevel: 0.2,
      ampAttackMs: 1,
      ampDecayMs: 180,
      ampSustain: 0,
      ampReleaseMs: 120,
      lfo2RateHz: 0.55,
      lfo2Depth: 0.38,
      modSlots: [
        { source: 'lfo2', dest: 'filterCutoff', amount: 0.62 },
        { source: 'lfo2', dest: 'filterRes', amount: 0.28 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.48,
        reverbDecay: 0.7,
        delayMix: 0.22,
        delayTimeMs: 290,
        eqHighDb: -5,
        eqHiMidDb: -2,
        eqLowDb: 4.5,
      },
    },
  },
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-shock-keys',
    label: 'Shock Keys',
    category: 'keys',
    patch: {
      filterMode: 'lowpass',
      filterCutoffHz: 960,
      filterResonanceQ: 1.9,
      filterDrive: 0.15,
      osc1: { wave: 'triangle', level: 0.52 },
      osc2: { wave: 'saw', level: 0.28, semitone: -8 },
      noiseLevel: 0.055,
      subLevel: 0.26,
      ampAttackMs: 2,
      ampDecayMs: 240,
      ampSustain: 0.06,
      ampReleaseMs: 200,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.65 },
        { source: 'velocity', dest: 'ampLevel', amount: 0.35 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.52,
        reverbDecay: 0.8,
        delayMix: 0.36,
        delayTimeMs: 440,
        eqHighDb: -4,
        eqHiMidDb: -1.5,
        eqLowDb: 3,
      },
    },
  },
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-phantom-stab',
    label: 'Phantom Stab',
    category: 'fx',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 680,
      filterResonanceQ: 2.85,
      osc1: { wave: 'square', level: 0.48, pwm: 0.08 },
      osc2: { wave: 'saw', level: 0.22, semitone: -5 },
      osc3: { level: 0.16, semitone: 7 },
      noiseLevel: 0.07,
      subLevel: 0.28,
      ampAttackMs: 1,
      ampDecayMs: 200,
      ampSustain: 0,
      ampReleaseMs: 160,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.72 },
        { source: 'filterEnv', dest: 'filterRes', amount: 0.35 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.64,
        reverbDecay: 0.85,
        delayMix: 0.4,
        delayTimeMs: 510,
        delayFeedback: 0.36,
        eqHighDb: -5.5,
        eqHiMidDb: -2,
        eqLowDb: 4.5,
      },
    },
  },
  // Slasher horror — dark pluck with legato slide between syncopated chord arp notes
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-michael-pluck',
    label: 'Michael Pluck',
    category: 'pluck',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 880,
      filterResonanceQ: 1.55,
      filterDrive: 0.18,
      osc1: { wave: 'triangle', level: 0.48 },
      osc2: { wave: 'saw', level: 0.28, semitone: -5 },
      osc3: { level: 0.14, semitone: 6 },
      subLevel: 0.38,
      noiseLevel: 0.03,
      ampAttackMs: 5,
      ampDecayMs: 480,
      ampSustain: 0.24,
      ampReleaseMs: 320,
      filterAttackMs: 2,
      filterDecayMs: 420,
      filterSustain: 0.16,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.68 },
        { source: 'lfo1', dest: 'osc1Pitch', amount: 0.05 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.5,
        reverbDecay: 0.78,
        delayMix: 0.3,
        delayTimeMs: 380,
        eqHighDb: -5.5,
        eqHiMidDb: -2,
        eqLowDb: 4.5,
      },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-camp-pluck',
    label: 'Camp Pluck',
    category: 'pluck',
    patch: {
      filterCutoffHz: 720,
      filterResonanceQ: 1.35,
      osc1: { wave: 'saw', level: 0.44 },
      osc2: { wave: 'square', level: 0.18, semitone: -7, pwm: 0.1 },
      subLevel: 0.42,
      noiseLevel: 0.04,
      ampAttackMs: 4,
      ampDecayMs: 440,
      ampSustain: 0.22,
      ampReleaseMs: 300,
      filterAttackMs: 1,
      filterDecayMs: 380,
      filterSustain: 0.14,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.62 },
        ...genoUltraDefaultModSlots().slice(1),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.46,
        reverbDecay: 0.72,
        delayMix: 0.26,
        delayTimeMs: 340,
        eqHighDb: -6,
        eqLowDb: 5,
      },
    },
  },
  {
    baseId: 'ultra-dark-cine',
    id: 'ultra-creep-pluck',
    label: 'Creep Pluck',
    category: 'pluck',
    patch: {
      filterMode: 'bandpass',
      filterCutoffHz: 640,
      filterResonanceQ: 2.2,
      osc1: { wave: 'triangle', level: 0.46 },
      osc2: { wave: 'triangle', level: 0.32, semitone: -5 },
      osc3: { level: 0.12, semitone: 1 },
      subLevel: 0.36,
      noiseLevel: 0.05,
      ampAttackMs: 6,
      ampDecayMs: 520,
      ampSustain: 0.26,
      ampReleaseMs: 360,
      filterAttackMs: 2,
      filterDecayMs: 460,
      filterSustain: 0.18,
      lfo1RateHz: 0.28,
      lfo1Depth: 0.32,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.58 },
        { source: 'lfo1', dest: 'filterCutoff', amount: 0.35 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.54,
        reverbDecay: 0.82,
        delayMix: 0.32,
        delayTimeMs: 410,
        eqHighDb: -5,
        eqHiMidDb: -2.5,
        eqLowDb: 4,
      },
    },
  },
  {
    baseId: 'ultra-pluck-glass',
    id: 'ultra-stab-pluck',
    label: 'Stab Pluck',
    category: 'pluck',
    patch: {
      filterCutoffHz: 960,
      filterResonanceQ: 1.75,
      filterDrive: 0.24,
      osc1: { wave: 'square', level: 0.38, pwm: 0.08 },
      osc2: { wave: 'saw', level: 0.34, semitone: -8 },
      osc3: { level: 0.2, semitone: 7 },
      subLevel: 0.34,
      noiseLevel: 0.045,
      ampAttackMs: 3,
      ampDecayMs: 400,
      ampSustain: 0.2,
      ampReleaseMs: 280,
      filterAttackMs: 1,
      filterDecayMs: 350,
      filterSustain: 0.12,
      modSlots: [
        { source: 'filterEnv', dest: 'filterCutoff', amount: 0.75 },
        { source: 'filterEnv', dest: 'filterRes', amount: 0.28 },
        ...genoUltraDefaultModSlots().slice(2),
      ],
      fx: {
        ...GENO_ULTRA_FX_DEFAULTS,
        reverbMix: 0.48,
        reverbDecay: 0.75,
        delayMix: 0.28,
        delayTimeMs: 360,
        eqHighDb: -4.5,
        eqLowDb: 3.5,
      },
    },
  },
];

export function buildGenoUltraDerivedPresets(
  factory: readonly GenoUltraSynthVoiceParams[],
): GenoUltraSynthVoiceParams[] {
  return DERIVED_SPECS.map((s) => derive(factory, s.baseId, s.id, s.label, s.category, s.patch));
}
