/**
 * Live Chord presets — batch 2: Drill, Lo-fi, Neo-Soul, Pop (~30 each).
 */
import type { ChordSymbol } from '@/app/lib/creationStation/chordBuilder';
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_DRILL_DEFS: Se2SynthGenoLivePresetDef[] = defs('drill', [
  {
    id: 'uk-dark',
    name: 'UK Dark',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bVI'],
    loop: ['bVI', 'bVII', 'i7', 'bVI', 'bVII', 'i7', 'iv7', 'bVII'],
  },
  {
    id: 'chicago-slide',
    name: 'Chicago Slide',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'ny-drill',
    name: 'NY Drill',
    tag: 'bVII lead',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'bVII', 'i7'],
    loop: ['bVII', 'bVI', 'bVII', 'i7', 'bVII', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'brooklyn-night',
    name: 'Brooklyn Night',
    tag: 'VI lead',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['VImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'VImaj7', 'i7'],
  },
  {
    id: 'grim-slide',
    name: 'Grim Slide',
    tag: 'harmonic',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'bVII'],
    loop: ['bVImaj7', 'V7', 'i7', 'bVII', 'bVImaj7', 'V7', 'iv7', 'i7'],
  },
  {
    id: 'cold-steel',
    name: 'Cold Steel',
    tag: 'iiø lead',
    mode: 'minor',
    romans: ['iiø7', 'bVII', 'i7', 'iv7'],
    loop: ['iiø7', 'bVII', 'i7', 'iv7', 'iiø7', 'i7', 'bVII', 'iv7'],
  },
  {
    id: 'menace-loop',
    name: 'Menace Loop',
    tag: 'bVII vamp',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'phrygian-drill',
    name: 'Phrygian Drill',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'i7', 'bVII', 'bIImaj7'],
  },
  {
    id: 'half-step-grit',
    name: 'Half-Step Grit',
    tag: 'chromatic',
    mode: 'minor',
    romans: ['bIImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bIImaj7', 'bVII', 'i7', 'iv7', 'bIImaj7', 'bVII', 'bVI', 'i7'],
  },
  {
    id: '808-menace',
    name: '808 Menace',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'bVI', 'bVII', 'iv7', 'V7'],
  },
  {
    id: 'dark-bounce',
    name: 'Dark Bounce',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'sliding-minor',
    name: 'Sliding Minor',
    tag: 'slide',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'i7', 'bVI'],
    loop: ['iv7', 'bVII', 'i7', 'bVI', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'drill-gospel',
    name: 'Drill Gospel',
    tag: 'iv turn',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'ice-palace',
    name: 'Ice Palace',
    tag: 'bVImaj7',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'night-raid',
    name: 'Night Raid',
    tag: 'V7 turn',
    mode: 'harmonicMinor',
    romans: ['V7', 'i7', 'bVI', 'bVII'],
    loop: ['V7', 'i7', 'bVI', 'bVII', 'V7', 'bVImaj7', 'i7', 'bVII'],
  },
  {
    id: 'sparse-menace',
    name: 'Sparse Menace',
    tag: 'bVII only',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'i7'],
    loop: ['bVII', 'i7', 'bVII', 'i7', 'bVII', 'bVI', 'i7', 'bVII'],
  },
  {
    id: 'dark-sample',
    name: 'Dark Sample',
    tag: 'VI flip',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'i7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'i7', 'VImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'drill-noir',
    name: 'Drill Noir',
    tag: 'bVImaj7',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'slime-drill',
    name: 'Slime Drill',
    tag: 'bIII lead',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'bVI', 'i7'],
    loop: ['bIIImaj7', 'bVII', 'bVI', 'i7', 'bIIImaj7', 'bVII', 'iv7', 'bVI'],
  },
  {
    id: 'drill-pain',
    name: 'Drill Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'iv7', 'bVII'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_LOFI_DEFS: Se2SynthGenoLivePresetDef[] = defs('lofi', [
  {
    id: 'dusty-vinyl',
    name: 'Dusty Vinyl',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'rainy-window',
    name: 'Rainy Window',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'study-beats',
    name: 'Study Beats',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'ii7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'coffee-shop',
    name: 'Coffee Shop',
    tag: 'ii lead',
    mode: 'dorian',
    romans: ['ii7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'tape-hiss',
    name: 'Tape Hiss',
    tag: 'bVII lead',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'iv7'],
    loop: ['bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVI', 'i7', 'bVII'],
  },
  {
    id: 'midnight-jazz',
    name: 'Midnight Jazz',
    tag: 'ii lead',
    mode: 'dorian',
    romans: ['ii7', 'bVIImaj7', 'IV7', 'i7'],
    loop: ['ii7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'soft-glow',
    name: 'Soft Glow',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'lazy-sunday',
    name: 'Lazy Sunday',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'bIIImaj7', 'i7', 'bVIImaj7'],
    loop: ['IV7', 'bIIImaj7', 'i7', 'bVIImaj7', 'ii7', 'IV7', 'i7', 'bIIImaj7'],
  },
  {
    id: 'nostalgia',
    name: 'Nostalgia',
    tag: 'VI lead',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['VImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'VImaj7', 'iv7'],
  },
  {
    id: 'bedroom-loop',
    name: 'Bedroom Loop',
    tag: 'bVII lead',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'iv7'],
    loop: ['bVII', 'bVI', 'i7', 'iv7', 'bVII', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'chill-dust',
    name: 'Chill Dust',
    tag: 'bVII lead',
    mode: 'dorian',
    romans: ['bVIImaj7', 'IV7', 'i7', 'ii7'],
    loop: ['bVIImaj7', 'IV7', 'i7', 'ii7', 'bVIImaj7', 'i7', 'IV7', 'ii7'],
  },
  {
    id: 'amber-light',
    name: 'Amber Light',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'bVImaj7', 'bVII', 'i7'],
    loop: ['iv7', 'bVImaj7', 'bVII', 'i7', 'iv7', 'bVII', 'bVImaj7', 'i7'],
  },
  {
    id: 'two-am',
    name: '2 AM',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'iv7'],
    loop: ['bVI', 'bVII', 'i7', 'iv7', 'bVImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'vinyl-crackle',
    name: 'Vinyl Crackle',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'ii7', 'i7', 'bVIImaj7'],
    loop: ['IV7', 'ii7', 'i7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'bVIImaj7'],
  },
  {
    id: 'haze',
    name: 'Haze',
    tag: 'bVII vamp',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'iv7', 'i7'],
    loop: ['bVII', 'bVI', 'iv7', 'i7', 'bVII', 'i7', 'bVI', 'iv7'],
  },
  {
    id: 'soft-rain',
    name: 'Soft Rain',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'i7', 'iv7'],
  },
  {
    id: 'dilla-dust',
    name: 'Dusty Flip',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'ii7', 'bVIImaj7'],
    loop: ['IV7', 'i7', 'ii7', 'bVIImaj7', 'IV7', 'ii7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'mellow-pad',
    name: 'Mellow Pad',
    tag: 'bVII lead',
    mode: 'minor',
    romans: ['bVII', 'iv7', 'i7', 'bVI'],
    loop: ['bVII', 'iv7', 'i7', 'bVI', 'bVII', 'bVImaj7', 'iv7', 'i7'],
  },
  {
    id: 'sunset-loop',
    name: 'Sunset Loop',
    tag: 'bIII lead',
    mode: 'dorian',
    romans: ['bIIImaj7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['bIIImaj7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'bIIImaj7', 'IV7', 'i7'],
  },
  {
    id: 'quiet-corner',
    name: 'Quiet Corner',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'bVImaj7', 'bVII', 'i7'],
  },
  {
    id: 'faded-photo',
    name: 'Faded Photo',
    tag: 'VI lead',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'i7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'i7', 'VImaj7', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'lofi-soul',
    name: 'Lo-Fi Soul',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'VImaj7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'VImaj7', 'bVII', 'i7', 'bVI', 'VImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'gentle-wave',
    name: 'Gentle Wave',
    tag: 'ii lead',
    mode: 'dorian',
    romans: ['ii7', 'i7', 'bVIImaj7', 'IV7'],
    loop: ['ii7', 'i7', 'bVIImaj7', 'IV7', 'ii7', 'bVIImaj7', 'i7', 'IV7'],
  },
  {
    id: 'old-radio',
    name: 'Old Radio',
    tag: 'bVII vamp',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'bVII'],
    loop: ['bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'cloud-nine',
    name: 'Cloud Nine',
    tag: 'bVII lead',
    mode: 'dorian',
    romans: ['bVIImaj7', 'IV7', 'bIIImaj7', 'i7'],
    loop: ['bVIImaj7', 'IV7', 'bIIImaj7', 'i7', 'ii7', 'bVIImaj7', 'IV7', 'i7'],
  },
  {
    id: 'warm-blanket',
    name: 'Warm Blanket',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'iv7', 'i7', 'bVII'],
    loop: ['bVI', 'iv7', 'i7', 'bVII', 'bVImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'study-hall',
    name: 'Study Hall',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVImaj7'],
  },
  {
    id: 'pink-noise',
    name: 'Pink Noise',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'IV7', 'bVIImaj7'],
    loop: ['IV7', 'i7', 'IV7', 'bVIImaj7', 'ii7', 'IV7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'slow-bloom',
    name: 'Slow Bloom',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'i7', 'bVII', 'iv7'],
    loop: ['bVImaj7', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7', 'bVImaj7'],
  },
  {
    id: 'last-cup',
    name: 'Last Cup',
    tag: 'bVII lead',
    mode: 'minor',
    romans: ['bVII', 'bVImaj7', 'iv7', 'i7'],
    loop: ['bVII', 'bVImaj7', 'iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_NEO_SOUL_DEFS: Se2SynthGenoLivePresetDef[] = defs('neo-soul', [
  {
    id: 'dangelo-vamp',
    name: 'Neo Vamp',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'ii7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'badu-dorian',
    name: 'Soft Dorian',
    tag: 'ii lead',
    mode: 'dorian',
    romans: ['ii7', 'bIIImaj7', 'IV7', 'bVIImaj7'],
    loop: ['ii7', 'bIIImaj7', 'IV7', 'bVIImaj7', 'i7', 'ii7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'maxwell-turn',
    name: 'Velvet Turn',
    tag: 'vi lead',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'iii7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'jill-scott',
    name: 'Warm Spoken',
    tag: 'ii lead',
    mode: 'dorian',
    romans: ['ii7', 'i7', 'IV7', 'bVIImaj7'],
    loop: ['ii7', 'i7', 'IV7', 'bVIImaj7', 'i7', 'ii7', 'bVIImaj7', 'IV7'],
  },
  {
    id: 'soulquarians',
    name: 'Collective Soul',
    tag: 'IV lead',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'ii7', 'bVIImaj7'],
    loop: ['IV7', 'i7', 'ii7', 'bVIImaj7', 'i7', 'IV7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'silk-turn',
    name: 'Silk Turn',
    tag: 'ii-V',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'neo-bridge',
    name: 'Neo Bridge',
    tag: 'vi start',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'quest-love',
    name: 'Pocket Groove',
    tag: 'bVII vamp',
    mode: 'dorian',
    romans: ['bVIImaj7', 'i7', 'IV7', 'ii7'],
    loop: ['bVIImaj7', 'i7', 'IV7', 'ii7', 'i7', 'bVIImaj7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'erykah-badu',
    name: 'Earth Tone',
    tag: 'bIII tint',
    mode: 'dorian',
    romans: ['bIIImaj7', 'i7', 'IV7', 'bVIImaj7'],
    loop: ['bIIImaj7', 'i7', 'IV7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bIIImaj7'],
  },
  {
    id: 'electric-church',
    name: 'Electric Church',
    tag: 'IV lead',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'iii7', 'vi7'],
    loop: ['IVmaj7', 'Imaj7', 'iii7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'warm-7th',
    name: 'Warm 7th',
    tag: 'ii start',
    mode: 'dorian',
    romans: ['ii7', 'i7', 'bVIImaj7', 'IV7'],
    loop: ['ii7', 'i7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'stank-face',
    name: 'Stank Face',
    tag: 'ii funk',
    mode: 'dorian',
    romans: ['ii7', 'IV7', 'bVIImaj7', 'i7'],
    loop: ['ii7', 'IV7', 'bVIImaj7', 'i7', 'ii7', 'bVIImaj7', 'IV7', 'ii7'],
  },
  {
    id: 'hammond-groove',
    name: 'Hammond Groove',
    tag: 'IV-ii',
    mode: 'dorian',
    romans: ['IV7', 'ii7', 'i7', 'bVIImaj7'],
    loop: ['IV7', 'ii7', 'i7', 'bVIImaj7', 'i7', 'IV7', 'ii7', 'IV7'],
  },
  {
    id: 'brown-sugar',
    name: 'Brown Sugar',
    tag: 'sugar',
    mode: 'dorian',
    romans: ['IV7', 'bIIImaj7', 'bVIImaj7', 'i7'],
    loop: ['IV7', 'bIIImaj7', 'bVIImaj7', 'i7', 'ii7', 'IV7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'moon-child',
    name: 'Moon Child',
    tag: 'borrowed',
    mode: 'dorian',
    romans: ['bVImaj7', 'bVIImaj7', 'IV7', 'i7'],
    loop: ['bVImaj7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'velvet-loop',
    name: 'Velvet Loop',
    tag: 'bVII lead',
    mode: 'dorian',
    romans: ['bVIImaj7', 'i7', 'IV7', 'ii7'],
    loop: ['bVIImaj7', 'i7', 'IV7', 'ii7', 'bVIImaj7', 'IV7', 'i7', 'ii7'],
  },
  {
    id: 'bilal-mood',
    name: 'Bilal Mood',
    tag: 'minor',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'neo-fall',
    name: 'Neo Fall',
    tag: 'vi start',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'iii7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'cissy-strut',
    name: 'Cissy Strut',
    tag: 'ii strut',
    mode: 'dorian',
    romans: ['ii7', 'bVIImaj7', 'IV7', 'i7'],
    loop: ['ii7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'midnight-soul',
    name: 'Midnight Soul',
    tag: 'bVII lead',
    mode: 'dorian',
    romans: ['bVIImaj7', 'ii7', 'i7', 'IV7'],
    loop: ['bVIImaj7', 'ii7', 'i7', 'IV7', 'ii7', 'bVIImaj7', 'IV7', 'i7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_POP_DEFS: Se2SynthGenoLivePresetDef[] = defs('pop', [
  {
    id: 'axis-hook',
    name: 'Axis Hook',
    tag: 'I-V-vi-IV',
    mode: 'major',
    romans: ['Imaj7', 'V7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7'],
  },
  {
    id: 'billboard-iv',
    name: 'Billboard IV',
    tag: 'IV-I-V-vi',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'vi7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'vi7', 'IVmaj7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'synth-ii',
    name: 'Synth ii',
    tag: 'ii-V-I-vi',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'stadium-v',
    name: 'Stadium V',
    tag: 'V-IV-I-vi',
    mode: 'major',
    romans: ['V7', 'IVmaj7', 'Imaj7', 'vi7'],
    loop: ['V7', 'IVmaj7', 'Imaj7', 'vi7', 'V7', 'vi7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'indie-iii',
    name: 'Indie iii',
    tag: 'iii-vi-IV-V',
    mode: 'major',
    romans: ['iii7', 'vi7', 'IVmaj7', 'V7'],
    loop: ['iii7', 'vi7', 'IVmaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'golden-iv',
    name: 'Golden IV',
    tag: 'IV-vi-I-V',
    mode: 'major',
    romans: ['IVmaj7', 'vi7', 'Imaj7', 'V7'],
    loop: ['IVmaj7', 'vi7', 'Imaj7', 'V7', 'IVmaj7', 'Imaj7', 'ii7', 'V7'],
  },
  {
    id: 'edm-v',
    name: 'EDM V',
    tag: 'V-vi-IV-I',
    mode: 'major',
    romans: ['V7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7', 'Imaj7'],
  },
  {
    id: 'acoustic-ii',
    name: 'Acoustic ii',
    tag: 'ii-V-IV-I',
    mode: 'major',
    romans: ['ii7', 'V7', 'IVmaj7', 'Imaj7'],
    loop: ['ii7', 'V7', 'IVmaj7', 'Imaj7', 'ii7', 'V7', 'vi7', 'Imaj7'],
  },
  {
    id: 'radio-heart',
    name: 'Radio Heart',
    tag: 'vi-IV-I-V',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'power-ii',
    name: 'Power ii',
    tag: 'ii-vi-IV-V',
    mode: 'major',
    romans: ['ii7', 'vi7', 'IVmaj7', 'V7'],
    loop: ['ii7', 'vi7', 'IVmaj7', 'V7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'dance-iv',
    name: 'Dance IV',
    tag: 'IV-V-vi-I',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'IVmaj7', 'vi7', 'V7', 'Imaj7'],
  },
  {
    id: 'bright-iii',
    name: 'Bright iii',
    tag: 'iii-IV-V-I',
    mode: 'major',
    romans: ['iii7', 'IVmaj7', 'V7', 'Imaj7'],
    loop: ['iii7', 'IVmaj7', 'V7', 'Imaj7', 'iii7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'summer-v',
    name: 'Summer V',
    tag: 'V-I-vi-IV',
    mode: 'major',
    romans: ['V7', 'Imaj7', 'vi7', 'IVmaj7'],
    loop: ['V7', 'Imaj7', 'vi7', 'IVmaj7', 'V7', 'vi7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'writer-vi',
    name: 'Writer vi',
    tag: 'vi-ii-V-I',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'ii7', 'V7'],
  },
  {
    id: 'feel-iv',
    name: 'Feel IV',
    tag: 'IV-I-vi-V',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'vi7', 'V7'],
    loop: ['IVmaj7', 'Imaj7', 'vi7', 'V7', 'IVmaj7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'tiktok-v',
    name: 'TikTok V',
    tag: 'V-vi-V-IV',
    mode: 'major',
    romans: ['V7', 'vi7', 'V7', 'IVmaj7'],
    loop: ['V7', 'vi7', 'V7', 'IVmaj7', 'V7', 'Imaj7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'classic-i',
    name: 'Classic I',
    tag: 'I-vi-IV-V',
    mode: 'major',
    romans: ['Imaj7', 'vi7', 'IVmaj7', 'V7'],
    loop: ['Imaj7', 'vi7', 'IVmaj7', 'V7', 'Imaj7', 'IVmaj7', 'V7', 'vi7'],
  },
  {
    id: 'doo-wop-ii',
    name: 'Doo-Wop ii',
    tag: 'ii-IV-I-V',
    mode: 'major',
    romans: ['ii7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['ii7', 'IVmaj7', 'Imaj7', 'V7', 'ii7', 'V7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'minor-pop',
    name: 'Minor Pop',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVImaj7', 'bVII', 'V7', 'i7'],
  },
  {
    id: 'borrowed-bvii',
    name: 'Borrowed bVII',
    tag: 'bVII-IV',
    mode: 'major',
    romans: ['bVII', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['bVII', 'IVmaj7', 'Imaj7', 'V7', 'bVII', 'IVmaj7', 'vi7', 'V7'],
  },
]);
