/**
 * Live Chord presets — Deep Neo (Geno Build 1 + SE2 Chord Generator).
 *
 * Twenty rearrangeable lush *color palettes* (maj9 / maj13 / 6/9 / m9 / m11 /
 * 13sus…). Cards are meant to be shuffled — not locked ii–V song turns.
 * Public-domain harmonic language only (chord qualities free to combine).
 */
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_DEEP_NEO_DEFS: Se2SynthGenoLivePresetDef[] = defs('deep-neo', [
  {
    id: 'maj9-velvet',
    name: 'Deep · Maj9 Velvet',
    tag: 'maj9 palette',
    mode: 'major',
    bpm: 78,
    romans: ['Imaj9', 'vi9', 'IVmaj9', 'ii9'],
    loop: ['Imaj9', 'vi9', 'IVmaj9', 'ii9', 'Imaj9', 'iii9', 'vi9', 'IVmaj9'],
  },
  {
    id: 'maj13-air',
    name: 'Deep · Maj13 Air',
    tag: 'maj13',
    mode: 'major',
    bpm: 76,
    romans: ['Imaj13', 'IVmaj13', 'vi11', 'Imaj9'],
    loop: ['Imaj13', 'IVmaj13', 'vi11', 'Imaj9', 'Imaj13', 'ii11', 'IVmaj9', 'Imaj13'],
  },
  {
    id: 'six-nine-bed',
    name: 'Deep · 6/9 Rhodes Bed',
    tag: '6/9',
    mode: 'major',
    bpm: 80,
    romans: ['I69', 'IV69', 'vi9', 'Imaj9'],
    loop: ['I69', 'IV69', 'vi9', 'Imaj9', 'I69', 'ii9', 'IV69', 'I69'],
  },
  {
    id: 'lydian-soft',
    name: 'Deep · Lydian Soft',
    tag: 'lydian',
    mode: 'major',
    bpm: 82,
    romans: ['Imaj7#11', 'IVmaj9', 'vi11', 'I69'],
    loop: ['Imaj7#11', 'IVmaj9', 'vi11', 'I69', 'Imaj7#11', 'ii11', 'IVmaj13', 'Imaj7#11'],
  },
  {
    id: 'm11-silk',
    name: 'Deep · m11 Silk',
    tag: 'm11',
    mode: 'major',
    bpm: 74,
    romans: ['vi11', 'ii11', 'Imaj13', 'IVmaj9'],
    loop: ['vi11', 'ii11', 'Imaj13', 'IVmaj9', 'vi11', 'Imaj9', 'ii11', 'vi11'],
  },
  {
    id: 'iv-color-lift',
    name: 'Deep · IV Color Lift',
    tag: 'IV color',
    mode: 'major',
    bpm: 88,
    romans: ['IVmaj13', 'Imaj9', 'vi9', 'IV69'],
    loop: ['IVmaj13', 'Imaj9', 'vi9', 'IV69', 'IVmaj13', 'iii9', 'vi11', 'IVmaj9'],
  },
  {
    id: '13sus-cloud',
    name: 'Deep · 13sus Cloud',
    tag: 'sus color',
    mode: 'major',
    bpm: 86,
    romans: ['V13sus', 'Imaj13', 'vi11', 'IVmaj9'],
    loop: ['V13sus', 'Imaj13', 'vi11', 'IVmaj9', 'V13sus', 'ii11', 'Imaj9', 'I69'],
  },
  {
    id: 'quiet-ninths',
    name: 'Deep · Quiet Ninths',
    tag: '9ths',
    mode: 'major',
    bpm: 72,
    romans: ['Imaj9', 'vi9', 'iii9', 'IVmaj9'],
    loop: ['Imaj9', 'vi9', 'iii9', 'IVmaj9', 'Imaj9', 'ii9', 'vi9', 'Imaj9'],
  },
  {
    id: 'borrowed-shade',
    name: 'Deep · Borrowed Shade',
    tag: 'borrowed',
    mode: 'major',
    bpm: 70,
    romans: ['Imaj9', 'iv9', 'IVmaj13', 'vi11'],
    loop: ['Imaj9', 'iv9', 'IVmaj13', 'vi11', 'I69', 'iv11', 'ii11', 'Imaj9'],
  },
  {
    id: 'half-dim-mist',
    name: 'Deep · Half-Dim Mist',
    tag: 'ø color',
    mode: 'major',
    bpm: 68,
    romans: ['iiø7', 'Imaj13', 'vi11', 'IVmaj9'],
    loop: ['iiø7', 'Imaj13', 'vi11', 'IVmaj9', 'iiø7', 'Imaj9', 'vi9', 'IVmaj13'],
  },
  {
    id: 'dorian-i11-pad',
    name: 'Deep · Dorian i11 Pad',
    tag: 'dorian',
    mode: 'dorian',
    bpm: 84,
    romans: ['i11', 'IV13', 'bVIImaj9', 'i9'],
    loop: ['i11', 'IV13', 'bVIImaj9', 'i9', 'i11', 'IV69', 'ii11', 'i11'],
  },
  {
    id: 'dorian-69-glow',
    name: 'Deep · Dorian 6/9 Glow',
    tag: 'dorian 6/9',
    mode: 'dorian',
    bpm: 80,
    romans: ['i69', 'IV69', 'bIIImaj9', 'ii11'],
    loop: ['i69', 'IV69', 'bIIImaj9', 'ii11', 'i69', 'IV13', 'bVIImaj9', 'i69'],
  },
  {
    id: 'bright-iv-shelf',
    name: 'Deep · Bright IV Shelf',
    tag: 'IV13',
    mode: 'dorian',
    bpm: 90,
    romans: ['IV13', 'i11', 'bVIImaj9', 'IV69'],
    loop: ['IV13', 'i11', 'bVIImaj9', 'IV69', 'IV13', 'i9', 'bIIImaj9', 'IV13'],
  },
  {
    id: 'earth-modal',
    name: 'Deep · Earth Modal',
    tag: 'modal',
    mode: 'dorian',
    bpm: 76,
    romans: ['bIIImaj9', 'i11', 'IV13', 'bVIImaj9'],
    loop: ['bIIImaj9', 'i11', 'IV13', 'bVIImaj9', 'bIIImaj9', 'i69', 'IV69', 'bIIImaj9'],
  },
  {
    id: 'smoky-i11',
    name: 'Deep · Smoky i11',
    tag: 'minor',
    mode: 'minor',
    bpm: 72,
    romans: ['i11', 'VImaj9', 'iv11', 'i9'],
    loop: ['i11', 'VImaj9', 'iv11', 'i9', 'i11', 'bVImaj9', 'iv9', 'i11'],
  },
  {
    id: 'minor-liquid',
    name: 'Deep · Minor Liquid',
    tag: 'minor 9',
    mode: 'minor',
    bpm: 70,
    romans: ['i9', 'iv9', 'VImaj9', 'bIIImaj9'],
    loop: ['i9', 'iv9', 'VImaj9', 'bIIImaj9', 'i9', 'iv11', 'VImaj9', 'i9'],
  },
  {
    id: 'iv11-blanket',
    name: 'Deep · iv11 Blanket',
    tag: 'iv11',
    mode: 'minor',
    bpm: 68,
    romans: ['iv11', 'i11', 'bVImaj9', 'VImaj9'],
    loop: ['iv11', 'i11', 'bVImaj9', 'VImaj9', 'iv11', 'i9', 'bIIImaj9', 'iv11'],
  },
  {
    id: 'velvet-mix',
    name: 'Deep · Velvet Mix',
    tag: 'soul jazz',
    mode: 'major',
    bpm: 78,
    romans: ['Imaj13', 'iii9', 'vi11', 'V13sus'],
    loop: ['Imaj13', 'iii9', 'vi11', 'V13sus', 'Imaj9', 'IVmaj13', 'vi9', 'Imaj13'],
  },
  {
    id: 'gospel-soft',
    name: 'Deep · Gospel Soft Colors',
    tag: 'gospel soft',
    mode: 'major',
    bpm: 74,
    romans: ['IVmaj13', 'Imaj9', 'vi11', 'I69'],
    loop: ['IVmaj13', 'Imaj9', 'vi11', 'I69', 'IVmaj9', 'iii9', 'vi9', 'IVmaj13'],
  },
  {
    id: 'night-pocket',
    name: 'Deep · Night Pocket',
    tag: 'night',
    mode: 'major',
    bpm: 82,
    romans: ['ii11', 'Imaj13', 'V13sus', 'vi9'],
    loop: ['ii11', 'Imaj13', 'V13sus', 'vi9', 'ii11', 'IVmaj9', 'Imaj9', 'ii11'],
  },
]);
