/**
 * Live Chord presets — Jazz pack v3.
 * Standards-based ii–V–I / rhythm changes / bossa / modal — explicit 8-bar loops
 * with cadences on bars 4 and 8 (same marination pattern as R&B presets).
 *
 * Sources: jazzguitar.be top progressions, Learn Jazz Standards, Autumn Leaves /
 * Rhythm Changes / Blue Bossa / Ipanema harmonic analysis.
 */
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_JAZZ_DEFS = defs('jazz', [
  // ── Major ii–V–I & circle-of-fourths (most-called standards) ─────────────
  {
    id: 'two-five-one',
    name: '2-5-1 Swing',
    tag: 'ii–V–I',
    mode: 'major',
    bpm: 132,
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'all-the-things',
    name: 'All The Things',
    tag: 'vi–ii–V–I',
    mode: 'major',
    bpm: 120,
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'iii7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'autumn-leaves',
    name: 'Autumn Leaves',
    tag: 'circle IV',
    mode: 'major',
    bpm: 118,
    romans: ['ii7', 'V7', 'Imaj7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'fly-me-moon',
    name: 'Fly Me To The Moon',
    tag: 'descend',
    mode: 'major',
    bpm: 124,
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'satin-doll',
    name: 'Satin Doll',
    tag: 'Ellington',
    mode: 'major',
    bpm: 128,
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'iii7', 'vi7'],
  },
  {
    id: 'there-will-never',
    name: 'There Will Never',
    tag: 'turnaround',
    mode: 'major',
    bpm: 126,
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'misty',
    name: 'Misty',
    tag: 'ballad',
    mode: 'major',
    bpm: 64,
    romans: ['Imaj7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['Imaj7', 'IVmaj7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'body-soul',
    name: 'Body And Soul',
    tag: 'IV–iv',
    mode: 'major',
    bpm: 58,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'iv', 'Imaj7', 'V7'],
  },
  {
    id: 'west-coast',
    name: 'West Coast Cool',
    tag: 'IV–ii–V–I',
    mode: 'major',
    bpm: 108,
    romans: ['IVmaj7', 'ii7', 'V7', 'Imaj7'],
    loop: ['IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  // ── Rhythm changes & bebop ─────────────────────────────────────────────
  {
    id: 'rhythm-changes',
    name: 'Rhythm Changes',
    tag: 'I Got Rhythm',
    mode: 'major',
    bpm: 168,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'rhythm-bridge',
    name: 'Rhythm Bridge',
    tag: 'iii–vi–ii–V',
    mode: 'major',
    bpm: 160,
    romans: ['iii7', 'vi7', 'ii7', 'V7'],
    loop: ['iii7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'confirmation',
    name: 'Confirmation',
    tag: 'bebop',
    mode: 'major',
    bpm: 152,
    romans: ['iii7', 'vi7', 'ii7', 'V7'],
    loop: ['iii7', 'vi7', 'ii7', 'V7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'but-not-for-me',
    name: 'But Not For Me',
    tag: 'II7 lead',
    mode: 'lydian',
    bpm: 136,
    romans: ['II7', 'V7', 'Imaj7', 'vi7'],
    loop: ['II7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'take-a-train',
    name: 'Take The A Train',
    tag: 'I–vi–ii–V',
    mode: 'major',
    bpm: 130,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'ipanema',
    name: 'Girl From Ipanema',
    tag: 'bossa',
    mode: 'lydian',
    bpm: 118,
    romans: ['Imaj7', 'II7', 'ii7', 'V7'],
    loop: ['Imaj7', 'II7', 'ii7', 'V7', 'Imaj7', 'II7', 'ii7', 'V7'],
  },
  {
    id: 'bossa-nova',
    name: 'Bossa Nova',
    tag: 'latin',
    mode: 'major',
    bpm: 116,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  // ── Reharm / blues / passing ─────────────────────────────────────────────
  {
    id: 'tritone-sub',
    name: 'Tritone Sub',
    tag: 'bII–I',
    mode: 'major',
    bpm: 124,
    romans: ['ii7', 'bIImaj7', 'Imaj7', 'V7'],
    loop: ['ii7', 'bIImaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'bIImaj7', 'Imaj7'],
  },
  {
    id: 'dim-passing',
    name: 'Dim Passing',
    tag: 'iiø turn',
    mode: 'major',
    bpm: 116,
    romans: ['iiø7', 'V7', 'Imaj7', 'vi7'],
    loop: ['iiø7', 'V7', 'Imaj7', 'vi7', 'iii7', 'vi7', 'iiø7', 'V7'],
  },
  {
    id: 'jazz-blues',
    name: 'Jazz Blues',
    tag: '12-bar',
    mode: 'major',
    bpm: 112,
    romans: ['I7', 'IV7', 'I7', 'V7'],
    loop: ['I7', 'IV7', 'I7', 'V7', 'IV7', 'I7', 'ii7', 'V7'],
  },
  {
    id: 'solar',
    name: 'Solar',
    tag: 'Miles',
    mode: 'major',
    bpm: 144,
    romans: ['Imaj7', 'iiø7', 'V7', 'iii7'],
    loop: ['Imaj7', 'iiø7', 'V7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  // ── Minor ii–V–i (standards) ───────────────────────────────────────────────
  {
    id: 'blue-bossa',
    name: 'Blue Bossa',
    tag: 'Kenny Dorham',
    mode: 'minor',
    bpm: 132,
    romans: ['i7', 'iv7', 'iiø7', 'V7'],
    loop: ['i7', 'iv7', 'iiø7', 'V7', 'i7', 'iv7', 'iiø7', 'V7'],
  },
  {
    id: 'minor-two-five',
    name: 'Minor 2-5-1',
    tag: 'iiø–V–i',
    mode: 'minor',
    bpm: 96,
    romans: ['iiø7', 'V7', 'i7', 'iv7'],
    loop: ['iiø7', 'V7', 'i7', 'iv7', 'iiø7', 'V7', 'i7', 'V7'],
  },
  {
    id: 'round-midnight',
    name: 'Round Midnight',
    tag: 'ballad',
    mode: 'minor',
    bpm: 54,
    romans: ['i7', 'iv7', 'i7', 'V7'],
    loop: ['i7', 'iv7', 'i7', 'V7', 'bVImaj7', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'blue-in-green',
    name: 'Blue In Green',
    tag: 'Miles ballad',
    mode: 'minor',
    bpm: 62,
    romans: ['i7', 'bVImaj7', 'iiø7', 'V7'],
    loop: ['i7', 'bVImaj7', 'iiø7', 'V7', 'iv7', 'i7', 'iiø7', 'V7'],
  },
  {
    id: 'recorda-me',
    name: 'Recorda Me',
    tag: 'latin minor',
    mode: 'minor',
    bpm: 128,
    romans: ['i7', 'VImaj7', 'iiø7', 'V7'],
    loop: ['i7', 'VImaj7', 'iiø7', 'V7', 'i7', 'VImaj7', 'iiø7', 'V7'],
  },
  {
    id: 'mr-pc',
    name: 'Mr. P.C.',
    tag: 'Coltrane',
    mode: 'minor',
    bpm: 120,
    romans: ['i7', 'iv7', 'i7', 'V7'],
    loop: ['i7', 'iv7', 'i7', 'V7', 'iv7', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'so-what',
    name: 'So What',
    tag: 'modal',
    mode: 'minor',
    bpm: 132,
    romans: ['i7', 'bIImaj7', 'i7', 'i7'],
    loop: ['i7', 'bIImaj7', 'i7', 'i7', 'i7', 'bIImaj7', 'i7', 'iv7'],
  },
  {
    id: 'cantaloupe',
    name: 'Cantaloupe Island',
    tag: 'Herbie',
    mode: 'dorian',
    bpm: 108,
    romans: ['i7', 'i7', 'bVIImaj7', 'IV7'],
    loop: ['i7', 'i7', 'bVIImaj7', 'IV7', 'i7', 'bIIImaj7', 'i7', 'IV7'],
  },
  {
    id: 'watermelon',
    name: 'Watermelon Man',
    tag: 'funk',
    mode: 'mixolydian',
    bpm: 116,
    romans: ['I7', 'IV7', 'I7', 'bVIImaj7'],
    loop: ['I7', 'IV7', 'I7', 'bVIImaj7', 'I7', 'IV7', 'bVIImaj7', 'I7'],
  },
]);
