/**
 * Live Chord presets — R&B Pop (neo-soul depth + radio hooks).
 * Deep neo-soul cards lead the list; each preset carries a feel-matched BPM.
 */
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_RNB_POP_DEFS: Se2SynthGenoLivePresetDef[] = defs('rnb-pop', [
  // ── Deep neo-soul / R&B (slow pocket — opens the category) ───────────────
  {
    id: 'voodoo-marinate',
    name: 'Voodoo Marinate',
    tag: 'deep neo',
    mode: 'dorian',
    bpm: 72,
    romans: ['i7', 'IVmaj7', 'ii7', 'bVIImaj7'],
    loop: ['i7', 'IVmaj7', 'iiø7', 'bVIImaj7', 'i7', 'IVmaj7', 'ii7', 'bVIImaj7'],
  },
  {
    id: 'baduizm-deep',
    name: 'Earth Deep',
    tag: 'bIII neo',
    mode: 'dorian',
    bpm: 74,
    romans: ['bIIImaj7', 'i7', 'ii7', 'IVmaj7'],
    loop: ['bIIImaj7', 'i7', 'ii7', 'IVmaj7', 'i7', 'bVIImaj7', 'ii7', 'IVmaj7'],
  },
  {
    id: 'glasper-minor',
    name: 'Soft Jazz Minor',
    tag: 'iiø turn',
    mode: 'minor',
    bpm: 76,
    romans: ['iiø7', 'V7', 'i7', 'bVImaj7'],
    loop: ['iiø7', 'V7', 'i7', 'bVImaj7', 'bVII', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'rhodes-prayer',
    name: 'Rhodes Prayer',
    tag: 'slow jam',
    mode: 'major',
    bpm: 70,
    romans: ['Imaj7', 'vi7', 'iii7', 'ii7'],
    loop: ['Imaj7', 'vi7', 'iii7', 'ii7', 'V7', 'Imaj7', 'vi7', 'ii7'],
  },
  {
    id: 'silk-9th-soul',
    name: 'Silk 9th Soul',
    tag: 'neo maj9',
    mode: 'major',
    bpm: 78,
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'vii°7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'dangelo-float',
    name: "D'Angelo Float",
    tag: 'dorian',
    mode: 'dorian',
    bpm: 78,
    romans: ['i7', 'IVmaj7', 'iii7', 'bVIImaj7'],
    loop: ['i7', 'IVmaj7', 'iii7', 'bVIImaj7', 'ii7', 'IVmaj7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'erykah-wick',
    name: 'Erykah Wick',
    tag: 'ii vamp',
    mode: 'dorian',
    bpm: 76,
    romans: ['i7', 'ii7', 'i7', 'IVmaj7'],
    loop: ['i7', 'ii7', 'i7', 'IVmaj7', 'bVIImaj7', 'ii7', 'IVmaj7', 'i7'],
  },
  {
    id: 'minor-nine-vamp',
    name: 'Minor 9 Vamp',
    tag: 'i–IV',
    mode: 'dorian',
    bpm: 80,
    romans: ['i7', 'IVmaj7', 'i7', 'bVIImaj7'],
    loop: ['i7', 'IVmaj7', 'i7', 'bVIImaj7', 'ii7', 'IVmaj7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'gospel-minor-drop',
    name: 'Gospel Minor Drop',
    tag: 'dim pass',
    mode: 'minor',
    bpm: 74,
    romans: ['i7', 'iiø7', 'V7', 'bVImaj7'],
    loop: ['i7', 'iiø7', 'V7', 'bVImaj7', 'bVII', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'soul-plagal-minor',
    name: 'Soul Plagal Minor',
    tag: 'iv–i',
    mode: 'minor',
    bpm: 76,
    romans: ['i7', 'iv7', 'bVImaj7', 'bVII'],
    loop: ['i7', 'iv7', 'bVImaj7', 'bVII', 'iv7', 'V7', 'i7', 'bVII'],
  },
  // ── Neo-soul / R&B pop pocket (mid tempo) ────────────────────────────────
  {
    id: 'neo-turnaround',
    name: 'Neo Turnaround',
    tag: 'ii9–V9–I',
    mode: 'major',
    bpm: 80,
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'iii7', 'vi7'],
  },
  {
    id: 'daniel-caesar',
    name: 'Daniel Caesar',
    tag: 'maj7 turn',
    mode: 'major',
    bpm: 78,
    romans: ['Imaj7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['Imaj7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'dim-passing',
    name: 'Dim Passing',
    tag: 'vii° bridge',
    mode: 'major',
    bpm: 76,
    romans: ['Imaj7', 'vii°7', 'iii7', 'vi7'],
    loop: ['Imaj7', 'vii°7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'cycle-turn',
    name: 'Cycle Turn',
    tag: 'cycle of 4ths',
    mode: 'major',
    bpm: 82,
    romans: ['Imaj7', 'IVmaj7', 'vii°7', 'iii7'],
    loop: ['Imaj7', 'IVmaj7', 'vii°7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'late-night-fm',
    name: 'Late Night FM',
    tag: 'slow jam',
    mode: 'major',
    bpm: 72,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'frank-blend',
    name: 'Frank Blend',
    tag: 'dream pop',
    mode: 'major',
    bpm: 74,
    romans: ['Imaj7', 'iii7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'iii7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'stevie-groove',
    name: 'Stevie Groove',
    tag: 'ii–V soul',
    mode: 'major',
    bpm: 82,
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7', 'vi7', 'ii7'],
  },
  {
    id: 'minor-turn',
    name: 'Minor Turn',
    tag: 'iiø–V–i',
    mode: 'minor',
    bpm: 78,
    romans: ['iiø7', 'V7', 'i7', 'bVII'],
    loop: ['iiø7', 'V7', 'i7', 'bVII', 'iiø7', 'V7', 'iv7', 'i7'],
  },
  {
    id: 'after-hours',
    name: 'After Hours',
    tag: 'Weeknd',
    mode: 'minor',
    bpm: 80,
    romans: ['i7', 'bVImaj7', 'bVII', 'iv7'],
    loop: ['i7', 'bVImaj7', 'bVII', 'iv7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'plagal-soul',
    name: 'Plagal Soul',
    tag: 'IV–I',
    mode: 'major',
    bpm: 86,
    romans: ['Imaj7', 'IVmaj7', 'vi7', 'V7'],
    loop: ['Imaj7', 'IVmaj7', 'vi7', 'V7', 'ii7', 'V7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'secondary-dom',
    name: 'Secondary Dom',
    tag: 'V/iii',
    mode: 'major',
    bpm: 84,
    romans: ['ii7', 'V7', 'iii7', 'vi7'],
    loop: ['ii7', 'V7', 'iii7', 'vi7', 'IVmaj7', 'Imaj7', 'ii7', 'V7'],
  },
  {
    id: 'gospel-pop-lift',
    name: 'Gospel Pop Lift',
    tag: 'IV shout',
    mode: 'major',
    bpm: 90,
    romans: ['IVmaj7', 'Imaj7', 'V7', 'vi7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  // ── R&B pop groove (mid-up) ─────────────────────────────────────────────
  {
    id: 'her-radio',
    name: 'H.E.R. Radio',
    tag: 'vi start',
    mode: 'major',
    bpm: 88,
    romans: ['vi7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'bryson-text',
    name: 'Bryson Text',
    tag: 'I–iii–vi',
    mode: 'major',
    bpm: 90,
    romans: ['Imaj7', 'iii7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'iii7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'sza-glide',
    name: 'SZA Glide',
    tag: 'vi lead',
    mode: 'major',
    bpm: 88,
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'drake-mood',
    name: 'Drake Mood',
    tag: 'i–VI–bVII',
    mode: 'minor',
    bpm: 84,
    romans: ['i7', 'VImaj7', 'bVII', 'iv7'],
    loop: ['i7', 'VImaj7', 'bVII', 'iv7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'sza-minor',
    name: 'SZA Minor',
    tag: 'moody loop',
    mode: 'minor',
    bpm: 82,
    romans: ['i7', 'iv7', 'bVImaj7', 'bVII'],
    loop: ['i7', 'iv7', 'bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'bryson-night',
    name: 'Bryson Night',
    tag: 'bVII lead',
    mode: 'minor',
    bpm: 86,
    romans: ['i7', 'bVII', 'VImaj7', 'iv7'],
    loop: ['i7', 'bVII', 'VImaj7', 'iv7', 'bVI', 'bVII', 'i7', 'iv7'],
  },
  {
    id: 'moody-pop-loop',
    name: 'Moody Pop Loop',
    tag: 'i–IV–v',
    mode: 'minor',
    bpm: 88,
    romans: ['i7', 'iv7', 'v7', 'i7'],
    loop: ['i7', 'iv7', 'v7', 'i7', 'bVImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'trap-soul',
    name: 'Trap Soul',
    tag: '808 soul',
    mode: 'minor',
    bpm: 88,
    romans: ['i7', 'bVII', 'VImaj7', 'iv7'],
    loop: ['i7', 'bVII', 'VImaj7', 'iv7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'radio-soul',
    name: 'Radio Soul',
    tag: 'vi–IV hook',
    mode: 'major',
    bpm: 92,
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'summer-heart',
    name: 'Summer Heart',
    tag: 'vi–IV–I',
    mode: 'major',
    bpm: 94,
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  // ── Chart / uptempo pop hooks ────────────────────────────────────────────
  {
    id: 'chart-axis',
    name: 'Chart Axis',
    tag: 'I–V–vi–IV',
    mode: 'major',
    bpm: 104,
    romans: ['Imaj7', 'V7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7'],
  },
  {
    id: 'tiktok-heart',
    name: 'TikTok Heart',
    tag: 'vi–IV–V',
    mode: 'major',
    bpm: 106,
    romans: ['vi7', 'IVmaj7', 'V7', 'Imaj7'],
    loop: ['vi7', 'IVmaj7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'kiss-cam',
    name: 'Kiss Cam',
    tag: 'stadium',
    mode: 'major',
    bpm: 108,
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'vi7', 'IVmaj7', 'V7', 'Imaj7'],
  },
]);
