/**
 * Live Chord presets — Deep Neo (Geno Build 1).
 * Twenty rearrangeable lush chord *palettes* (maj13 / 6/9 / m11 / 13sus…),
 * not locked song progressions. Load a card → pads are deep colors you can
 * move / swap / reorder — Building Blocks–style chord colors, public-domain
 * harmonic language only.
 */
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_DEEP_NEO_DEFS: Se2SynthGenoLivePresetDef[] = defs('deep-neo', [
  {
    id: 'maj9-home',
    name: 'Deep · Maj9 Home',
    tag: 'maj9 palette',
    mode: 'major',
    bpm: 78,
    romans: ['Imaj9', 'vi9', 'IVmaj9', 'V13sus'],
    loop: ['Imaj9', 'vi9', 'IVmaj9', 'V13sus', 'Imaj9', 'iii9', 'vi9', 'V13'],
  },
  {
    id: 'maj13-glow',
    name: 'Deep · Maj13 Glow',
    tag: 'maj13',
    mode: 'major',
    bpm: 76,
    romans: ['Imaj13', 'vi11', 'IVmaj13', 'V13'],
    loop: ['Imaj13', 'vi11', 'IVmaj13', 'V13', 'Imaj13', 'ii11', 'V13sus', 'Imaj13'],
  },
  {
    id: 'six-nine-rhodes',
    name: 'Deep · 6/9 Rhodes',
    tag: '6/9',
    mode: 'major',
    bpm: 80,
    romans: ['I69', 'IV69', 'vi9', 'V13sus'],
    loop: ['I69', 'IV69', 'vi9', 'V13sus', 'I69', 'ii9', 'V13', 'I69'],
  },
  {
    id: 'lydian-sharp11',
    name: 'Deep · Maj7♯11',
    tag: 'lydian',
    mode: 'major',
    bpm: 82,
    romans: ['Imaj7#11', 'IVmaj9', 'vi11', 'V13'],
    loop: ['Imaj7#11', 'IVmaj9', 'vi11', 'V13', 'Imaj7#11', 'ii11', 'V13sus', 'Imaj7#11'],
  },
  {
    id: 'm11-pocket',
    name: 'Deep · m11 Pocket',
    tag: 'm11',
    mode: 'major',
    bpm: 84,
    romans: ['ii11', 'V13', 'Imaj13', 'vi11'],
    loop: ['ii11', 'V13', 'Imaj13', 'vi11', 'ii11', 'V13sus', 'Imaj9', 'vi11'],
  },
  {
    id: 'vi11-silk',
    name: 'Deep · vi11 Silk',
    tag: 'vi m11',
    mode: 'major',
    bpm: 74,
    romans: ['vi11', 'ii11', 'V13sus', 'Imaj13'],
    loop: ['vi11', 'ii11', 'V13sus', 'Imaj13', 'vi11', 'IVmaj9', 'ii11', 'V13'],
  },
  {
    id: 'iv-maj13-lift',
    name: 'Deep · IVmaj13 Lift',
    tag: 'IV color',
    mode: 'major',
    bpm: 88,
    romans: ['IVmaj13', 'Imaj9', 'vi11', 'V13'],
    loop: ['IVmaj13', 'Imaj9', 'vi11', 'V13', 'IVmaj13', 'iii11', 'vi9', 'V13sus'],
  },
  {
    id: '13sus-resolve',
    name: 'Deep · 13sus Resolve',
    tag: 'sus color',
    mode: 'major',
    bpm: 86,
    romans: ['V13sus', 'V13', 'Imaj13', 'vi9'],
    loop: ['V13sus', 'V13', 'Imaj13', 'vi9', 'ii11', 'V13sus', 'Imaj9', 'I69'],
  },
  {
    id: 'half-dim-tender',
    name: 'Deep · Tender ø7',
    tag: 'iiø',
    mode: 'major',
    bpm: 72,
    romans: ['iiø7', 'V13', 'Imaj13', 'vi11'],
    loop: ['iiø7', 'V13', 'Imaj13', 'vi11', 'iiø7', 'V13sus', 'Imaj9', 'IVmaj9'],
  },
  {
    id: 'borrowed-iv11',
    name: 'Deep · Borrowed iv11',
    tag: 'backdoor',
    mode: 'major',
    bpm: 78,
    romans: ['Imaj13', 'iv11', 'Imaj9', 'V13sus'],
    loop: ['Imaj13', 'iv11', 'Imaj9', 'V13sus', 'I69', 'iv9', 'ii11', 'V13'],
  },
  {
    id: 'dorian-im11',
    name: 'Deep · Dorian i11',
    tag: 'modal',
    mode: 'dorian',
    bpm: 84,
    romans: ['i11', 'IV13', 'bVIImaj9', 'ii11'],
    loop: ['i11', 'IV13', 'bVIImaj9', 'ii11', 'i11', 'IV69', 'i69', 'bVIImaj9'],
  },
  {
    id: 'dorian-i69',
    name: 'Deep · Dorian i6/9',
    tag: 'm6/9',
    mode: 'dorian',
    bpm: 80,
    romans: ['i69', 'IV13', 'ii11', 'bVIImaj9'],
    loop: ['i69', 'IV13', 'ii11', 'bVIImaj9', 'i11', 'IV69', 'i69', 'bIIImaj9'],
  },
  {
    id: 'dorian-iv13',
    name: 'Deep · Dorian IV13',
    tag: 'bright IV',
    mode: 'dorian',
    bpm: 88,
    romans: ['IV13', 'i11', 'bVIImaj9', 'ii9'],
    loop: ['IV13', 'i11', 'bVIImaj9', 'ii9', 'IV69', 'i69', 'bIIImaj9', 'IV13'],
  },
  {
    id: 'minor-smoky-m11',
    name: 'Deep · Smoky i11',
    tag: 'minor',
    mode: 'minor',
    bpm: 72,
    romans: ['i11', 'VImaj9', 'iiø7', 'V13'],
    loop: ['i11', 'VImaj9', 'iiø7', 'V13', 'i69', 'iv11', 'V13sus', 'i11'],
  },
  {
    id: 'minor-iv11-pad',
    name: 'Deep · Minor iv11',
    tag: 'iv color',
    mode: 'minor',
    bpm: 70,
    romans: ['iv11', 'i11', 'bVImaj9', 'V13sus'],
    loop: ['iv11', 'i11', 'bVImaj9', 'V13sus', 'iv9', 'VImaj9', 'iiø7', 'V13'],
  },
  {
    id: 'minor-liquid',
    name: 'Deep · Liquid Minor',
    tag: 'm9/m11',
    mode: 'minor',
    bpm: 74,
    romans: ['i9', 'i11', 'VImaj9', 'V13'],
    loop: ['i9', 'i11', 'VImaj9', 'V13', 'i69', 'iv11', 'bIIImaj9', 'V13sus'],
  },
  {
    id: 'neo-earth-palette',
    name: 'Deep · Earth Palette',
    tag: 'neo pad',
    mode: 'dorian',
    bpm: 76,
    romans: ['bIIImaj9', 'i11', 'IV13', 'bVIImaj9'],
    loop: ['bIIImaj9', 'i11', 'IV13', 'bVIImaj9', 'i69', 'ii11', 'IV69', 'bIIImaj9'],
  },
  {
    id: 'quiet-storm-colors',
    name: 'Deep · Quiet Storm',
    tag: '70s soul',
    mode: 'major',
    bpm: 72,
    romans: ['Imaj13', 'iii11', 'vi11', 'V13sus'],
    loop: ['Imaj13', 'iii11', 'vi11', 'V13sus', 'I69', 'IVmaj13', 'ii11', 'V13'],
  },
  {
    id: 'velvet-turn-colors',
    name: 'Deep · Velvet Colors',
    tag: 'turnaround',
    mode: 'major',
    bpm: 90,
    romans: ['Imaj9', 'vi11', 'ii11', 'V13'],
    loop: ['Imaj9', 'vi11', 'ii11', 'V13', 'Imaj13', 'iii9', 'iiø7', 'V13sus'],
  },
  {
    id: 'gospel-jazz-colors',
    name: 'Deep · Gospel Jazz',
    tag: 'lift',
    mode: 'major',
    bpm: 92,
    romans: ['IVmaj13', 'Imaj13', 'vi11', 'V13'],
    loop: ['IVmaj13', 'Imaj13', 'vi11', 'V13', 'IVmaj9', 'iii11', 'ii11', 'V13sus'],
  },
]);
