/**
 * Live Chord preset definitions — batch 3: Gospel, Afrobeats, Latin Trap, House/Dance,
 * Jersey/Bounce, Boom Bap, Plug/Rage, Lo-Fi Cinematic (~30 each).
 */
import type { Se2SynthGenoLivePresetDef } from '@/app/lib/studio/se2SynthGenoLiveChordPresets';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]) {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_GOSPEL_DEFS = defs('gospel', [
  {
    id: 'sunday-rise',
    name: 'Sunday Rise',
    tag: 'IV lead',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'vi7', 'V7'],
    loop: ['IVmaj7', 'Imaj7', 'vi7', 'V7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'choir-lift',
    name: 'Choir Lift',
    tag: 'V lead',
    mode: 'major',
    romans: ['V7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['V7', 'vi7', 'IVmaj7', 'Imaj7', 'ii7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'organ-shout',
    name: 'Organ Shout',
    tag: 'IV shout',
    mode: 'major',
    romans: ['IV7', 'I7', 'vi7', 'V7'],
    loop: ['IV7', 'I7', 'vi7', 'V7', 'IV7', 'V7', 'I7', 'vi7'],
  },
  {
    id: 'praise-turn',
    name: 'Praise Turn',
    tag: 'IV turn',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'iii7', 'vi7'],
    loop: ['IVmaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'holy-groove',
    name: 'Holy Groove',
    tag: 'vi lead',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'baptist-walk',
    name: 'Baptist Walk',
    tag: 'ii lead',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    tag: 'IV warm',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'iii7', 'vi7'],
    loop: ['IVmaj7', 'Imaj7', 'iii7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'testimony',
    name: 'Testimony',
    tag: 'vi start',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'revival-fire',
    name: 'Revival Fire',
    tag: 'V drive',
    mode: 'major',
    romans: ['V7', 'vi7', 'IV7', 'I7'],
    loop: ['V7', 'vi7', 'IV7', 'I7', 'V7', 'IV7', 'vi7', 'V7'],
  },
  {
    id: 'gospel-soul',
    name: 'Gospel Soul',
    tag: 'vi turn',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'church-bounce',
    name: 'Church Bounce',
    tag: 'IV bounce',
    mode: 'major',
    romans: ['IV7', 'vi7', 'V7', 'I7'],
    loop: ['IV7', 'vi7', 'V7', 'I7', 'IV7', 'I7', 'vi7', 'V7'],
  },
  {
    id: 'amen-loop',
    name: 'Amen Loop',
    tag: 'IV cadence',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'ii7', 'V7'],
    loop: ['IVmaj7', 'Imaj7', 'ii7', 'V7', 'IVmaj7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'spirit-move',
    name: 'Spirit Move',
    tag: 'iii flow',
    mode: 'major',
    romans: ['iii7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['iii7', 'vi7', 'IVmaj7', 'Imaj7', 'ii7', 'V7', 'iii7', 'vi7'],
  },
  {
    id: 'hallelujah',
    name: 'Hallelujah',
    tag: 'V lift',
    mode: 'major',
    romans: ['V7', 'Imaj7', 'IVmaj7', 'vi7'],
    loop: ['V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'gospel-blues',
    name: 'Gospel Blues',
    tag: 'IV blues',
    mode: 'major',
    romans: ['IV7', 'I7', 'V7', 'IV7'],
    loop: ['IV7', 'I7', 'V7', 'IV7', 'I7', 'IV7', 'V7', 'I7'],
  },
  {
    id: 'prayer-room',
    name: 'Prayer Room',
    tag: 'vi intimate',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'iii7', 'vi7', 'IVmaj7', 'ii7'],
  },
  {
    id: 'choir-stack',
    name: 'Choir Stack',
    tag: 'IV stack',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'Imaj7', 'vi7'],
    loop: ['IVmaj7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'Imaj7', 'ii7', 'V7'],
  },
  {
    id: 'sunday-drive',
    name: 'Sunday Drive',
    tag: 'vi smooth',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'ii7', 'Imaj7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7'],
  },
  {
    id: 'altar-call',
    name: 'Altar Call',
    tag: 'ii resolve',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'gospel-jazz',
    name: 'Gospel Jazz',
    tag: 'ii jazz',
    mode: 'major',
    romans: ['ii7', 'iii7', 'vi7', 'IVmaj7'],
    loop: ['ii7', 'iii7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'mountain-top',
    name: 'Mountain Top',
    tag: 'V peak',
    mode: 'major',
    romans: ['V7', 'vi7', 'ii7', 'Imaj7'],
    loop: ['V7', 'vi7', 'ii7', 'Imaj7', 'IVmaj7', 'V7', 'vi7', 'ii7'],
  },
  {
    id: 'hymn-bed',
    name: 'Hymn Bed',
    tag: 'IV hymn',
    mode: 'major',
    romans: ['IVmaj7', 'ii7', 'V7', 'Imaj7'],
    loop: ['IVmaj7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'gospel-turn',
    name: 'Gospel Turn',
    tag: 'vi turn',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'joyful-noise',
    name: 'Joyful Noise',
    tag: 'IV joy',
    mode: 'major',
    romans: ['IV7', 'V7', 'I7', 'vi7'],
    loop: ['IV7', 'V7', 'I7', 'vi7', 'IV7', 'I7', 'V7', 'IV7'],
  },
  {
    id: 'worship-pad',
    name: 'Worship Pad',
    tag: 'vi pad',
    mode: 'major',
    romans: ['vi7', 'Imaj7', 'IVmaj7', 'iii7'],
    loop: ['vi7', 'Imaj7', 'IVmaj7', 'iii7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'gospel-swing',
    name: 'Gospel Swing',
    tag: 'ii swing',
    mode: 'major',
    romans: ['ii7', 'V7', 'vi7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'blessed-loop',
    name: 'Blessed Loop',
    tag: 'IV blessed',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'gospel-minor',
    name: 'Gospel Minor',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'bVII', 'V7', 'i7'],
  },
  {
    id: 'crossover',
    name: 'Crossover',
    tag: 'bVII borrow',
    mode: 'major',
    romans: ['bVII', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['bVII', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'bVII', 'IVmaj7', 'V7'],
  },
  {
    id: 'gospel-house',
    name: 'Gospel House',
    tag: 'IV house',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'IVmaj7', 'Imaj7', 'V7', 'vi7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_AFROBEATS_DEFS: Se2SynthGenoLivePresetDef[] = defs('afrobeats', [
  {
    id: 'highlife-iv',
    name: 'Highlife IV',
    tag: 'IV-I-V',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'naija-ii',
    name: 'Naija ii',
    tag: 'ii-V-I',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'Imaj7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'Imaj7'],
  },
  {
    id: 'lagos-v',
    name: 'Lagos V',
    tag: 'V-vi-IV',
    mode: 'major',
    romans: ['V7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7', 'Imaj7'],
  },
  {
    id: 'afropop-vi',
    name: 'Afropop vi',
    tag: 'vi-IV-I-V',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'makosa-iv',
    name: 'Makosa IV',
    tag: 'IV-I-V-IV',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'amapiano-ii',
    name: 'Amapiano ii',
    tag: 'ii-V-vi',
    mode: 'major',
    romans: ['ii7', 'V7', 'vi7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: '6525-groove',
    name: '6525 Groove',
    tag: 'vi-V-ii-V',
    mode: 'major',
    romans: ['vi7', 'V7', 'ii7', 'V7'],
    loop: ['vi7', 'V7', 'ii7', 'V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'island-bvii',
    name: 'Island bVII',
    tag: 'bVII-IV-I',
    mode: 'major',
    romans: ['bVII', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['bVII', 'IVmaj7', 'Imaj7', 'V7', 'bVII', 'IVmaj7', 'vi7', 'V7'],
  },
  {
    id: 'dancehall-bvii',
    name: 'Dancehall bVII',
    tag: 'bVII-I-IV',
    mode: 'major',
    romans: ['bVII', 'Imaj7', 'IVmaj7', 'V7'],
    loop: ['bVII', 'Imaj7', 'IVmaj7', 'V7', 'bVII', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'accra-ii',
    name: 'Accra ii',
    tag: 'ii-V-IV-I',
    mode: 'major',
    romans: ['ii7', 'V7', 'IVmaj7', 'Imaj7'],
    loop: ['ii7', 'V7', 'IVmaj7', 'Imaj7', 'ii7', 'V7', 'vi7', 'Imaj7'],
  },
  {
    id: 'afro-gospel-iv',
    name: 'Afro Gospel IV',
    tag: 'IV-I-vi-V',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'vi7', 'V7'],
    loop: ['IVmaj7', 'Imaj7', 'vi7', 'V7', 'IVmaj7', 'V7', 'Imaj7', 'vi7'],
  },
  {
    id: 'sensitive-vi',
    name: 'Sensitive vi',
    tag: 'vi-IV-V-I',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'V7', 'Imaj7'],
    loop: ['vi7', 'IVmaj7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'afro-shift',
    name: 'Afro Shift',
    tag: 'mixo I7',
    mode: 'mixolydian',
    romans: ['I7', 'bVII', 'IV7', 'I7'],
    loop: ['I7', 'bVII', 'IV7', 'I7', 'bVII', 'IV7', 'I7', 'bVII'],
  },
  {
    id: 'afro-dorian-iv',
    name: 'Afro Dorian IV',
    tag: 'IV-i-bVII',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'IV7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'IV7', 'ii7', 'i7', 'bVIImaj7', 'IV7'],
  },
  {
    id: 'dorian-bvii',
    name: 'Dorian bVII',
    tag: 'bVII-i-IV',
    mode: 'dorian',
    romans: ['bVIImaj7', 'i7', 'IV7', 'ii7'],
    loop: ['bVIImaj7', 'i7', 'IV7', 'ii7', 'bVIImaj7', 'IV7', 'i7', 'ii7'],
  },
  {
    id: 'night-market-vi',
    name: 'Night Market',
    tag: 'VI-i-iv',
    mode: 'minor',
    romans: ['VImaj7', 'i7', 'iv7', 'V7'],
    loop: ['VImaj7', 'i7', 'iv7', 'V7', 'VImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'afro-minor-bvii',
    name: 'Afro Minor',
    tag: 'bVII-bVI-i',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'bVI', 'iv7', 'V7', 'i7'],
  },
  {
    id: 'naija-i',
    name: 'Naija I',
    tag: 'I-V-vi-IV',
    mode: 'major',
    romans: ['Imaj7', 'V7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7'],
  },
  {
    id: 'producer-ii',
    name: 'Producer ii',
    tag: 'ii-V-I-vi',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'sunset-iv',
    name: 'Sunset IV',
    tag: 'IV-V-vi-I',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'IVmaj7', 'vi7', 'V7', 'Imaj7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_LATIN_TRAP_DEFS = defs('latin-trap', [
  {
    id: 'reggaeton-glow',
    name: 'Reggaeton Glow',
    tag: 'dembow',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'miami-heat',
    name: 'Miami Heat',
    tag: 'heat',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['VImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'i7', 'VImaj7'],
  },
  {
    id: 'latin-night',
    name: 'Latin Night',
    tag: 'night',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'V7', 'bVII', 'bVI'],
  },
  {
    id: 'perreo-loop',
    name: 'Perreo Loop',
    tag: 'perreo',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'V7'],
    loop: ['bVII', 'i7', 'bVI', 'V7', 'bVII', 'iv7', 'i7', 'bVI'],
  },
  {
    id: 'trapeton',
    name: 'Trapeton',
    tag: 'fusion',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'bVI', 'bIIImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'caribbean-dark',
    name: 'Caribbean Dark',
    tag: 'dark',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'iv7', 'bVImaj7'],
  },
  {
    id: 'dembow-7th',
    name: 'Dembow 7th',
    tag: 'bounce',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'iv7'],
    loop: ['bVI', 'bVII', 'i7', 'iv7', 'bVI', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'latin-soul',
    name: 'Latin Soul',
    tag: 'soul',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'VImaj7', 'bVII', 'bVI'],
  },
  {
    id: 'reggaeton-minor',
    name: 'Reggaeton Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['V7', 'i7', 'iv7', 'bVII'],
    loop: ['V7', 'i7', 'iv7', 'bVII', 'V7', 'bVI', 'i7', 'iv7'],
  },
  {
    id: 'tropical-trap',
    name: 'Tropical Trap',
    tag: 'tropical',
    mode: 'dorian',
    romans: ['IV7', 'bVIImaj7', 'i7', 'ii7'],
    loop: ['IV7', 'bVIImaj7', 'i7', 'ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'latin-slide',
    name: 'Latin Slide',
    tag: 'slide',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'bVII', 'V7'],
    loop: ['iv7', 'bVI', 'bVII', 'V7', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'fiesta-loop',
    name: 'Fiesta Loop',
    tag: 'fiesta',
    mode: 'minor',
    romans: ['V7', 'bVI', 'bVII', 'i7'],
    loop: ['V7', 'bVI', 'bVII', 'i7', 'iv7', 'V7', 'bVI', 'bVII'],
  },
  {
    id: 'bad-bunny-lean',
    name: 'Bad Bunny Lean',
    tag: 'lean',
    mode: 'minor',
    romans: ['bVI', 'i7', 'bVII', 'iv7'],
    loop: ['bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7', 'bVImaj7'],
  },
  {
    id: 'latin-phrygian',
    name: 'Latin Phrygian',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'reggaeton-turn',
    name: 'Reggaeton Turn',
    tag: 'turn',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'miami-bass',
    name: 'Miami Bass',
    tag: 'bass',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'i7'],
    loop: ['bVII', 'bVI', 'V7', 'i7', 'bVII', 'iv7', 'bVI', 'V7'],
  },
  {
    id: 'latin-gospel',
    name: 'Latin Gospel',
    tag: 'church',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'trap-salsa',
    name: 'Trap Salsa',
    tag: 'salsa',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['bIIImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'bIIImaj7', 'bVI', 'bVII'],
  },
  {
    id: 'night-club',
    name: 'Night Club',
    tag: 'club',
    mode: 'minor',
    romans: ['VII7', 'bVI', 'i7', 'bVII'],
    loop: ['VII7', 'bVI', 'i7', 'bVII', 'VII7', 'iv7', 'bVI', 'i7'],
  },
  {
    id: 'latin-drift',
    name: 'Latin Drift',
    tag: 'drift',
    mode: 'minor',
    romans: ['bVII', 'i7', 'VII7', 'bVI'],
    loop: ['bVII', 'i7', 'VII7', 'bVI', 'bVII', 'iv7', 'i7', 'VII7'],
  },
  {
    id: 'dembow-pain',
    name: 'Dembow Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'reggaeton-wide',
    name: 'Reggaeton Wide',
    tag: 'wide',
    mode: 'minor',
    romans: ['bVII', 'iv7', 'bVI', 'i7'],
    loop: ['bVII', 'iv7', 'bVI', 'i7', 'bVII', 'bVI', 'iv7', 'bVII'],
  },
  {
    id: 'latin-808',
    name: 'Latin 808',
    tag: '808',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bIIImaj7'],
    loop: ['bVI', 'bVII', 'i7', 'bIIImaj7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'trap-latino',
    name: 'Trap Latino',
    tag: 'trap',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'V7'],
    loop: ['iv7', 'bVII', 'bVI', 'V7', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'caribe-smoke',
    name: 'Caribe Smoke',
    tag: 'smoke',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'bVI'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'bVI', 'i7', 'bVImaj7', 'bVII', 'iv7'],
  },
  {
    id: 'perreo-dark',
    name: 'Perreo Dark',
    tag: 'dark',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVImaj7', 'i7', 'bVII'],
    loop: ['bIImaj7', 'bVImaj7', 'i7', 'bVII', 'bIImaj7', 'iv7', 'bVImaj7', 'i7'],
  },
  {
    id: 'latin-ballad',
    name: 'Latin Ballad',
    tag: 'ballad',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'bVII'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'bVII', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'reggaeton-hook',
    name: 'Reggaeton Hook',
    tag: 'hook',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'iv7'],
    loop: ['bVII', 'bVI', 'V7', 'iv7', 'bVII', 'i7', 'bVI', 'V7'],
  },
  {
    id: 'mambo-trap',
    name: 'Mambo Trap',
    tag: 'mambo',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'bVI', 'i7'],
    loop: ['bIIImaj7', 'bVII', 'bVI', 'i7', 'bIIImaj7', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'latin-shift',
    name: 'Latin Shift',
    tag: 'shift',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'bVII', 'i7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_HOUSE_DANCE_DEFS = defs('house-dance', [
  {
    id: 'four-on-floor',
    name: 'Four On Floor',
    tag: 'house',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'deep-house',
    name: 'Deep House',
    tag: 'deep',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'ii7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'Imaj7', 'IVmaj7', 'V7'],
  },
  {
    id: 'club-anthem',
    name: 'Club Anthem',
    tag: 'anthem',
    mode: 'major',
    romans: ['V7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['V7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7', 'Imaj7'],
  },
  {
    id: 'disco-house',
    name: 'Disco House',
    tag: 'disco',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'vi7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    tag: 'warehouse',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'house-minor',
    name: 'House Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['VImaj7', 'bVII', 'i7', 'iv7', 'VImaj7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'euro-glow',
    name: 'Euro Glow',
    tag: 'euro',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'Imaj7', 'vi7'],
    loop: ['IVmaj7', 'V7', 'Imaj7', 'vi7', 'IVmaj7', 'Imaj7', 'V7', 'vi7'],
  },
  {
    id: 'dance-pad',
    name: 'Dance Pad',
    tag: 'pad',
    mode: 'major',
    romans: ['vi7', 'Imaj7', 'IVmaj7', 'ii7'],
    loop: ['vi7', 'Imaj7', 'IVmaj7', 'ii7', 'vi7', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'house-turn',
    name: 'House Turn',
    tag: 'turn',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'iii7', 'vi7'],
    loop: ['IVmaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'festival-drop',
    name: 'Festival Drop',
    tag: 'drop',
    mode: 'major',
    romans: ['I7', 'IV7', 'V7', 'vi7'],
    loop: ['I7', 'IV7', 'V7', 'vi7', 'I7', 'IV7', 'V7', 'I7'],
  },
  {
    id: 'deep-groove',
    name: 'Deep Groove',
    tag: 'groove',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'vi7'],
    loop: ['ii7', 'V7', 'Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'house-soul',
    name: 'House Soul',
    tag: 'soul',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'IVmaj7'],
    loop: ['vi7', 'ii7', 'V7', 'IVmaj7', 'vi7', 'IVmaj7', 'ii7', 'V7'],
  },
  {
    id: 'chicago-loop',
    name: 'Chicago Loop',
    tag: 'chicago',
    mode: 'major',
    romans: ['IVmaj7', 'ii7', 'V7', 'Imaj7'],
    loop: ['IVmaj7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'dance-minor',
    name: 'Dance Minor',
    tag: 'minor',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'ii7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'ii7', 'IV7', 'ii7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'house-stack',
    name: 'House Stack',
    tag: 'stack',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'Imaj7', 'IVmaj7'],
    loop: ['IVmaj7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'IVmaj7', 'V7', 'Imaj7'],
  },
  {
    id: 'sunrise-set',
    name: 'Sunrise Set',
    tag: 'sunrise',
    mode: 'major',
    romans: ['ii7', 'vi7', 'IVmaj7', 'Imaj7'],
    loop: ['ii7', 'vi7', 'IVmaj7', 'Imaj7', 'ii7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'tech-house',
    name: 'Tech House',
    tag: 'tech',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'iv7'],
    loop: ['bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVI', 'i7', 'bVII'],
  },
  {
    id: 'dance-hook',
    name: 'Dance Hook',
    tag: 'hook',
    mode: 'major',
    romans: ['V7', 'IVmaj7', 'vi7', 'Imaj7'],
    loop: ['V7', 'IVmaj7', 'vi7', 'Imaj7', 'V7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'house-gospel',
    name: 'House Gospel',
    tag: 'gospel',
    mode: 'major',
    romans: ['IVmaj7', 'vi7', 'Imaj7', 'V7'],
    loop: ['IVmaj7', 'vi7', 'Imaj7', 'V7', 'IVmaj7', 'V7', 'vi7', 'Imaj7'],
  },
  {
    id: 'club-minor',
    name: 'Club Minor',
    tag: 'club',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'V7', 'bVII', 'bVI'],
  },
  {
    id: 'dance-fade',
    name: 'Dance Fade',
    tag: 'fade',
    mode: 'major',
    romans: ['iii7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['iii7', 'IVmaj7', 'Imaj7', 'V7', 'iii7', 'vi7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'house-bounce',
    name: 'House Bounce',
    tag: 'bounce',
    mode: 'major',
    romans: ['I7', 'vi7', 'IV7', 'V7'],
    loop: ['I7', 'vi7', 'IV7', 'V7', 'I7', 'IV7', 'vi7', 'V7'],
  },
  {
    id: 'rave-loop',
    name: 'Rave Loop',
    tag: 'rave',
    mode: 'major',
    romans: ['bVII', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['bVII', 'IVmaj7', 'Imaj7', 'V7', 'bVII', 'vi7', 'IVmaj7', 'Imaj7'],
  },
  {
    id: 'dance-turn',
    name: 'Dance Turn',
    tag: 'turn',
    mode: 'major',
    romans: ['iii7', 'vi7', 'IVmaj7', 'V7'],
    loop: ['iii7', 'vi7', 'IVmaj7', 'V7', 'iii7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'house-dorian',
    name: 'House Dorian',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['ii7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'peak-hour',
    name: 'Peak Hour',
    tag: 'peak',
    mode: 'major',
    romans: ['V7', 'IV7', 'vi7', 'ii7'],
    loop: ['V7', 'IV7', 'vi7', 'ii7', 'V7', 'Imaj7', 'IV7', 'V7'],
  },
  {
    id: 'dance-wide',
    name: 'Dance Wide',
    tag: 'wide',
    mode: 'major',
    romans: ['IVmaj7', 'vi7', 'ii7', 'V7'],
    loop: ['IVmaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7', 'vi7', 'ii7'],
  },
  {
    id: 'house-shift',
    name: 'House Shift',
    tag: 'shift',
    mode: 'mixolydian',
    romans: ['I7', 'bVII', 'IV7', 'I7'],
    loop: ['I7', 'bVII', 'IV7', 'I7', 'bVII', 'IV7', 'I7', 'bVII'],
  },
  {
    id: 'after-hours',
    name: 'After Hours',
    tag: 'late',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'dance-resolve',
    name: 'Dance Resolve',
    tag: 'resolve',
    mode: 'major',
    romans: ['IVmaj7', 'V7', 'vi7', 'Imaj7'],
    loop: ['IVmaj7', 'V7', 'vi7', 'Imaj7', 'ii7', 'V7', 'IVmaj7', 'Imaj7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_JERSEY_BOUNCE_DEFS = defs('jersey-bounce', [
  {
    id: 'jersey-club',
    name: 'Jersey Club',
    tag: 'club',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'bounce-king',
    name: 'Bounce King',
    tag: 'bounce',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'iv7'],
    loop: ['bVII', 'i7', 'bVI', 'iv7', 'bVII', 'V7', 'i7', 'bVI'],
  },
  {
    id: 'bed-squeak',
    name: 'Bed Squeak',
    tag: 'jersey',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['VImaj7', 'bVII', 'i7', 'iv7', 'VImaj7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'club-knock',
    name: 'Club Knock',
    tag: 'knock',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'V7', 'bVII', 'bVI'],
  },
  {
    id: 'bounce-turn',
    name: 'Bounce Turn',
    tag: 'turn',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'jersey-night',
    name: 'Jersey Night',
    tag: 'night',
    mode: 'minor',
    romans: ['bVII', 'V7', 'bVI', 'i7'],
    loop: ['bVII', 'V7', 'bVI', 'i7', 'bVII', 'iv7', 'V7', 'bVI'],
  },
  {
    id: 'sample-flip',
    name: 'Sample Flip',
    tag: 'sample',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'VImaj7', 'bVI', 'bVII'],
  },
  {
    id: 'bounce-minor',
    name: 'Bounce Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'bVI', 'bIIImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'jersey-soul',
    name: 'Jersey Soul',
    tag: 'soul',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'iv7', 'bVImaj7'],
  },
  {
    id: 'club-heat',
    name: 'Club Heat',
    tag: 'heat',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'iv7'],
    loop: ['bVI', 'bVII', 'i7', 'iv7', 'bVI', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'bounce-wide',
    name: 'Bounce Wide',
    tag: 'wide',
    mode: 'minor',
    romans: ['bVII', 'iv7', 'bVI', 'i7'],
    loop: ['bVII', 'iv7', 'bVI', 'i7', 'bVII', 'bVI', 'iv7', 'bVII'],
  },
  {
    id: 'jersey-slide',
    name: 'Jersey Slide',
    tag: 'slide',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'party-bounce',
    name: 'Party Bounce',
    tag: 'party',
    mode: 'minor',
    romans: ['VII7', 'bVI', 'i7', 'bVII'],
    loop: ['VII7', 'bVI', 'i7', 'bVII', 'VII7', 'iv7', 'bVI', 'i7'],
  },
  {
    id: 'bounce-hook',
    name: 'Bounce Hook',
    tag: 'hook',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'iv7'],
    loop: ['bVII', 'bVI', 'V7', 'iv7', 'bVII', 'i7', 'bVI', 'V7'],
  },
  {
    id: 'jersey-drift',
    name: 'Jersey Drift',
    tag: 'drift',
    mode: 'dorian',
    romans: ['IV7', 'bVIImaj7', 'i7', 'ii7'],
    loop: ['IV7', 'bVIImaj7', 'i7', 'ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7'],
  },
  {
    id: 'club-stack',
    name: 'Club Stack',
    tag: 'stack',
    mode: 'minor',
    romans: ['bVII', 'i7', 'VII7', 'bVI'],
    loop: ['bVII', 'i7', 'VII7', 'bVI', 'bVII', 'iv7', 'i7', 'VII7'],
  },
  {
    id: 'bounce-pain',
    name: 'Bounce Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'jersey-trap',
    name: 'Jersey Trap',
    tag: 'trap',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'V7'],
    loop: ['iv7', 'bVII', 'bVI', 'V7', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'bounce-loop',
    name: 'Bounce Loop',
    tag: 'loop',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'club-glow',
    name: 'Club Glow',
    tag: 'glow',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['VImaj7', 'bVII', 'iv7', 'i7', 'VImaj7', 'bVI', 'bVII', 'iv7'],
  },
  {
    id: 'jersey-phrygian',
    name: 'Jersey Phrygian',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'bounce-shift',
    name: 'Bounce Shift',
    tag: 'shift',
    mode: 'minor',
    romans: ['bVI', 'i7', 'bVII', 'bIIImaj7'],
    loop: ['bVI', 'i7', 'bVII', 'bIIImaj7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'jersey-808',
    name: 'Jersey 808',
    tag: '808',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'iv7', 'V7'],
    loop: ['bVI', 'bVII', 'iv7', 'V7', 'bVI', 'i7', 'bVII', 'iv7'],
  },
  {
    id: 'club-ballad',
    name: 'Club Ballad',
    tag: 'ballad',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'bounce-drive',
    name: 'Bounce Drive',
    tag: 'drive',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['bIIImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'bIIImaj7', 'bVI', 'bVII'],
  },
  {
    id: 'jersey-gospel',
    name: 'Jersey Gospel',
    tag: 'church',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'bounce-dark',
    name: 'Bounce Dark',
    tag: 'dark',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVImaj7', 'i7', 'bVII'],
    loop: ['bIImaj7', 'bVImaj7', 'i7', 'bVII', 'bIImaj7', 'iv7', 'bVImaj7', 'i7'],
  },
  {
    id: 'club-anthem',
    name: 'Club Anthem',
    tag: 'anthem',
    mode: 'minor',
    romans: ['bVII', 'V7', 'i7', 'bVI'],
    loop: ['bVII', 'V7', 'i7', 'bVI', 'bVII', 'iv7', 'V7', 'i7'],
  },
  {
    id: 'jersey-fade',
    name: 'Jersey Fade',
    tag: 'fade',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'bVI'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'bVI', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'bounce-resolve',
    name: 'Bounce Resolve',
    tag: 'resolve',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'bVII', 'i7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_BOOM_BAP_DEFS = defs('boom-bap', [
  {
    id: 'dilla-vamp',
    name: 'Dilla Vamp',
    tag: 'dilla',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'iv7'],
    loop: ['bVII', 'bVI', 'i7', 'iv7', 'bVII', 'bVI', 'iv7', 'i7'],
  },
  {
    id: 'crate-dig',
    name: 'Crate Dig',
    tag: 'sample',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'VImaj7', 'bVI', 'bVII'],
  },
  {
    id: 'boom-loop',
    name: 'Boom Loop',
    tag: 'loop',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'V7', 'bVII', 'bVI'],
  },
  {
    id: 'vinyl-soul',
    name: 'Vinyl Soul',
    tag: 'soul',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'iv7', 'bVImaj7'],
  },
  {
    id: 'jazz-rap',
    name: 'Jazz Rap',
    tag: 'jazz',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'ii7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'ii7', 'IV7', 'ii7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'boom-turn',
    name: 'Boom Turn',
    tag: 'turn',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'dusty-pad',
    name: 'Dusty Pad',
    tag: 'dusty',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'iv7'],
    loop: ['bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVI', 'i7', 'iv7'],
  },
  {
    id: 'boom-gospel',
    name: 'Boom Gospel',
    tag: 'gospel',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'sample-chop',
    name: 'Sample Chop',
    tag: 'chop',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'iv7', 'bIIImaj7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'boom-wide',
    name: 'Boom Wide',
    tag: 'wide',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'bVII'],
    loop: ['iv7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'vinyl-night',
    name: 'Vinyl Night',
    tag: 'night',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['VImaj7', 'bVII', 'i7', 'iv7', 'VImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'boom-dorian',
    name: 'Boom Dorian',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['ii7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'head-nod',
    name: 'Head Nod',
    tag: 'nod',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bVII'],
    loop: ['bVI', 'bVII', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'boom-blues',
    name: 'Boom Blues',
    tag: 'blues',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'crate-classic',
    name: 'Crate Classic',
    tag: 'classic',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'boom-stack',
    name: 'Boom Stack',
    tag: 'stack',
    mode: 'minor',
    romans: ['bVII', 'i7', 'VII7', 'bVI'],
    loop: ['bVII', 'i7', 'VII7', 'bVI', 'bVII', 'iv7', 'i7', 'VII7'],
  },
  {
    id: 'vinyl-warm',
    name: 'Vinyl Warm',
    tag: 'warm',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'bIIImaj7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'bIIImaj7', 'bVImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'boom-hook',
    name: 'Boom Hook',
    tag: 'hook',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'i7'],
    loop: ['bVII', 'bVI', 'V7', 'i7', 'bVII', 'iv7', 'bVI', 'V7'],
  },
  {
    id: 'sample-flip',
    name: 'Sample Flip',
    tag: 'flip',
    mode: 'minor',
    romans: ['ii7', 'iv7', 'bVII', 'i7'],
    loop: ['ii7', 'iv7', 'bVII', 'i7', 'ii7', 'V7', 'iv7', 'bVII'],
  },
  {
    id: 'boom-pain',
    name: 'Boom Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'bVI'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'bVI', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'vinyl-drift',
    name: 'Vinyl Drift',
    tag: 'drift',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'bVII', 'i7'],
    loop: ['iv7', 'bVI', 'bVII', 'i7', 'iv7', 'bVII', 'bVI', 'iv7'],
  },
  {
    id: 'boom-minor',
    name: 'Boom Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'V7', 'i7'],
    loop: ['iv7', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'crate-swing',
    name: 'Crate Swing',
    tag: 'swing',
    mode: 'dorian',
    romans: ['ii7', 'bVIImaj7', 'IV7', 'i7'],
    loop: ['ii7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'boom-fade',
    name: 'Boom Fade',
    tag: 'fade',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'bVII'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'bVII', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'vinyl-loop',
    name: 'Vinyl Loop',
    tag: 'loop',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'boom-shift',
    name: 'Boom Shift',
    tag: 'shift',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'crate-glow',
    name: 'Crate Glow',
    tag: 'glow',
    mode: 'dorian',
    romans: ['IV7', 'ii7', 'i7', 'bVIImaj7'],
    loop: ['IV7', 'ii7', 'i7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'bVIImaj7'],
  },
  {
    id: 'boom-resolve',
    name: 'Boom Resolve',
    tag: 'resolve',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'vinyl-sparse',
    name: 'Vinyl Sparse',
    tag: 'sparse',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bVI'],
    loop: ['bVI', 'bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'boom-anthem',
    name: 'Boom Anthem',
    tag: 'anthem',
    mode: 'minor',
    romans: ['bVII', 'V7', 'bVI', 'i7'],
    loop: ['bVII', 'V7', 'bVI', 'i7', 'bVII', 'iv7', 'V7', 'bVI'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_PLUG_RAGE_DEFS = defs('plug-rage', [
  {
    id: 'rage-loop',
    name: 'Rage Loop',
    tag: 'rage',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'plug-dark',
    name: 'Plug Dark',
    tag: 'plug',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'V7', 'bVII', 'bVI'],
  },
  {
    id: 'carti-lean',
    name: 'Carti Lean',
    tag: 'lean',
    mode: 'minor',
    romans: ['bVI', 'i7', 'bVII', 'bIIImaj7'],
    loop: ['bVI', 'i7', 'bVII', 'bIIImaj7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'rage-808',
    name: 'Rage 808',
    tag: '808',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'iv7'],
    loop: ['bVI', 'bVII', 'i7', 'iv7', 'bVI', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'plug-slide',
    name: 'Plug Slide',
    tag: 'slide',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'bVII', 'i7', 'bVI'],
  },
  {
    id: 'rage-turn',
    name: 'Rage Turn',
    tag: 'turn',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'plug-night',
    name: 'Plug Night',
    tag: 'night',
    mode: 'minor',
    romans: ['VII7', 'bVI', 'i7', 'bVII'],
    loop: ['VII7', 'bVI', 'i7', 'bVII', 'VII7', 'iv7', 'bVI', 'i7'],
  },
  {
    id: 'rage-wide',
    name: 'Rage Wide',
    tag: 'wide',
    mode: 'minor',
    romans: ['bVII', 'iv7', 'bVI', 'i7'],
    loop: ['bVII', 'iv7', 'bVI', 'i7', 'bVII', 'bVI', 'iv7', 'bVII'],
  },
  {
    id: 'plug-phrygian',
    name: 'Plug Phrygian',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'rage-stack',
    name: 'Rage Stack',
    tag: 'stack',
    mode: 'minor',
    romans: ['bVII', 'i7', 'VII7', 'bVI'],
    loop: ['bVII', 'i7', 'VII7', 'bVI', 'bVII', 'iv7', 'i7', 'VII7'],
  },
  {
    id: 'plug-minor',
    name: 'Plug Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'bVI', 'bIIImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'rage-hook',
    name: 'Rage Hook',
    tag: 'hook',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'i7'],
    loop: ['bVII', 'bVI', 'V7', 'i7', 'bVII', 'iv7', 'bVI', 'V7'],
  },
  {
    id: 'plug-drift',
    name: 'Plug Drift',
    tag: 'drift',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'iv7', 'bVImaj7'],
  },
  {
    id: 'rage-cold',
    name: 'Rage Cold',
    tag: 'cold',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bIIImaj7'],
    loop: ['bVI', 'bVII', 'i7', 'bIIImaj7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'plug-glow',
    name: 'Plug Glow',
    tag: 'glow',
    mode: 'minor',
    romans: ['VImaj7', 'bVI', 'bVII', 'i7'],
    loop: ['VImaj7', 'bVI', 'bVII', 'i7', 'VImaj7', 'iv7', 'bVI', 'bVII'],
  },
  {
    id: 'rage-shift',
    name: 'Rage Shift',
    tag: 'shift',
    mode: 'minor',
    romans: ['bVII', 'V7', 'bVI', 'i7'],
    loop: ['bVII', 'V7', 'bVI', 'i7', 'bVII', 'iv7', 'V7', 'bVI'],
  },
  {
    id: 'plug-loop',
    name: 'Plug Loop',
    tag: 'loop',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'rage-pain',
    name: 'Rage Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'plug-trap',
    name: 'Plug Trap',
    tag: 'trap',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'V7'],
    loop: ['iv7', 'bVII', 'bVI', 'V7', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'rage-ballad',
    name: 'Rage Ballad',
    tag: 'ballad',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'bVII'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'bVII', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'plug-horror',
    name: 'Plug Horror',
    tag: 'horror',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVImaj7', 'i7', 'bVII'],
    loop: ['bIImaj7', 'bVImaj7', 'i7', 'bVII', 'bIImaj7', 'iv7', 'bVImaj7', 'i7'],
  },
  {
    id: 'rage-drive',
    name: 'Rage Drive',
    tag: 'drive',
    mode: 'minor',
    romans: ['VII7', 'i7', 'bVI', 'bVII'],
    loop: ['VII7', 'i7', 'bVI', 'bVII', 'VII7', 'iv7', 'bVI', 'i7'],
  },
  {
    id: 'plug-sparse',
    name: 'Plug Sparse',
    tag: 'sparse',
    mode: 'minor',
    romans: ['bVI', 'i7', 'bVI', 'bVII'],
    loop: ['bVI', 'i7', 'bVI', 'bVII', 'bVI', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'rage-resolve',
    name: 'Rage Resolve',
    tag: 'resolve',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'plug-bounce',
    name: 'Plug Bounce',
    tag: 'bounce',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'iv7'],
    loop: ['bVII', 'bVI', 'V7', 'iv7', 'bVII', 'i7', 'bVI', 'V7'],
  },
  {
    id: 'rage-dorian',
    name: 'Rage Dorian',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['IV7', 'bVIImaj7', 'i7', 'bVI'],
    loop: ['IV7', 'bVIImaj7', 'i7', 'bVI', 'IV7', 'ii7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'plug-gospel',
    name: 'Plug Gospel',
    tag: 'church',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'rage-anthem',
    name: 'Rage Anthem',
    tag: 'anthem',
    mode: 'minor',
    romans: ['bVII', 'V7', 'i7', 'bVI'],
    loop: ['bVII', 'V7', 'i7', 'bVI', 'bVII', 'iv7', 'V7', 'i7'],
  },
  {
    id: 'plug-fade',
    name: 'Plug Fade',
    tag: 'fade',
    mode: 'minor',
    romans: ['bVImaj7', 'i7', 'bVII', 'iv7'],
    loop: ['bVImaj7', 'i7', 'bVII', 'iv7', 'bVImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'rage-grave',
    name: 'Rage Grave',
    tag: 'grave',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'bVI', 'i7'],
    loop: ['bIImaj7', 'bVII', 'bVI', 'i7', 'bIImaj7', 'iv7', 'bVII', 'bVI'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_LOFI_CINEMATIC_DEFS = defs('lofi-cinematic', [
  {
    id: 'rain-window',
    name: 'Rain Window',
    tag: 'rain',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'film-dust',
    name: 'Film Dust',
    tag: 'dust',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'iv7'],
    loop: ['bVII', 'bVI', 'i7', 'iv7', 'bVII', 'bVI', 'iv7', 'i7'],
  },
  {
    id: 'soft-horror',
    name: 'Soft Horror',
    tag: 'soft',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'i7'],
    loop: ['iv7', 'bVII', 'bVI', 'i7', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'ambient-loop',
    name: 'Ambient Loop',
    tag: 'ambient',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'iv7'],
    loop: ['bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVI', 'i7', 'iv7'],
  },
  {
    id: 'cinematic-pad',
    name: 'Cinematic Pad',
    tag: 'pad',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVImaj7'],
  },
  {
    id: 'tape-fog',
    name: 'Tape Fog',
    tag: 'fog',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'bVII', 'i7'],
    loop: ['iv7', 'bVI', 'bVII', 'i7', 'iv7', 'bVII', 'bVI', 'iv7'],
  },
  {
    id: 'lonely-reel',
    name: 'Lonely Reel',
    tag: 'lonely',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['VImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'VImaj7', 'iv7'],
  },
  {
    id: 'soft-dorian',
    name: 'Soft Dorian',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['IV7', 'i7', 'bVIImaj7', 'ii7'],
    loop: ['IV7', 'i7', 'bVIImaj7', 'ii7', 'IV7', 'ii7', 'i7', 'bVIImaj7'],
  },
  {
    id: 'cinema-fade',
    name: 'Cinema Fade',
    tag: 'fade',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'bVII'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'bVII', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'mist-loop',
    name: 'Mist Loop',
    tag: 'mist',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'soft-phrygian',
    name: 'Soft Phrygian',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVII', 'i7', 'bVI'],
    loop: ['bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'film-score',
    name: 'Film Score',
    tag: 'score',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'i7', 'bVII'],
    loop: ['iv7', 'bVI', 'i7', 'bVII', 'iv7', 'bVII', 'bVI', 'i7'],
  },
  {
    id: 'ambient-turn',
    name: 'Ambient Turn',
    tag: 'turn',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'bVI', 'iv7', 'bVII', 'V7'],
  },
  {
    id: 'lofi-horror',
    name: 'Lo-Fi Horror',
    tag: 'horror',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVImaj7', 'i7', 'bVII'],
    loop: ['bIImaj7', 'bVImaj7', 'i7', 'bVII', 'bIImaj7', 'iv7', 'bVImaj7', 'i7'],
  },
  {
    id: 'cinema-drift',
    name: 'Cinema Drift',
    tag: 'drift',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'iv7', 'i7'],
    loop: ['bVII', 'bVI', 'iv7', 'i7', 'bVII', 'iv7', 'bVI', 'bVII'],
  },
  {
    id: 'soft-stack',
    name: 'Soft Stack',
    tag: 'stack',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'i7', 'bVII'],
    loop: ['bVImaj7', 'iv7', 'i7', 'bVII', 'bVI', 'iv7', 'i7', 'bVImaj7'],
  },
  {
    id: 'rain-pad',
    name: 'Rain Pad',
    tag: 'pad',
    mode: 'minor',
    romans: ['iv7', 'bVII', 'bVI', 'bVII'],
    loop: ['iv7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'film-minor',
    name: 'Film Minor',
    tag: 'minor',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'iv7', 'bIIImaj7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'ambient-wide',
    name: 'Ambient Wide',
    tag: 'wide',
    mode: 'minor',
    romans: ['bVII', 'iv7', 'bVI', 'bVII'],
    loop: ['bVII', 'iv7', 'bVI', 'bVII', 'bVII', 'i7', 'iv7', 'bVI'],
  },
  {
    id: 'cinema-soul',
    name: 'Cinema Soul',
    tag: 'soul',
    mode: 'minor',
    romans: ['VImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['VImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'VImaj7'],
  },
  {
    id: 'soft-resolve',
    name: 'Soft Resolve',
    tag: 'resolve',
    mode: 'harmonicMinor',
    romans: ['bVImaj7', 'V7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'tape-night',
    name: 'Tape Night',
    tag: 'night',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'bVI'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'bVI', 'i7', 'bVImaj7', 'iv7', 'bVII'],
  },
  {
    id: 'film-sparse',
    name: 'Film Sparse',
    tag: 'sparse',
    mode: 'minor',
    romans: ['bVI', 'i7', 'bVI', 'bVII'],
    loop: ['bVI', 'i7', 'bVI', 'bVII', 'bVI', 'iv7', 'i7', 'bVII'],
  },
  {
    id: 'ambient-glow',
    name: 'Ambient Glow',
    tag: 'glow',
    mode: 'minor',
    romans: ['bVII', 'VImaj7', 'bVII', 'i7'],
    loop: ['bVII', 'VImaj7', 'bVII', 'i7', 'bVII', 'iv7', 'VImaj7', 'bVII'],
  },
  {
    id: 'cinema-hook',
    name: 'Cinema Hook',
    tag: 'hook',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'V7', 'iv7'],
    loop: ['bVII', 'bVI', 'V7', 'iv7', 'bVII', 'i7', 'bVI', 'V7'],
  },
  {
    id: 'soft-loop',
    name: 'Soft Loop',
    tag: 'loop',
    mode: 'dorian',
    romans: ['ii7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['ii7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'film-shift',
    name: 'Film Shift',
    tag: 'shift',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'bIIImaj7'],
    loop: ['bVI', 'bVII', 'i7', 'bIIImaj7', 'bVI', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'ambient-pain',
    name: 'Ambient Pain',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVI', 'iv7', 'bVII', 'i7'],
    loop: ['bVI', 'iv7', 'bVII', 'i7', 'bVImaj7', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'cinema-dust',
    name: 'Cinema Dust',
    tag: 'dusty',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVI', 'bVII'],
    loop: ['bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'soft-close',
    name: 'Soft Close',
    tag: 'close',
    mode: 'minor',
    romans: ['iv7', 'bVImaj7', 'bVII', 'i7'],
    loop: ['iv7', 'bVImaj7', 'bVII', 'i7', 'iv7', 'bVII', 'bVImaj7', 'i7'],
  },
]);
