/**
 * Curated Live Chord preset definitions — feel-first names, 7th-heavy voicings.
 * v1: Trap, Hip-hop, R&B, Dark · Cinematic/Horror (~30 each).
 */
import type { ChordMode, ChordSymbol } from '@/app/lib/creationStation/chordBuilder';
import type { Se2SynthGenoLiveGenreId } from '@/app/lib/studio/se2SynthGenoLiveChordTypes';

export type Se2SynthGenoLivePresetDef = {
  id: string;
  name: string;
  tag?: string;
  mode: ChordMode;
  /** Short label loop (first 4 steps) — shown in card subtitle. */
  romans: ChordSymbol[];
  /**
   * Full playable progression (4–12). When set, used as-is for trigger slots
   * instead of generic bridge extension — each card keeps its own harmony.
   */
  loop?: ChordSymbol[];
  /** @deprecated Prefer {@link loop}. */
  romans12?: ChordSymbol[];
  /** Authentic feel BPM — overrides genre default when set. */
  bpm?: number;
};

function defs(genreId: Se2SynthGenoLiveGenreId, items: Se2SynthGenoLivePresetDef[]): Se2SynthGenoLivePresetDef[] {
  return items.map((item) => ({ ...item, id: `${genreId}-${item.id}` }));
}

export const SE2_SYNTH_GENO_LIVE_TRAP_DEFS: Se2SynthGenoLivePresetDef[] = defs('trap', [
  {
    id: 'metro-shadow',
    name: 'Metro Shadow',
    tag: 'dark loop',
    mode: 'minor',
    romans: ['i7', 'bVII', 'bVI', 'bVII'],
    loop: ['i7', 'bVII', 'bVI', 'bVII', 'i7', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'zay-wide',
    name: 'Zay Wide',
    tag: 'sample flip',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bIIImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'i7', 'bIIImaj7'],
  },
  {
    id: 'soul-flip',
    name: 'Soul Sample Flip',
    tag: 'VI start',
    mode: 'minor',
    romans: ['vi7', 'bVII', 'iv7', 'i7'],
    loop: ['vi7', 'bVII', 'iv7', 'i7', 'bVI', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'atlanta-night',
    name: 'Atlanta Night',
    tag: 'borrowed VI',
    mode: 'minor',
    romans: ['VImaj7', 'VII7', 'bVI', 'i7'],
    loop: ['VImaj7', 'VII7', 'bVI', 'i7', 'iv7', 'bVII', 'VImaj7', 'VII7'],
  },
  {
    id: '808-graveyard',
    name: '808 Graveyard',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'bVI'],
    loop: ['iv7', 'i7', 'bVII', 'bVI', 'iv7', 'V7', 'bVII', 'i7'],
  },
  {
    id: 'hard-turn',
    name: 'Hard Turn',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'V7', 'i7'],
    loop: ['bVI', 'bVII', 'V7', 'i7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'detroit-drift',
    name: 'Detroit Drift',
    tag: 'bIII lead',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVI', 'bVII', 'iv7'],
    loop: ['bIIImaj7', 'bVI', 'bVII', 'iv7', 'i7', 'bIIImaj7', 'bVII', 'bVI'],
  },
  {
    id: 'sad-trap',
    name: 'Sad Trap',
    tag: 'emotional',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'bVII', 'i7'],
    loop: ['bVImaj7', 'iv7', 'bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'night-rider',
    name: 'Night Rider',
    tag: 'VII lead',
    mode: 'minor',
    romans: ['VII7', 'bVI', 'i7', 'iv7'],
    loop: ['VII7', 'bVI', 'i7', 'iv7', 'bVII', 'bVI', 'VII7', 'i7'],
  },
  {
    id: 'sparse-pain',
    name: 'Sparse Pain',
    tag: 'bVII vamp',
    mode: 'minor',
    romans: ['bVII', 'i7', 'bVII', 'bVI'],
    loop: ['bVII', 'i7', 'bVII', 'bVI', 'bVII', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'lex-cold',
    name: 'Lex Cold',
    tag: 'icy',
    mode: 'minor',
    romans: ['i7', 'bVII', 'bVI', 'bVII'],
    loop: ['i7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7', 'bVII', 'bVI'],
  },
  {
    id: 'tm88-wide',
    name: 'TM88 Wide',
    tag: 'stadium',
    mode: 'minor',
    romans: ['i7', 'bVII', 'iv7', 'bVI'],
    loop: ['i7', 'bVII', 'iv7', 'bVI', 'VImaj7', 'bVII', 'i7', 'bVII'],
  },
  {
    id: 'trap-gospel',
    name: 'Trap Gospel',
    tag: 'iv turn',
    mode: 'minor',
    romans: ['iv7', 'V7', 'i7', 'bVI'],
    loop: ['iv7', 'V7', 'i7', 'bVI', 'iv7', 'i7', 'V7', 'i7'],
  },
  {
    id: 'ethereal-smoke',
    name: 'Ethereal Smoke',
    tag: 'airy',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bVII', 'i7', 'iv7', 'bVI', 'bVII', 'bVImaj7', 'i7'],
  },
  {
    id: 'money-count',
    name: 'Money Count',
    tag: 'bounce',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'bVII'],
    loop: ['bVII', 'bVI', 'i7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7'],
  },
  {
    id: 'horror-lean',
    name: 'Horror Lean',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['i7', 'bIImaj7', 'bVII', 'i7'],
    loop: ['i7', 'bIImaj7', 'bVII', 'i7', 'bVI', 'bIImaj7', 'i7', 'bVII'],
  },
  {
    id: 'wavy-minor',
    name: 'Wavy Minor',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['i7', 'IV7', 'bVIImaj7', 'i7'],
    loop: ['i7', 'IV7', 'bVIImaj7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'frozen-heart',
    name: 'Frozen Heart',
    tag: 'harmonic',
    mode: 'harmonicMinor',
    romans: ['i7', 'bVImaj7', 'V7', 'i7'],
    loop: ['i7', 'bVImaj7', 'V7', 'i7', 'iv7', 'V7', 'bVImaj7', 'i7'],
  },
  {
    id: 'purple-dusk',
    name: 'Purple Dusk',
    tag: 'VI tint',
    mode: 'minor',
    romans: ['VImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['VImaj7', 'bVII', 'iv7', 'i7', 'VImaj7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'slime-season',
    name: 'Slime Season',
    tag: 'bounce',
    mode: 'minor',
    romans: ['bVII', 'i7', 'VII7', 'bVI'],
    loop: ['bVII', 'i7', 'VII7', 'bVI', 'bVII', 'i7', 'bVII', 'VII7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_HIPHOP_DEFS: Se2SynthGenoLivePresetDef[] = defs('hip-hop', [
  {
    id: 'boom-bap-soul',
    name: 'Boom Bap Soul',
    tag: 'classic',
    mode: 'minor',
    romans: ['i7', 'VImaj7', 'bVII', 'iv7'],
    loop: ['i7', 'VImaj7', 'bVII', 'iv7', 'bVI', 'bVII', 'i7', 'iv7'],
  },
  {
    id: 'dj-premier',
    name: 'DJ Premier Feel',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVII', 'i7'],
    loop: ['iv7', 'i7', 'bVII', 'i7', 'bVI', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'j-dilla-vamp',
    name: 'Dilla Vamp',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['i7', 'IV7', 'i7', 'bVIImaj7'],
    loop: ['i7', 'IV7', 'i7', 'bVIImaj7', 'ii7', 'i7', 'IV7', 'bVIImaj7'],
  },
  {
    id: 'nas-story',
    name: 'Street Story',
    tag: 'iv start',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'bVII', 'i7'],
    loop: ['iv7', 'bVI', 'bVII', 'i7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'mobb-deep',
    name: 'Mobb Deep Dark',
    tag: 'bVI lead',
    mode: 'minor',
    romans: ['bVI', 'bVII', 'i7', 'iv7'],
    loop: ['bVI', 'bVII', 'i7', 'iv7', 'bVI', 'i7', 'bVII', 'iv7'],
  },
  {
    id: 'kanye-soul',
    name: 'Soul Chop',
    tag: 'sample',
    mode: 'minor',
    romans: ['i7', 'VImaj7', 'iv7', 'bVII'],
    loop: ['i7', 'VImaj7', 'iv7', 'bVII', 'VI', 'iv7', 'bVII', 'bVI'],
  },
  {
    id: 'jazz-rap',
    name: 'Jazz Rap',
    tag: 'ii start',
    mode: 'dorian',
    romans: ['ii7', 'i7', 'IV7', 'bVIImaj7'],
    loop: ['ii7', 'i7', 'IV7', 'bVIImaj7', 'ii7', 'IV7', 'bVII', 'i7'],
  },
  {
    id: 'g-funk-glide',
    name: 'G-Funk Glide',
    tag: 'west',
    mode: 'minor',
    romans: ['i7', 'bVII', 'bVI', 'V7'],
    loop: ['i7', 'bVII', 'bVI', 'V7', 'bVII', 'bVI', 'i7', 'V7'],
  },
  {
    id: 'dr-dre-wide',
    name: 'Wide Coast',
    tag: 'bIII lead',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVII', 'bVI', 'i7'],
    loop: ['bIIImaj7', 'bVII', 'bVI', 'i7', 'iv7', 'bIIImaj7', 'bVII', 'bVI'],
  },
  {
    id: 'chipmunk-soul',
    name: 'Chipmunk Soul',
    tag: 'pitched',
    mode: 'minor',
    romans: ['i7', 'bVII', 'VImaj7', 'iv7'],
    loop: ['i7', 'bVII', 'VImaj7', 'iv7', 'bVI', 'bVII', 'VImaj7', 'i7'],
  },
  {
    id: 'conscious-flow',
    name: 'Conscious Flow',
    tag: 'turn',
    mode: 'minor',
    romans: ['i7', 'bVImaj7', 'iv7', 'V7'],
    loop: ['i7', 'bVImaj7', 'iv7', 'V7', 'bVI', 'iv7', 'V7', 'i7'],
  },
  {
    id: 'boom-bap-ii',
    name: 'Boom Bap II-V',
    tag: 'iiø lead',
    mode: 'minor',
    romans: ['iiø7', 'V7', 'i7', 'bVII'],
    loop: ['iiø7', 'V7', 'i7', 'bVII', 'iiø7', 'V7', 'iv7', 'bVII'],
  },
  {
    id: 'vinyl-warmth',
    name: 'Vinyl Warmth',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['i7', 'IV7', 'bIIImaj7', 'i7'],
    loop: ['i7', 'IV7', 'bIIImaj7', 'i7', 'bVIImaj7', 'IV7', 'i7', 'ii7'],
  },
  {
    id: 'east-coast-rain',
    name: 'East Coast Rain',
    tag: 'rain',
    mode: 'minor',
    romans: ['i7', 'bVImaj7', 'bVII', 'iv7'],
    loop: ['i7', 'bVImaj7', 'bVII', 'iv7', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'west-coast-sun',
    name: 'West Coast Sun',
    tag: 'IV tint',
    mode: 'minor',
    romans: ['i7', 'bVII', 'IV7', 'bVI'],
    loop: ['i7', 'bVII', 'IV7', 'bVI', 'iv7', 'bVII', 'bVI', 'i7'],
  },
  {
    id: 'soul-turn',
    name: 'Soul Turn',
    tag: 'VI turn',
    mode: 'minor',
    romans: ['i7', 'VImaj7', 'bVII', 'V7'],
    loop: ['i7', 'VImaj7', 'bVII', 'V7', 'iv7', 'bVI', 'bVII', 'V7'],
  },
  {
    id: 'dusty-groove',
    name: 'Dusty Groove',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['i7', 'ii7', 'i7', 'IV7'],
    loop: ['i7', 'ii7', 'i7', 'IV7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
  {
    id: 'harlem-nights',
    name: 'Harlem Nights',
    tag: 'iv lead',
    mode: 'minor',
    romans: ['iv7', 'VImaj7', 'bVII', 'i7'],
    loop: ['iv7', 'VImaj7', 'bVII', 'i7', 'iv7', 'i7', 'bVI', 'bVII'],
  },
  {
    id: 'golden-era',
    name: 'Golden Era',
    tag: 'golden',
    mode: 'minor',
    romans: ['i7', 'VImaj7', 'bVI', 'iv7'],
    loop: ['i7', 'VImaj7', 'bVI', 'iv7', 'bVII', 'bVI', 'iv7', 'i7'],
  },
  {
    id: 'head-nod',
    name: 'Head Nod',
    tag: 'dorian',
    mode: 'dorian',
    romans: ['i7', 'bVIImaj7', 'IV7', 'i7'],
    loop: ['i7', 'bVIImaj7', 'IV7', 'i7', 'ii7', 'IV7', 'bVIImaj7', 'i7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_RNB_DEFS: Se2SynthGenoLivePresetDef[] = defs('rnb', [
  {
    id: 'quiet-storm',
    name: 'Quiet Storm',
    tag: 'slow',
    mode: 'major',
    romans: ['Imaj7', 'vi7', 'IVmaj7', 'V7'],
    loop: ['Imaj7', 'vi7', 'IVmaj7', 'V7', 'ii7', 'V7', 'iii7', 'vi7'],
  },
  {
    id: 'usher-turn',
    name: 'Usher Turn',
    tag: 'vi lead',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'iii7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'bridge-25',
    name: 'Bridge 2-5',
    tag: 'ii lead',
    mode: 'major',
    romans: ['ii7', 'V7', 'Imaj7', 'IVmaj7'],
    loop: ['ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7', 'Imaj7'],
  },
  {
    id: 'frank-ocean',
    name: 'Frank Ocean Feel',
    tag: 'dream',
    mode: 'major',
    romans: ['Imaj7', 'iii7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'iii7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'vi7', 'IVmaj7'],
  },
  {
    id: 'h-e-r-mood',
    name: 'H.E.R. Mood',
    tag: 'vi start',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'V7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'V7', 'iii7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'maxwell-smooth',
    name: 'Maxwell Smooth',
    tag: 'vi turn',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'iii7', 'vi7', 'ii7'],
  },
  {
    id: 'stevie-wonder',
    name: 'Stevie Wonder',
    tag: 'classic',
    mode: 'major',
    romans: ['Imaj7', 'vi7', 'ii7', 'V7'],
    loop: ['Imaj7', 'vi7', 'ii7', 'V7', 'IVmaj7', 'Imaj7', 'vi7', 'ii7'],
  },
  {
    id: 'gospel-rnb',
    name: 'Gospel R&B',
    tag: 'IV lead',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'Imaj7', 'vi7', 'IVmaj7', 'V7'],
  },
  {
    id: 'h-town',
    name: 'H-Town',
    tag: 'houston',
    mode: 'major',
    romans: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7'],
    loop: ['IVmaj7', 'Imaj7', 'V7', 'IVmaj7', 'vi7', 'IVmaj7', 'Imaj7', 'V7'],
  },
  {
    id: 'sza-mood',
    name: 'SZA Mood',
    tag: 'minor',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'i7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'i7', 'bVI', 'bVII', 'V7', 'i7'],
  },
  {
    id: 'summer-walker',
    name: 'Summer Walker',
    tag: 'alt minor',
    mode: 'minor',
    romans: ['i7', 'bVImaj7', 'iv7', 'bVII'],
    loop: ['i7', 'bVImaj7', 'iv7', 'bVII', 'bVI', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'weeknd-night',
    name: 'Weeknd Night',
    tag: 'dark',
    mode: 'minor',
    romans: ['i7', 'bVI', 'bVII', 'i7'],
    loop: ['i7', 'bVI', 'bVII', 'i7', 'bVImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: 'trap-soul',
    name: 'Trap Soul',
    tag: 'vi lead',
    mode: 'minor',
    romans: ['vi7', 'bVII', 'iv7', 'i7'],
    loop: ['vi7', 'bVII', 'iv7', 'i7', 'VImaj7', 'bVII', 'iv7', 'i7'],
  },
  {
    id: '2000s-rnb',
    name: '2000s R&B',
    tag: 'vi start',
    mode: 'major',
    romans: ['vi7', 'IVmaj7', 'Imaj7', 'iii7'],
    loop: ['vi7', 'IVmaj7', 'Imaj7', 'iii7', 'vi7', 'IVmaj7', 'V7', 'Imaj7'],
  },
  {
    id: 'two-chord-vamp',
    name: 'Two-Chord Vamp',
    tag: 'vamp',
    mode: 'major',
    romans: ['Imaj7', 'IVmaj7', 'Imaj7', 'IVmaj7'],
    loop: ['Imaj7', 'IVmaj7', 'Imaj7', 'IVmaj7', 'Imaj7', 'IVmaj7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'rnb-climax',
    name: 'Climax',
    tag: 'turn',
    mode: 'major',
    romans: ['vi7', 'ii7', 'V7', 'Imaj7'],
    loop: ['vi7', 'ii7', 'V7', 'Imaj7', 'IVmaj7', 'vi7', 'ii7', 'V7'],
  },
  {
    id: 'power-ballad',
    name: 'Power Ballad',
    tag: 'ballad',
    mode: 'major',
    romans: ['Imaj7', 'IVmaj7', 'vi7', 'V7'],
    loop: ['Imaj7', 'IVmaj7', 'vi7', 'V7', 'ii7', 'V7', 'Imaj7', 'IVmaj7'],
  },
  {
    id: 'kehlani-feel',
    name: 'Kehlani Feel',
    tag: 'bright',
    mode: 'major',
    romans: ['Imaj7', 'iii7', 'vi7', 'IVmaj7'],
    loop: ['Imaj7', 'iii7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'iii7', 'vi7'],
  },
  {
    id: 'dark-rnb',
    name: 'Dark R&B',
    tag: 'minor',
    mode: 'minor',
    romans: ['i7', 'bVImaj7', 'bVII', 'iv7'],
    loop: ['i7', 'bVImaj7', 'bVII', 'iv7', 'bVI', 'bVII', 'V7', 'i7'],
  },
  {
    id: '90s-groove',
    name: '90s Groove',
    tag: '90s',
    mode: 'major',
    romans: ['Imaj7', 'vi7', 'IVmaj7', 'ii7'],
    loop: ['Imaj7', 'vi7', 'IVmaj7', 'ii7', 'V7', 'IVmaj7', 'vi7', 'ii7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_DARK_DEFS: Se2SynthGenoLivePresetDef[] = defs('dark-cinematic', [
  {
    id: 'horror-pedal',
    name: 'Horror Pedal',
    tag: 'pedal',
    mode: 'minor',
    romans: ['i7', 'bVImaj7', 'i7', 'bVII'],
    loop: ['i7', 'bVImaj7', 'i7', 'bVII', 'i7', 'iv7', 'i7', 'bVI'],
  },
  {
    id: 'phrygian-fear',
    name: 'Phrygian Fear',
    tag: 'phrygian',
    mode: 'phrygian',
    romans: ['bIImaj7', 'i7', 'bVImaj7', 'bIImaj7'],
    loop: ['bIImaj7', 'i7', 'bVImaj7', 'bIImaj7', 'iv7', 'i7', 'bVII', 'bIImaj7'],
  },
  {
    id: 'half-step-dread',
    name: 'Half-Step Dread',
    tag: 'chromatic',
    mode: 'minor',
    romans: ['bIImaj7', 'i7', 'iv7', 'bVI'],
    loop: ['bIImaj7', 'i7', 'iv7', 'bVI', 'bVII', 'i7', 'bIImaj7', 'V7'],
  },
  {
    id: 'dim-passing',
    name: 'Dim Passing',
    tag: 'dim',
    mode: 'harmonicMinor',
    romans: ['vii°7', 'i(maj7)', 'V7', 'i7'],
    loop: ['vii°7', 'i(maj7)', 'V7', 'i7', 'iv7', 'V7', 'vii°7', 'i7'],
  },
  {
    id: 'm-maj7-horror',
    name: 'Minor-Maj7 Dread',
    tag: 'maj7',
    mode: 'harmonicMinor',
    romans: ['i(maj7)', 'iv7', 'V7', 'i7'],
    loop: ['i(maj7)', 'iv7', 'V7', 'i7', 'bVImaj7', 'V7', 'iv7', 'i(maj7)'],
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    tag: 'noir',
    mode: 'minor',
    romans: ['bVImaj7', 'iiø7', 'V7', 'i7'],
    loop: ['bVImaj7', 'iiø7', 'V7', 'i7', 'iv7', 'bVImaj7', 'bVII', 'i7'],
  },
  {
    id: 'creepy-drone',
    name: 'Creepy Drone',
    tag: 'drone',
    mode: 'phrygian',
    romans: ['i7', 'bII', 'bVI', 'i7'],
    loop: ['i7', 'bII', 'bVI', 'i7', 'bIImaj7', 'i7', 'bVII', 'bII'],
  },
  {
    id: 'haunted-hall',
    name: 'Haunted Hall',
    tag: 'hall',
    mode: 'minor',
    romans: ['iv7', 'i7', 'bVImaj7', 'iiø7'],
    loop: ['iv7', 'i7', 'bVImaj7', 'iiø7', 'V7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'psycho-strings',
    name: 'Psycho Strings',
    tag: 'psycho',
    mode: 'phrygian',
    romans: ['bIImaj7', 'bVImaj7', 'i7', 'bIImaj7'],
    loop: ['bIImaj7', 'bVImaj7', 'i7', 'bIImaj7', 'iv7', 'V7', 'i7', 'bVImaj7'],
  },
  {
    id: 'unresolved',
    name: 'Unresolved',
    tag: 'tension',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'iiø7', 'V7'],
    loop: ['bVII', 'bVI', 'iiø7', 'V7', 'i7', 'bVII', 'bVI', 'bVII'],
  },
  {
    id: 'witching-hour',
    name: 'Witching Hour',
    tag: 'witch',
    mode: 'harmonicMinor',
    romans: ['iv7', 'V7', 'i7', 'bVImaj7'],
    loop: ['iv7', 'V7', 'i7', 'bVImaj7', 'iiø7', 'V7', 'i7', 'iv7'],
  },
  {
    id: 'graveyard-waltz',
    name: 'Graveyard Waltz',
    tag: 'waltz',
    mode: 'minor',
    romans: ['bVImaj7', 'iv7', 'i7', 'iiø7'],
    loop: ['bVImaj7', 'iv7', 'i7', 'iiø7', 'V7', 'bVImaj7', 'iv7', 'i7'],
  },
  {
    id: 'inferno-rise',
    name: 'Inferno Rise',
    tag: 'rise',
    mode: 'phrygian',
    romans: ['bVII', 'bIImaj7', 'i7', 'V7'],
    loop: ['bVII', 'bIImaj7', 'i7', 'V7', 'bVImaj7', 'bIImaj7', 'iv7', 'i7'],
  },
  {
    id: 'blood-moon',
    name: 'Blood Moon',
    tag: 'moon',
    mode: 'minor',
    romans: ['bVI', 'iiø7', 'V7', 'i7'],
    loop: ['bVI', 'iiø7', 'V7', 'i7', 'iv7', 'bVImaj7', 'V7', 'i7'],
  },
  {
    id: 'silent-hill',
    name: 'Silent Hill',
    tag: 'hill',
    mode: 'phrygian',
    romans: ['iv7', 'bIImaj7', 'i7', 'bVI'],
    loop: ['iv7', 'bIImaj7', 'i7', 'bVI', 'bIImaj7', 'iv7', 'V7', 'i7'],
  },
  {
    id: 'anxiety-loop',
    name: 'Anxiety Loop',
    tag: 'anxiety',
    mode: 'minor',
    romans: ['iiø7', 'V7', 'i7', 'bVII'],
    loop: ['iiø7', 'V7', 'i7', 'bVII', 'iiø7', 'bVI', 'V7', 'i7'],
  },
  {
    id: 'cinematic-minor',
    name: 'Cinematic Minor',
    tag: 'cinema',
    mode: 'minor',
    romans: ['bVImaj7', 'bVII', 'iv7', 'iiø7'],
    loop: ['bVImaj7', 'bVII', 'iv7', 'iiø7', 'V7', 'i7', 'bVI', 'bVImaj7'],
  },
  {
    id: 'horror-trailer',
    name: 'Horror Trailer',
    tag: 'trailer',
    mode: 'phrygian',
    romans: ['bIImaj7', 'i7', 'V7', 'bVImaj7'],
    loop: ['bIImaj7', 'i7', 'V7', 'bVImaj7', 'iv7', 'bIImaj7', 'i7', 'V7'],
  },
  {
    id: 'dark-meditation',
    name: 'Dark Meditation',
    tag: 'meditate',
    mode: 'minor',
    romans: ['i7', 'bVII', 'bVI', 'i7'],
    loop: ['i7', 'bVII', 'bVI', 'i7', 'bVII', 'bVImaj7', 'i7', 'bVII'],
  },
  {
    id: 'nightmare-sting',
    name: 'Nightmare Sting',
    tag: 'sting',
    mode: 'harmonicMinor',
    romans: ['iv7', 'i(maj7)', 'V7', 'i7'],
    loop: ['iv7', 'i(maj7)', 'V7', 'i7', 'vii°7', 'V7', 'iv7', 'i7'],
  },
  {
    id: 'void-echo',
    name: 'Void Echo',
    tag: 'void',
    mode: 'phrygian',
    romans: ['bVImaj7', 'bIImaj7', 'i7', 'iv7'],
    loop: ['bVImaj7', 'bIImaj7', 'i7', 'iv7', 'bVII', 'bIImaj7', 'bVImaj7', 'i7'],
  },
  {
    id: 'serial-tone',
    name: 'Serial Tone',
    tag: 'serial',
    mode: 'minor',
    romans: ['bIIImaj7', 'bVI', 'iiø7', 'V7'],
    loop: ['bIIImaj7', 'bVI', 'iiø7', 'V7', 'i7', 'bVII', 'bIIImaj7', 'iv7'],
  },
  {
    id: 'basement-tape',
    name: 'Basement Tape',
    tag: 'basement',
    mode: 'minor',
    romans: ['iv7', 'bVI', 'i7', 'bVII'],
    loop: ['iv7', 'bVI', 'i7', 'bVII', 'iv7', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'ritual-circle',
    name: 'Ritual Circle',
    tag: 'ritual',
    mode: 'phrygian',
    romans: ['bII', 'bVI', 'i7', 'bIImaj7'],
    loop: ['bII', 'bVI', 'i7', 'bIImaj7', 'iv7', 'bVImaj7', 'bII', 'i7'],
  },
  {
    id: 'descent',
    name: 'Descent',
    tag: 'descent',
    mode: 'minor',
    romans: ['bVI', 'iv7', 'iiø7', 'V7'],
    loop: ['bVI', 'iv7', 'iiø7', 'V7', 'i7', 'bVImaj7', 'iv7', 'i7'],
  },
  {
    id: 'possession',
    name: 'Possession',
    tag: 'possess',
    mode: 'harmonicMinor',
    romans: ['iiø7', 'V7', 'i7', 'iv7'],
    loop: ['iiø7', 'V7', 'i7', 'iv7', 'V7', 'vii°7', 'i(maj7)', 'V7'],
  },
  {
    id: 'fog-lake',
    name: 'Fog Lake',
    tag: 'fog',
    mode: 'minor',
    romans: ['bVImaj7', 'i7', 'bVII', 'iv7'],
    loop: ['bVImaj7', 'i7', 'bVII', 'iv7', 'bVI', 'iiø7', 'V7', 'i7'],
  },
  {
    id: 'evil-approach',
    name: 'Evil Approach',
    tag: 'evil',
    mode: 'phrygian',
    romans: ['bIImaj7', 'i7', 'V7', 'bIImaj7'],
    loop: ['bIImaj7', 'i7', 'V7', 'bIImaj7', 'bVImaj7', 'iv7', 'i7', 'V7'],
  },
  {
    id: 'last-breath',
    name: 'Last Breath',
    tag: 'breath',
    mode: 'minor',
    romans: ['iv7', 'bVImaj7', 'iiø7', 'i7'],
    loop: ['iv7', 'bVImaj7', 'iiø7', 'i7', 'V7', 'iv7', 'bVII', 'i7'],
  },
  {
    id: 'end-credits',
    name: 'End Credits',
    tag: 'credits',
    mode: 'minor',
    romans: ['bVII', 'bVI', 'i7', 'iv7'],
    loop: ['bVII', 'bVI', 'i7', 'iv7', 'bVImaj7', 'bVII', 'V7', 'i7'],
  },
]);

export const SE2_SYNTH_GENO_LIVE_ALL_DEFS: Se2SynthGenoLivePresetDef[] = [
  ...SE2_SYNTH_GENO_LIVE_TRAP_DEFS,
  ...SE2_SYNTH_GENO_LIVE_HIPHOP_DEFS,
  ...SE2_SYNTH_GENO_LIVE_RNB_DEFS,
  ...SE2_SYNTH_GENO_LIVE_DARK_DEFS,
];
